var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(d,e,f){d instanceof String&&(d=String(d));for(var a=d.length,b=0;b<a;b++){var c=d[b];if(e.call(f,c,b,d))return{i:b,v:c}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(d,e,f){d!=Array.prototype&&d!=Object.prototype&&(d[e]=f.value)};$jscomp.getGlobal=function(d){return"undefined"!=typeof window&&window===d?d:"undefined"!=typeof global&&null!=global?global:d};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(d,e,f,a){if(e){f=$jscomp.global;d=d.split(".");for(a=0;a<d.length-1;a++){var b=d[a];b in f||(f[b]={});f=f[b]}d=d[d.length-1];a=f[d];e=e(a);e!=a&&null!=e&&$jscomp.defineProperty(f,d,{configurable:!0,writable:!0,value:e})}};$jscomp.polyfill("Array.prototype.find",function(d){return d?d:function(d,f){return $jscomp.findInternal(this,d,f).v}},"es6","es3");
(function(d,e){var f=e.isSecondaryComponent||function(){return!1};e.regExtension({name:"code-editor",global:{customTemplate:'<div mbr-id="_anchor" mbr-custom-code="true"></div>',encodeCodeEditorPHP:function(a,b){b._PHPplaceholders=[];return a.replace(/<\?[\w\W]+?\?>/g,function(a){var c=b._PHPplaceholders.length;b._PHPplaceholders.push(a);return"[PHP_CODE_"+c+"]"})},decodeCodeEditorPHP:function(a,b){b._PHPplaceholders&&b._PHPplaceholders.length&&(a=a.replace(/[[{]{1}PHP_CODE_([0-9]+)[\]}]{1}/ig,function(a,
d){return b._PHPplaceholders[d]||a}),a=a.replace(/\?>=""/ig,"?>").replace(/\?>=''/ig,"?>"));return a},encodeCodeEditorJS:function(a,b){b._JSplaceholders=[];return a.replace(/<script[\w\W]+?<\/script>/g,function(a){var c=b._JSplaceholders.length;-1===b._JSplaceholders.indexOf(a)&&b._JSplaceholders.push(a);return-1!==a.indexOf('type="application/json"')||-1!==a.indexOf("type='application/json'")?a:"[JS_CODE_"+c+"]"})},decodeCodeEditorJS:function(a,b){b._JSplaceholders&&b._JSplaceholders.length&&(a=
a.replace(/[[{]{1}JS_CODE_([0-9]+)[\]}]{1}/ig,function(a,d){return b._JSplaceholders[d]||a}));return a},getComponentHTMLforEditor:function(a,b){return this.getResultHTML(this.currentPage,a).then(function(c){c=this.applyFilter("resultHTMLforEditor",c,b||this.getComponent(a));c.find("> *").removeAttr("id");c.find("[data-app-edit]").each(function(){var a=d(this),b=a.attr("data-app-edit"),c="mbr-editable-"+b;"buttons"===b&&(c="mbr-editable-button",a=a.find("[data-app-btn]"));"menu"===b&&(c="mbr-editable-menu-item",
a=a.find("[data-app-btn]"));a.addClass(c)});c=c.html();c=this.cleanHTMLplease(c);c=this.APP.preparePublishVideos(c);return d.Deferred().resolve(c)}.bind(this))},convertComponentToCustomHTML:function(a){var b=this.getComponent(a);this.fire("convertComponentToCustomHTML",a);return this.getComponentHTMLforEditor(a,b).then(function(c){b._customHTML=c;b._customHTML=this.encodeCodeEditorPHP(b._customHTML,b);b._customHTML=this.encodeCodeEditorJS(b._customHTML,b);c=this.getComponentStyles(b,!0);c=c.google+
c.css;b._customCSS=c;delete b._styles;delete b._onParamsChange;delete b._publishFilter;b._customTemplate=!0;c=d(this.customTemplate);rivets.bind(c,b);this.$template.find("[data-app-component-id="+a+"] > .app-component-content").html(c);this.$template.find("[data-app-component-id="+a+"] .app-component-menu .component-params").remove();this.prepareCodeEditor(a);this.fire("convertedComponentToCustomHTML",a)}.bind(this))},addCodeEditableID:function(a){var b=this;a=b.getComponent(a);if(!f(a)&&"undefined"!=
typeof a._customHTML){var c=d("<div>").html(a._customHTML);c.find(".mbr-editable-content, .mbr-editable-full, .mbr-editable-button, .mbr-editable-menu-item, .mbr-editable-image").each(function(){d(this).attr("code-editable-id",b.uniqNum())});a._customHTML=c.html();c.remove()}},prepareCodeEditor:function(a,b,c){b=b||this.$template;if("object"===typeof a){var g=a;a=g._id}else g=this.getComponent(a);if(f(g)){a=b.find("[data-app-component-id="+a+"] > .app-component-content");var e=this.getSecondaryComponent(g);
e.isActualTemplate()||(c||a.find("> *").trigger("delete.cards"),e=e.update().createElementFromTemplate(),rivets.unbind(a).bind(e,g),a.html(e),this.fire("loadedComponent",g,this.currentPage,b,c))}else g._customHTML&&(a=b.find("[data-app-component-id="+a+"]"),a.find("[mbr-custom-code]").html(g._customHTML),c||(a.find(".app-component-content > *").trigger("add.cards"),a.css("min-height",0),b=a.find("[mbr-custom-code] *").toArray().some(function(a){return 0!==d(a).height()}),0!==a.height()||b&&a.find("[mbr-custom-code] *").length||
a.css("min-height","40px")))},renderCodeEditorChanges:function(a){this.fire("renderCodeEditorChanges",a);var b=this.getComponent(a);this.addCodeEditableID(a);this.prepareCodeEditor(a);this.fire("renderedCodeEditorChanges",a);return this.renderComponentsStyles(!1,this.currentPage,b)},changeEditableElement:function(a){a=d(a);if(a.is("[code-editable-id]")&&a.parents("[mbr-custom-code]:eq(0)").length){var b=a.attr("code-editable-id"),c=a.parents("[data-app-component-id]:eq(0)").attr("data-app-component-id");
c=this.getComponent(c);if(c._customHTML){var e=d("<div>").html(c._customHTML);b=e.find("[code-editable-id="+b+"]");a.is(".mbr-editable-button")?b.parent().html(this.cleanHTMLplease(a.parent().html(),!0)):a.is(".mbr-editable-menu-item")?b.parent().parent().html(this.cleanHTMLplease(a.parent().parent().html(),!0)):a.is(".mbr-editable-image")?b.attr("src",a.attr("src")):(a=d("<div>").html(a.clone()),b.replaceWith(this.cleanHTMLplease(a.html(),!0)),a.remove());c._customHTML=e.html();e.remove()}}}},events:{load:function(){var a=
this;a.addFilter("getResultHTMLcomponent",function(b,c){c._customHTML&&(b=a.decodeCodeEditorJS(b,c),b=a.decodeCodeEditorPHP(b,c));return b});a.addFilter("getComponentParams",function(a){return"undefined"===typeof a.current?!1:a});a.addFilter("preventComponentStylesSave",function(a,c,d,e,f,h){if(!c._customTemplate)return a;d.css(e,f);c._customCSS&&-1===c._customCSS.indexOf(h)&&(c._customCSS="@import url("+h+");\n"+c._customCSS);return!0});a.addFilter("summernoteEditableItems",function(a,c){return c.is("[code-editable-id]:not(img)")?
a.add(c):a});a.addFilter("cleanHTMLplease",function(a,c){a.find("[code-editable-id]").removeAttr("contenteditable id"+(c?"":" data-app-btn data-app-list-item code-editable-id")).removeClass("note-air-editor note-editable");a.find("[custom-code]").removeAttr("custom-code data-rv-view");return a});a.addFilter("loadComponentTemplate",function(b,c){return c._customTemplate?a.customTemplate:b});a.addFilter("getComponentStyles",function(a,c){f(c)||"undefined"==typeof c._customCSS||(a.css+=c._customCSS||
"");return a});d.isEmptyObject(a.APP.projectSettings.theme)||a.APP.redrawStyleChanger();a.$template.find(".app-component:eq(0)").length&&a.switchPage(a.currentPage)},loadedComponent:function(a,b,c){b=e.$template.find('[data-app-component-id="'+a._id+'"]');40>b.height()&&!b.find(".app-component-content *").toArray().some(function(a){return 0!==d(a).height()})&&b.css("min-height","40px");f(a)||this.prepareCodeEditor(a,c,a._checkPublish())},summernoteBlur:function(a){this.changeEditableElement(a)}}})})(jQuery,
mbrAppCore);
