var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,g){a!=Array.prototype&&a!=Object.prototype&&(a[b]=g.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(a,b){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function a(g){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(g||"")+"_"+b++,g)}var b=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};
$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var g=0,k={next:function(){if(g<a.length){var c=g++;return{value:b(c,a[c]),done:!1}}k.next=function(){return{done:!0,value:void 0}};return k.next()}};k[Symbol.iterator]=function(){return k};return k};
$jscomp.polyfill=function(a,b,g,k){if(b){g=$jscomp.global;a=a.split(".");for(k=0;k<a.length-1;k++){var c=a[k];c in g||(g[c]={});g=g[c]}a=a[a.length-1];k=g[a];b=b(k);b!=k&&null!=b&&$jscomp.defineProperty(g,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(b){return b})}},"es6","es3");
$jscomp.findInternal=function(a,b,g){a instanceof String&&(a=String(a));for(var k=a.length,c=0;c<k;c++){var n=a[c];if(b.call(g,n,c,a))return{i:c,v:n}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(b,a){return $jscomp.findInternal(this,b,a).v}},"es6","es3");$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function g(b){return b instanceof c?b:new c(function(a,r){a(b)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(b){if(null==this.batch_){this.batch_=[];var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})}this.batch_.push(b)};var k=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(b){k(b,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var b=
this.batch_;this.batch_=[];for(var a=0;a<b.length;++a){var c=b[a];b[a]=null;try{c()}catch(y){this.asyncThrow_(y)}}}this.batch_=null};b.prototype.asyncThrow_=function(b){this.asyncExecuteFunction(function(){throw b;})};var c=function(b){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var a=this.createResolveAndReject_();try{b(a.resolve,a.reject)}catch(x){a.reject(x)}};c.prototype.createResolveAndReject_=function(){function b(b){return function(d){c||(c=!0,b.call(a,d))}}var a=this,c=!1;
return{resolve:b(this.resolveTo_),reject:b(this.reject_)}};c.prototype.resolveTo_=function(b){if(b===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(b instanceof c)this.settleSameAsPromise_(b);else{a:switch(typeof b){case "object":var a=null!=b;break a;case "function":a=!0;break a;default:a=!1}a?this.resolveToNonPromiseObj_(b):this.fulfill_(b)}};c.prototype.resolveToNonPromiseObj_=function(b){var a=void 0;try{a=b.then}catch(x){this.reject_(x);return}"function"==typeof a?
this.settleSameAsThenable_(a,b):this.fulfill_(b)};c.prototype.reject_=function(b){this.settle_(2,b)};c.prototype.fulfill_=function(b){this.settle_(1,b)};c.prototype.settle_=function(b,a){if(0!=this.state_)throw Error("Cannot settle("+b+", "+a+"): Promise already settled in state"+this.state_);this.state_=b;this.result_=a;this.executeOnSettledCallbacks_()};c.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var b=0;b<this.onSettledCallbacks_.length;++b)n.asyncExecute(this.onSettledCallbacks_[b]);
this.onSettledCallbacks_=null}};var n=new b;c.prototype.settleSameAsPromise_=function(b){var a=this.createResolveAndReject_();b.callWhenSettled_(a.resolve,a.reject)};c.prototype.settleSameAsThenable_=function(b,a){var c=this.createResolveAndReject_();try{b.call(a,c.resolve,c.reject)}catch(y){c.reject(y)}};c.prototype.then=function(b,a){function g(b,a){return"function"==typeof b?function(a){try{k(b(a))}catch(m){d(m)}}:a}var k,d,r=new c(function(b,a){k=b;d=a});this.callWhenSettled_(g(b,k),g(a,d));return r};
c.prototype.catch=function(b){return this.then(void 0,b)};c.prototype.callWhenSettled_=function(b,a){function c(){switch(g.state_){case 1:b(g.result_);break;case 2:a(g.result_);break;default:throw Error("Unexpected state: "+g.state_);}}var g=this;null==this.onSettledCallbacks_?n.asyncExecute(c):this.onSettledCallbacks_.push(c)};c.resolve=g;c.reject=function(b){return new c(function(a,c){c(b)})};c.race=function(b){return new c(function(a,c){for(var k=$jscomp.makeIterator(b),d=k.next();!d.done;d=k.next())g(d.value).callWhenSettled_(a,
c)})};c.all=function(b){var a=$jscomp.makeIterator(b),k=a.next();return k.done?g([]):new c(function(b,d){function c(a){return function(d){n[a]=d;f--;0==f&&b(n)}}var n=[],f=0;do n.push(void 0),f++,g(k.value).callWhenSettled_(c(n.length-1),d),k=a.next();while(!k.done)})};return c},"es6","es3");
$jscomp.polyfill("Promise.prototype.finally",function(a){return a?a:function(b){return this.then(function(a){return Promise.resolve(b()).then(function(){return a})},function(a){return Promise.resolve(b()).then(function(){throw a;})})}},"es9","es3");
defineM("app-addons",function(a,b,g){function k(d){a("a[href^=http]",d).each(function(){a(this).data("link",a(this).attr("href"))}).attr("href","javascript:void(0)").click(function(){var d=a(this).data("link");b.openUrl(d)})}function c(f,c,m,u,g){b.getAddons(function(h){Object.keys(h).map(function(b){var a=f.filter(function(a){return b===a.name});a.length&&"archive"===a[0].status&&delete h[b]});f=f.filter(function(b){return"archive"!==b.status});var p=0,l;for(l in h)h[l].id_local=p,p++;f.sort(function(b,
a){if(b.hasOwnProperty("id")&&!a.hasOwnProperty("id"))return-1;if(!b.hasOwnProperty("id")&&a.hasOwnProperty("id"))return 1;if(!b.hasOwnProperty("id")&&!a.hasOwnProperty("id")){if(h[b.name].id_local>h[a.name].id_local)return-1;if(h[b.name].id_local<h[a.name].id_local)return 1}return 0});var w=a("<div>");c.html(w);var t=w;for(l=0;l<f.length;l++)(function(e){0===l&&(t=a('<div class="row">').appendTo(w));var f=a('<div class="panel panel-default">').appendTo(t),c=a('<div class="panel-body"></div>').appendTo(f),
p=a("<img>").attr("src",e.largeCover||e.cover),h="";h=e.new?a("<div>").html("<p>"+e.description+'</p> <div><h3 class="text-primary">'+(e.title||e.name)+"</h3><h4>NEW!</h4></div>"):a("<div>").html("<p>"+e.description+'</p> <h3 class="text-primary">'+(e.title||e.name)+"</h3>");var q=a("<div class='btn-group'>");if(e.demoUrl||h.find("p a").attr("href")){var H=a('<a href="'+(e.demoUrl||h.find("p a").eq(-1).attr("href")||h.find("p a").eq(0).attr("href"))+'">').appendTo(t);a('<div class="col-sm-6 col-md-6 col-lg-3">').append(function(){return H.append(f)}).appendTo(t);
a(h).find("p a").remove();H.click(function(d){a(d.target).parents(".btn-group").length||a(d.target).attr("href")||b.openUrl(a(this).attr("href"))})}else k(h),a('<div class="col-sm-6 col-md-6 col-lg-3">').append(f).appendTo(t);f.parents(".col-sm-6.col-md-6.col-lg-3").attr({"data-extensions-title":e.title||e.name,"data-extensions-text":a(h).find("p")[0].innerHTML,"data-extensions-type":e.new?e.type:""});c.html('<div class="media">\n<div class="media-img"></div>\n<div class="media-body"></div>\n</div>');
"theme"===e.type?e.installed||e.downloadURL?c.find(".media-img").append(p).append('<button class="btn btn-primary media-create-site">'+d("Create Site")+"</button>").click(function(a){a.preventDefault();a.stopPropagation();e.installed?n(e):u(e,function(a){a?n(e):b.hidePreloader()})}):c.find(".media-img").append(p).append('<button class="btn btn-primary media-preview">'+d("View Demo")+"</button>"):c.find(".media-img").append(p);c.find(".media-body").append(q).prepend(h);if(e.installed){if("system"!=
e.status&&a('<span class="btn btn-material-red" data-tooltipster="bottom" title="'+d("Remove")+'"><i class="mbr-icon-trash"></i></span>').click(function(){m(e)}).appendTo(q),e.installed<e.version||e.expired&&e.expiredDate<e.modified){var r=!e.downloadURL&&e.buyURL||e.installed>=e.version;a('<span class="btn btn-primary" data-tooltipster="bottom" title="'+d("Update")+'"><i class="mbr-icon-sync"></i>'+(r?"<span>&nbsp;"+e.price+"</span>":"")+"</span>").click(function(){r?g(e):u(e)}).appendTo(q)}}else"future"==
e.status?a('<button type="button" class="btn btn-default disable" data-tooltipster="bottom" title="'+d("Coming soon...")+'"><span>'+d("Soon...")+"</span></button>").css({width:"auto"}).click(function(){b.openUrl("https://mobirise.com/")}).appendTo(q):e.downloadURL&&(!e.expired||!e.premium||(e.expiredDate||Infinity)<Date.parse("2021-02-27"))&&(!e.minVersion||e.version>=e.minVersion)?a('<span class="btn btn-primary" data-tooltipster="bottom" title="'+d("Add")+'"><i class="mbr-icon-plus"></i></span>').click(function(){u(e)}).appendTo(q):
e.buyURL&&a('<span class="btn btn-primary" data-tooltipster="bottom" title="'+d("Buy")+'">'+(e.price?"<span>"+e.price+"</span>":d("Buy"))+"</span>").click(function(){g(e)}).appendTo(q);e.minAppVersion&&0>Bridge.versionCmp(Bridge.version,e.minAppVersion)||e.maxAppVersion&&0<Bridge.versionCmp(Bridge.version,e.maxAppVersion)||e.minVersion&&e.version<e.minVersion&&!e.expired||e.disabled?(c.addClass("uncompatible").attr("data-tooltipster","top").attr("title",d("Not available for your Mobirise version")),
console.log("Uncompatible version of addon "+e.name)):(e.installed&&e.installed<e.minVersion&&c.addClass("disabled").attr("data-tooltipster","top").attr("title",d("Not compatible with your version of Mobirise")),h.find(e.new?"div":"h3").css("max-width","calc( 100% - "+(q.width()+11)+"px)"))})(f[l])})}function n(f){var c="Site-"+Bridge.dateFormat(new Date,"MM-dd_hhmm");f={name:f.name,title:f.title};b.showPreloader();b.applyFilter("promiseChosenTheme",Promise.resolve(f)).then(function(f){setTimeout(function(){a(".preloader").css("opacity",
1)},1);$Bridge.getSettings("dontShowCreateSiteModal").then(function(l){function m(){b.closeSidebar();b.runSaveProject(function(h){h||console.error("Error: unable to save current project");b.createProject(c,0,f,function(a){a&&b.showError(d("Unexpected project create error ")+" ("+a+").",function(){b.showProjectsList()})});a("#addonsModal").hide()},!0)}if("true"!==l)var h=b.showDialog({body:['<div class="form-group">',d("Do you want to create the $site name$ site based on the $theme name$ theme, $name preset$ Template?").replace("$site name$",
"<strong>"+c+"</strong>").replace(f.titlePreset?"$name preset$":", $name preset$ Template",f.titlePreset?"<strong>"+f.titlePreset+"</strong>":"").replace("$theme name$","<strong>"+f.title+"</strong>"),'</div>\n<div class="dont-show-more clearfix">\n   <div class="togglebutton">\n       <label style="width: 100%;">\n           <input type="checkbox" id="dont-show-again">\n           <span class="toggle" style="margin-top: -6px;"></span>',d("Don't show again"),"       </label>\n   </div>\n</div>"].join("\n"),
buttons:{cancel:{label:d("Cancel"),className:"btn-default"},success:{label:d("Ok"),className:"btn-primary",callback:function(){var b=h.find("#dont-show-again")[0].checked;$Bridge.setSettings("dontShowCreateSiteModal",b);m()}}}}).on("hidden.bs.modal",function(){b.hidePreloader()});else m()})}).catch(function(){b.closeSidebar();b.hidePreloader()})}function r(a){var f=jQuery.Deferred();Bridge.loadLocalFile(b.getAddonDir(a.name)+"/splash.html",function(c){var m="theme"===a.type?d("theme"):d("extension");
C({body:d("$extension$ is successfuly added").replace("$extension$",'"'+a.title+'" '+m+" ")+".\n"+(c||"").replace('src="','src="'+b.getAddonDir(a.name)+"/"),title:d("About"),size:"large",onhide:function(){f.resolve()}})});return f}function C(b){b=b||{};var d=b.body;if("string"==typeof d)for(var c in b)d=d.replace("@"+c+"@",b[c]);c=a(D).attr("id",b.id).insertBefore("#insertBefore");"large"==b.size&&(c.addClass("bs-example-modal-lg"),c.find(".modal-dialog").addClass("modal-lg"));c.find(".modal-body").append(d);
c.find(".modal-title").append(b.title);c.on("hidden.bs.modal",function(){a(this).data("modal",null);if(b.onhide)b.onhide();a(this).remove()});if(b.onbeforeshow)b.onbeforeshow(c);c.modal("show");return c}function x(c){function f(a){return new Promise(function(c,f){b.getAddons(function(h){a in h?f(null):b.getAddonsEx(0,0,{server:!0,serverOptions:{with_archive:1},restricted:!0}).then(function(h,p,g){var e=!1;h.map(function(h){h.name===a&&(e=!0,b.downloadAddon(h).done(function(b){c(h)}).fail(function(){b.alertDlg(d("Error add extension")+
' "'+h.title+'"').on("hidden.bs.modal",function(){f()})}))});e||f(Error("Addon "+a+" is not available!"))}).catch(function(b){f(b)})})})}var m=C({id:"redeemModal",title:d("Redeem code"),body:'<div class="input-group"><input type="text" class="form-control" placeholder="'+d("Enter code...")+'"><span class="input-group-btn"><button class="btn btn-primary" type="button">'+d("Redeem")+"</button></span></div>"});m.find("button.btn-primary").click(function(){var l=m.find("input").val();if(l){var k=a(b.preloaderHTML);
a("#addonsModal").append(k);m.find("input,button").prop("disabled",!0);g.activate(l).then(function(a){b.fire("redeemActivated");var h=[],l=!1;a&&!a.length&&h.push(f("code-editor").then(function(){l=!0}));(a||[]).forEach(function(a,c){a&&a.downloadURL||!a||"subscription"!==a.type?(c=new Promise(function(c,f){b.downloadAddon(a).done(function(b){"code-editor"===b.name&&(l=!0);k.remove();r(b).always(function(){c(a)})}).fail(function(){k.remove();b.alertDlg(d("Error add extension")+' "'+a.title+'"').on("hidden.bs.modal",
function(){f(a)})})}),h.push(c)):(c=f("code-editor").then(function(){l=!0}),console.log("Successful subscription to the "+a.title),h.push(c))});Promise.all(h).finally(function(){k.remove();b.alertDlg(d("Code is successfully redeemed!")).on("hidden.bs.modal",function(){m.find("input,button").prop("disabled",!1);m.modal("hide");l?Bridge.reload():c&&c()})})},function(c,f,l){k.remove();1211==f&&(c=d("Incorrect code"));1212==f&&(c=d("Activation error"));c=l?"<a class='ex-info-link' href='javascript:void(0)'>"+
c+"</a> ("+f+")<div style='display:none;-webkit-user-select:all'>"+(l+"</div>"):c+(" ("+f+")");b.alertDlg(c).find("a.ex-info-link").click(function(){a(this).parent().find("div").show()});m.find("input,button").prop("disabled",!1);b.handleServerError(c,f)})}})}function y(c){Bridge.runFileDialog(d("Select extension package"),Bridge.docLocation,"Mobirise Extension (*.mbrext)",function(f){if(f){var l=Bridge.splitPath(f).fullname;b.confirmDlg({className:"import-dialog",title:l+" - "+d("Unknown Source Warning!"),
message:d("You're importing an extension from unknown sources. Extension from unknown sources can harm your projects and bring incompatibility issues with Mobirise app and other extensions. Mobirise doesn't provide a support for 3rd-party extensions."),buttons:{confirm:{label:d("Import Anyway"),className:"btn-default"},cancel:{label:d("Ok"),className:"btn-primary"}},callback:function(l){if(l){var g=a(b.preloaderHTML);a("#addonsModal").append(g);b.extractAddon(f,function(a){g.remove();if(a){a.minAppVersion&&
0>Bridge.versionCmp(Bridge.version,a.minAppVersion)&&b.alertDlg(d("This extension works with app version $ext_version$ and higher. Please update your Mobirise app").replace("$ext_version$",a.minAppVersion));console.log("imported package:",a);var f=b.pkgParams2addon(a);b.fire("importedAddon",f);r(f).always(function(){c&&c(f)})}else b.alertDlg(d("Error add extension package")).on("hidden.bs.modal",function(){c&&c()})})}}})}else c&&c()})}function d(a){return b.TR?b.TR(a,"app-addons"):a}var K=/\.mbrext$/,
D='<div class="modal">  <div class="modal-dialog">    <div class="modal-content">      <div class="modal-header">        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>        <h4 class="modal-title"></h4>      </div>      <div class="modal-body">        <div class="placeholder hide">'+d("No extensions matched your search. Try again.")+"</div>      </div>    </div>  </div></div>";b.regExtension({name:"addons",global:{addonPackageExt:"mbrext",
$addonsBlock:0,showAddonsList:function(f,l){b.checkSign(function(g){function k(){var a=b.getUserInfo();p.find(".modal-title").replaceWith('<h3 class="modal-title">'+h+(a&&a.email?" ("+a.email+")":"")+"</h3>")}if(g){b.fire("clearAutoUpdateTimeout");var m=a(b.preloaderHTML),h=d("Extensions"),p=C({id:"addonsModal",title:h,body:m,onhide:function(){l?(console.log("rebooting..."),Bridge.reload()):(Bridge.isDev||(b.off("updateAllStop",A),b.off("updateAllStart",B)),f&&f())},onbeforeshow:function(b){b.find(".modal-header>*").wrapAll('<div class="modal-header-wrapper">')}});
k();var q=p.find(".modal-body");g=p.find(".modal-header-wrapper");var n=a('<a href="javascript:void(0)" class="redeem-ext">'+d("Redeem")+"</a>"),t=a('<a href="javascript:void(0)" class="import-ext">'+d("Import")+"</a>"),e=a('<a href="javascript:void(0)" class="update-all-ext">'+d("Update All")+"</a>"),E=a('<a href="javascript:void(0)" class="add-all-ext">'+d("Add All")+"</a>"),z=a('<div class="col-md-4" id="filter-extensions"><input name="name" type="text" placeholder="'+d("Search")+'" value="" class="form-control"></div>');
n.click(function(){b.checkSign(function(b){b&&(k(),x(v))})}).appendTo(g);t.click(function(){b.checkSign(function(a){a&&(k(),y(function(a){if(a){if(a.name===b.theme.name||"theme"!==a.type)l=!0;v()}}))})}).appendTo(g);if(!Bridge.isDev){var I=function(){b.checkSign(function(a){a&&(k(),b.showDialog({title:d("Do you want to download all available themes and extensions?"),successLabel:d("Download all"),success:function(){b.updateAllStart(!0,!1).then(v)},hide:function(){},cancel:function(){}}))})};e.click(function(){b.checkSign(function(a){a&&
(k(),b.showDialog({title:d("Update all installed extensions?"),successLabel:d("Update"),success:function(){b.updateAllStart(!0).then(function(){Bridge.reload()})},cancel:function(){}}))})}).appendTo(g);E.click(function(){I()}).appendTo(g);document.addEventListener("keyup",function(b){1==b.shiftKey&&1==b.ctrlKey&&65==b.keyCode&&I()});var A=function(){b.off("updateAllStop",A);b.on("updateAllStart",B);n.removeClass("disabled");t.removeClass("disabled");e.removeClass("disabled");E.removeClass("disabled")},
B=function(){b.off("updateAllStart",B);b.on("updateAllStop",A);n.addClass("disabled");t.addClass("disabled");e.addClass("disabled");E.addClass("disabled");b.updateAllAppendLoader(F)};b.isUpdatingNow?B():A()}var J=function(){var b=p.find("#filter-extensions > input").val().toLowerCase(),c=a(".list-view .row").children();c.forEach=[].forEach;c.forEach(function(b){return b.classList.remove("hide")});if(""===b)a("#addonsModal .placeholder").addClass("hide");else{b=b.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g,
"\\$&");var d=a(c).filter(function(a){return void 0!==this?this.dataset.extensionsTitle||this.dataset.extensionsText?!(~this.dataset.extensionsTitle.toLowerCase().search(b)||~this.dataset.extensionsText.toLowerCase().search(b)):"":1});d.forEach=[].forEach;d.forEach(function(b){return b.classList.add("hide")});c.length===d.length?a("#addonsModal .placeholder").removeClass("hide"):a("#addonsModal .placeholder").addClass("hide")}};z.on("blur","input",function(a){b.fire("inputBlur",a.target)});z.on("keyup",
"input",J).appendTo(g);p.find(".modal-header .close").replaceWith('<div class="app-layer"><span class="app-layer-close mbr-icon-angle-left" data-dismiss="modal"></span></div>');var G=a('<div class="extensions-info">'+d("Note: The server list is not available. Only installed extensions are shown")+'. <a href="javascript:void(0)">'+d("Get more extensions")+"</a></div>").appendTo(q),F=a('<div class="list-view">').appendTo(q),D=a("<h4>"+d("Extensions")+'</h4><div id="themes-list"></div>').appendTo(F),
v=function(){function f(e,g,p){b.getAddonsEx(0,g?{type:g}:0,{server:p,serverOptions:{with_archive:1},restricted:!0}).then(function(u,n,w){w?(p=w,G.hide()):G.show();0>=--h&&(a(".preloader-spinner").remove(),b.isUpdatingNow&&b.updateAllAppendLoader(F));u=u.filter(function(b){return!("mobirise5"==b.name||"startm5"==b.name)});c(u,e,function(a,c){b.disableAddon(a.name,function(d){if(d){b.fire("deletedAddon",a);f(e,g,p);if("theme"!==a.type||b.theme.name===a.name)l=!0;c&&c(!0)}})},function(a,c){var f=a.downloadURL||
"",e=b.getUserInfo();e&&e.email?(q.append(m),setTimeout(function(){b.downloadAddon(a).done(function(a){if(a){v();console.log(!a.theme);if(a.name===b.theme.name||"theme"!==a.type)l=!0;r(a).always(function(){c&&c(!0)})}else m.remove()}).fail(function(e,g){b.alertDlg(e+' "'+a.title+'".'+(f?"":d("Try to log out and log back in"))).on("hidden.bs.modal",function(){c&&c(!1)});m.remove()})},100)):b.checkSign(function(b){b&&(k(),v())})},function(a,c){b.openUrl(a.buyURL)});b.fire("showedAddonsList",u);J()})}
function e(){f(D,0,!0)}var h=1;z.find("input").val("");z.find("input").trigger("keyup");G.click(e);e();b.checkAccountExpired();b.off("signedin",v)};v();b.on("signedin",v);b.fire("shownAddonsDialog",p)}})},downloadAddon:function(a,c,k){function f(){h.reject(d("Download cancelled: "),1303);Bridge.stopDownload(l);b.off("cancelDownloadAddon",f)}var l=a.downloadURL;console.log("Start download "+l);b.fire("downloadAddon",a);var h=jQuery.Deferred();if(!l)return h.reject(d("Unable to download $extension$. Try to re-login.").replace("$extension$",
a.name||"extension"),1302);b.on("cancelDownloadAddon",f);g.download(l,function(f){if(c)k&&k({msg:a.title,currentAddon:f});else switch(f){case 0:b.progressBar("isCanceled")&&(b.progressBar("show",d("Downloading..."),a.title),b.$progressModal.removeClass("passive"));break;case 1:b.progressBar("hide");break;default:b.progressBar({progress:Math.floor(100*f)}),console.log("Download progress "+f)}}).then(function(a){b.off("cancelDownloadAddon",f);b.extractAddon(a,function(a){a?(a=b.pkgParams2addon(a),console.log("Loaded new addon "+
a.name),b.fire("downloadedAddon",a),h.resolve(a)):h.reject("\u0410n error occurred while extracting",1301)},c)},function(a,c){b.off("cancelDownloadAddon",f);h.reject(a,c);b.handleServerError(a,c)});return h},extractAddon:function(a,c,d){d=void 0===d?!1:d;var f=Bridge.tempLocation+"/addon"+Bridge.dateFormat(new Date,"yyyyMMdd_hhmmss");c=c||function(){};Bridge.unzip(a,f,function(g){g?Bridge.getLocalJSON(f+"/params.json",function(g){var h=b.pkgParams2addon(g||{}),k=h.name;if(k){var l=b.getAddonsDir()+
"/"+k;!d||"plugin"!==h.type&&h.name!==b.theme.name||(l+="-new",h.newVersion=!0);Bridge.isExistsLocal(l.replace(/\-new$/,""),function(a){a||!d||"plugin"!==h.type&&h.name!==b.theme.name||(Bridge.removeLocal(l),l=l.replace(/\-new$/,""));Bridge.copyLocal(f,l,function(a){a?b.enableAddon(h,function(a){b.fire("extractedAddon");c(g)}):(console.log("Error: component '"+h.name+"' is not registered"),c());Bridge.removeLocal(f)})})}else console.log("Error: wrong params.json file of addon "+a),c()}):(console.log("Extraction error ",
a,"to",f),c())})}},events:{load:function(){this.$addonsBlock=b.addSidebarItem({title:d("Extensions"),tooltip:d("Add Themes and Extensions"),onclick:function(){b.showAddonsList()}});b.on(["accountInited","signedin"],function(){!1!==b.getUserInfo()&&b.getAddons(function(a){"code-editor"in a||b.$body.find(".nav.navbar-nav.navbar-right .app-mobi-kit").length||(b.$body.find(".nav.navbar-nav.navbar-right").append('<li class="app-mobi-kit" data-tooltipster="bottom" title="'+d("Get ALL Mobirise Themes & Extensions!")+
'">\n                                            <a href="javascript:void(0)">\n                                                <i class="mbr-icon-shapes"></i>\n                                            </a>\n                                        </li>'),b.$body.find(".nav.navbar-nav.navbar-right .app-mobi-kit").click(function(){b.openUrl("https://mobirise.com/extensions/kit/")}))})})},addonsOff:function(){var c=this;a(".preloader").hide();b.showDialog({title:d("Warning"),body:d("During the last run the program failed to load all extensions. To run again, program will temporarily disable them."),
buttons:{ok:{label:d("Ok"),className:"btn-primary"}},onhide:function(){c.showAddonsList()}})},addonsLoaded:function(c,g){var f=this;a(".preloader").delay(600).fadeOut(1E3,function(){a(this).hide()});if(g&&g.length){c="";for(var k=0;k<g.length;k++)g[k].disabled||(c+=(c?",":"")+'"'+g[k].title+'"');c&&b.confirmDlg({message:d('Some installed extensions $ext names$ are not compatible with the current version of the application. Please visit "Extensions list" dialog to update it.').replace("$ext names$",
"("+c+")"),buttons:{cancel:{label:d("Cancel"),className:"btn-default"},confirm:{label:d('Open "Extensions list"'),className:"btn-primary"}},callback:function(a){a&&f.showAddonsList()}})}},incomingFile:function(a){K.test(a)&&b.extractAddon(a,function(a){console.log(a)})}}})},["jQuery","mbrApp","mbrServer"]);
