var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(b,a,e){b instanceof String&&(b=String(b));for(var g=b.length,f=0;f<g;f++){var l=b[f];if(a.call(e,l,f,b))return{i:f,v:l}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,a,e){b!=Array.prototype&&b!=Object.prototype&&(b[a]=e.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(b,a,e,g){if(a){e=$jscomp.global;b=b.split(".");for(g=0;g<b.length-1;g++){var f=b[g];f in e||(e[f]={});e=e[f]}b=b[b.length-1];g=e[b];a=a(g);a!=g&&null!=a&&$jscomp.defineProperty(e,b,{configurable:!0,writable:!0,value:a})}};$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(a,b){return $jscomp.findInternal(this,a,b).v}},"es6","es3");$jscomp.arrayIteratorImpl=function(b){var a=0;return function(){return a<b.length?{done:!1,value:b[a++]}:{done:!0}}};
$jscomp.arrayIterator=function(b){return{next:$jscomp.arrayIteratorImpl(b)}};$jscomp.makeIterator=function(b){var a="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];return a?a.call(b):$jscomp.arrayIterator(b)};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(b){function a(){this.batch_=null}function e(a){return a instanceof f?a:new f(function(b,h){b(a)})}if(b&&!$jscomp.FORCE_POLYFILL_PROMISE)return b;a.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})}this.batch_.push(a)};var g=$jscomp.global.setTimeout;a.prototype.asyncExecuteFunction=function(a){g(a,0)};a.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var h=a[b];a[b]=null;try{h()}catch(c){this.asyncThrow_(c)}}}this.batch_=null};a.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var f=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(h){b.reject(h)}};f.prototype.createResolveAndReject_=function(){function a(a){return function(c){h||(h=!0,a.call(b,c))}}var b=this,h=!1;
return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};f.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof f)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};f.prototype.resolveToNonPromiseObj_=function(a){var b=void 0;try{b=a.then}catch(h){this.reject_(h);return}"function"==typeof b?
this.settleSameAsThenable_(b,a):this.fulfill_(a)};f.prototype.reject_=function(a){this.settle_(2,a)};f.prototype.fulfill_=function(a){this.settle_(1,a)};f.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};f.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)l.asyncExecute(this.onSettledCallbacks_[a]);
this.onSettledCallbacks_=null}};var l=new a;f.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};f.prototype.settleSameAsThenable_=function(a,b){var h=this.createResolveAndReject_();try{a.call(b,h.resolve,h.reject)}catch(c){h.reject(c)}};f.prototype.then=function(a,b){function h(a,b){return"function"==typeof a?function(b){try{c(a(b))}catch(p){n(p)}}:b}var c,n,d=new f(function(a,b){c=a;n=b});this.callWhenSettled_(h(a,c),h(b,n));return d};
f.prototype.catch=function(a){return this.then(void 0,a)};f.prototype.callWhenSettled_=function(a,b){function h(){switch(c.state_){case 1:a(c.result_);break;case 2:b(c.result_);break;default:throw Error("Unexpected state: "+c.state_);}}var c=this;null==this.onSettledCallbacks_?l.asyncExecute(h):this.onSettledCallbacks_.push(h)};f.resolve=e;f.reject=function(a){return new f(function(b,h){h(a)})};f.race=function(a){return new f(function(b,h){for(var c=$jscomp.makeIterator(a),n=c.next();!n.done;n=c.next())e(n.value).callWhenSettled_(b,
h)})};f.all=function(a){var b=$jscomp.makeIterator(a),h=b.next();return h.done?e([]):new f(function(a,n){function c(b){return function(c){g[b]=c;f--;0==f&&a(g)}}var g=[],f=0;do g.push(void 0),f++,e(h.value).callWhenSettled_(c(g.length-1),n),h=b.next();while(!h.done)})};return f},"es6","es3");
$jscomp.polyfill("Array.from",function(b){return b?b:function(a,b,g){b=null!=b?b:function(a){return a};var e=[],l="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if("function"==typeof l){a=l.call(a);for(var k=0;!(l=a.next()).done;)e.push(b.call(g,l.value,k++))}else for(l=a.length,k=0;k<l;k++)e.push(b.call(g,a[k],k));return e}},"es6","es3");
$jscomp.checkEs6ConformanceViaProxy=function(){try{var b={},a=Object.create(new $jscomp.global.Proxy(b,{get:function(e,g,f){return e==b&&"q"==g&&f==a}}));return!0===a.q}catch(e){return!1}};$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS=!1;$jscomp.ES6_CONFORMANCE=$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS&&$jscomp.checkEs6ConformanceViaProxy();$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(b,a){this.$jscomp$symbol$id_=b;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:a})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function b(e){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(e||"")+"_"+a++,e)}var a=0;return b}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.iterator;b||(b=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[b]&&$jscomp.defineProperty(Array.prototype,b,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.asyncIterator;b||(b=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(b){$jscomp.initSymbolIterator();b={next:b};b[$jscomp.global.Symbol.iterator]=function(){return this};return b};$jscomp.owns=function(b,a){return Object.prototype.hasOwnProperty.call(b,a)};
$jscomp.polyfill("WeakMap",function(b){function a(){if(!b||!Object.seal)return!1;try{var a=Object.seal({}),n=Object.seal({}),d=new b([[a,2],[n,3]]);if(2!=d.get(a)||3!=d.get(n))return!1;d.delete(a);d.set(n,4);return!d.has(a)&&4==d.get(n)}catch(r){return!1}}function e(){}function g(a){var b=typeof a;return"object"===b&&null!==a||"function"===b}function f(a){if(!$jscomp.owns(a,k)){var b=new e;$jscomp.defineProperty(a,k,{value:b})}}function l(a){var b=Object[a];b&&(Object[a]=function(a){if(a instanceof
e)return a;f(a);return b(a)})}if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(b&&$jscomp.ES6_CONFORMANCE)return b}else if(a())return b;var k="$jscomp_hidden_"+Math.random();l("freeze");l("preventExtensions");l("seal");var q=0,h=function(a){this.id_=(q+=Math.random()+1).toString();if(a){a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};h.prototype.set=function(a,b){if(!g(a))throw Error("Invalid WeakMap key");f(a);if(!$jscomp.owns(a,k))throw Error("WeakMap key fail: "+
a);a[k][this.id_]=b;return this};h.prototype.get=function(a){return g(a)&&$jscomp.owns(a,k)?a[k][this.id_]:void 0};h.prototype.has=function(a){return g(a)&&$jscomp.owns(a,k)&&$jscomp.owns(a[k],this.id_)};h.prototype.delete=function(a){return g(a)&&$jscomp.owns(a,k)&&$jscomp.owns(a[k],this.id_)?delete a[k][this.id_]:!1};return h},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(b){function a(){if($jscomp.ASSUME_NO_NATIVE_MAP||!b||"function"!=typeof b||!b.prototype.entries||"function"!=typeof Object.seal)return!1;try{var a=Object.seal({x:4}),c=new b($jscomp.makeIterator([[a,"s"]]));if("s"!=c.get(a)||1!=c.size||c.get({x:4})||c.set({x:4},"t")!=c||2!=c.size)return!1;var n=c.entries(),d=n.next();if(d.done||d.value[0]!=a||"s"!=d.value[1])return!1;d=n.next();return d.done||4!=d.value[0].x||"t"!=d.value[1]||!n.next().done?!1:!0}catch(r){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(b&&$jscomp.ES6_CONFORMANCE)return b}else if(a())return b;$jscomp.initSymbolIterator();var e=new WeakMap,g=function(a){this.data_={};this.head_=k();this.size=0;if(a){a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};g.prototype.set=function(a,b){a=0===a?0:a;var c=f(this,a);c.list||(c.list=this.data_[c.id]=[]);c.entry?c.entry.value=b:(c.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:a,
value:b},c.list.push(c.entry),this.head_.previous.next=c.entry,this.head_.previous=c.entry,this.size++);return this};g.prototype.delete=function(a){a=f(this,a);return a.entry&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.data_[a.id],a.entry.previous.next=a.entry.next,a.entry.next.previous=a.entry.previous,a.entry.head=null,this.size--,!0):!1};g.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=k();this.size=0};g.prototype.has=function(a){return!!f(this,a).entry};
g.prototype.get=function(a){return(a=f(this,a).entry)&&a.value};g.prototype.entries=function(){return l(this,function(a){return[a.key,a.value]})};g.prototype.keys=function(){return l(this,function(a){return a.key})};g.prototype.values=function(){return l(this,function(a){return a.value})};g.prototype.forEach=function(a,b){for(var c=this.entries(),d;!(d=c.next()).done;)d=d.value,a.call(b,d[1],d[0],this)};g.prototype[Symbol.iterator]=g.prototype.entries;var f=function(a,b){var c=b&&typeof b;"object"==
c||"function"==c?e.has(b)?c=e.get(b):(c=""+ ++q,e.set(b,c)):c="p_"+b;var d=a.data_[c];if(d&&$jscomp.owns(a.data_,c))for(a=0;a<d.length;a++){var g=d[a];if(b!==b&&g.key!==g.key||b===g.key)return{id:c,list:d,index:a,entry:g}}return{id:c,list:d,index:-1,entry:void 0}},l=function(a,b){var c=a.head_;return $jscomp.iteratorPrototype(function(){if(c){for(;c.head!=a.head_;)c=c.previous;for(;c.next!=c.head;)return c=c.next,{done:!1,value:b(c)};c=null}return{done:!0,value:void 0}})},k=function(){var a={};return a.previous=
a.next=a.head=a},q=0;return g},"es6","es3");
$jscomp.polyfill("Set",function(b){function a(){if($jscomp.ASSUME_NO_NATIVE_SET||!b||"function"!=typeof b||!b.prototype.entries||"function"!=typeof Object.seal)return!1;try{var a=Object.seal({x:4}),e=new b($jscomp.makeIterator([a]));if(!e.has(a)||1!=e.size||e.add(a)!=e||1!=e.size||e.add({x:4})!=e||2!=e.size)return!1;var l=e.entries(),k=l.next();if(k.done||k.value[0]!=a||k.value[1]!=a)return!1;k=l.next();return k.done||k.value[0]==a||4!=k.value[0].x||k.value[1]!=k.value[0]?!1:l.next().done}catch(q){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(b&&$jscomp.ES6_CONFORMANCE)return b}else if(a())return b;$jscomp.initSymbolIterator();var e=function(a){this.map_=new Map;if(a){a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)this.add(b.value)}this.size=this.map_.size};e.prototype.add=function(a){a=0===a?0:a;this.map_.set(a,a);this.size=this.map_.size;return this};e.prototype.delete=function(a){a=this.map_.delete(a);this.size=this.map_.size;return a};e.prototype.clear=function(){this.map_.clear();
this.size=0};e.prototype.has=function(a){return this.map_.has(a)};e.prototype.entries=function(){return this.map_.entries()};e.prototype.values=function(){return this.map_.values()};e.prototype.keys=e.prototype.values;e.prototype[Symbol.iterator]=e.prototype.values;e.prototype.forEach=function(a,b){var e=this;this.map_.forEach(function(f){return a.call(b,f,f,e)})};return e},"es6","es3");
$jscomp.polyfill("Object.is",function(b){return b?b:function(a,b){return a===b?0!==a||1/a===1/b:a!==a&&b!==b}},"es6","es3");$jscomp.polyfill("Array.prototype.includes",function(b){return b?b:function(a,b){var e=this;e instanceof String&&(e=String(e));var f=e.length;b=b||0;for(0>b&&(b=Math.max(b+f,0));b<f;b++){var l=e[b];if(l===a||Object.is(l,a))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(b,a,e){if(null==b)throw new TypeError("The 'this' value for String.prototype."+e+" must not be null or undefined");if(a instanceof RegExp)throw new TypeError("First argument to String.prototype."+e+" must not be a regular expression");return b+""};$jscomp.polyfill("String.prototype.includes",function(b){return b?b:function(a,b){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,b||0)}},"es6","es3");
defineM("app-pages",function(b,a,e,g){function f(){var c=a.getCurrentPageName();a.$navbarPageName.html(a.getPages()[c].settings.title||"");var e=b(".navbar-project-info .app-page-url-separator"),d=b(".navbar-project-info .app-page-url");"index.html"===c?(e.hide(),d.html("")):(e.show(),d.html(c))}function l(b){for(var c=b.children().length,d=0;d<c;d++){var e=b.children().eq(d).find("a").attr("data-page");a.currentPageSettings=e;a.changePageSettings("order",d+1)}}function k(){a.$pageSettings.find(".page-settings-chrome-preview").hasClass("chrome-preview-mobile")?
a.$pageSettings.find(".chrome-preview-url").text("https://yoursite.com"+("index.html"===a.currentPageSettings?"":" > "+a.currentPageSettings)):a.$pageSettings.find(".chrome-preview-url").text("https://yoursite.com/"+("index.html"===a.currentPageSettings?"":a.currentPageSettings))}var q=!0,h=function(){function c(c,d){return function(m){if(m.image.src)if(m=m.image.src,0<=m.indexOf(a.path2core(a.getAddonDir(a.theme.name)+"/components"))&&(m=m.replace(/^\.\.\/\.\.\//,"")),a.Core.resultJSON[a.Core.currentPage].settings.meta_image=
m,d)b(d).css({display:"block"}).attr("src",m),b(d).css({height:d.width/1.91});else{var e=b(c).closest(".form-group").find(".social-sharing-on-mobirise").css({display:"block"}).find("img");b(c).closest(".form-group").find(".social-sharing-on-users").css({display:"none"});b(c).closest(".form-group").find(".social-sharing-on-mobirise").css({display:"block"});e.on("load",function(){e.css({height:e.width()/1.91})});e.css({display:"block"});e.attr("src",m)}else a.$pageSettings.find("#metaShareImage").trigger("click")}}
function e(a,b,c,d){a<b&&d(c[a]).catch(function(){a++;e(a,b,c,d)})}function d(){return new Promise(function(b,c){c=a.Core.resultJSON[a.Core.currentPage].components;c.length?c.some(function(c,d,m){if(-1!==c._name.search("menu"))return d+1===m.length?(b(),!0):!1;var p=(a.Core.$template.find("[data-app-component-id="+c._id+"] > *").html().match(/<img[^>]* src="([^"]*)"[^>]*>/ig)||[]).map(function(a){return a.match(/<img[^>]* src="([^"]*)"[^>]*>/i)[1]});p=p.map(function(b){return a.core2abs(b)});if(p.length)return e(0,
Array.from(new Set(p)).length,Array.from(new Set(p)),function(a){return new Promise(function(c,d){var m=new Image;m.onload=function(){400<=m.width?b(a):d()};m.src=a})}),!0;if(c._params&&c._params.bg&&"image"===c._params.bg.type)return b(c._params.bg.value),!0;m.length-1===d&&b()}):b()})}function f(e){a.Core.resultJSON[a.Core.currentPage].settings.meta_image?b(e).closest(".form-group").find(".social-sharing-on-users").css({display:"none"}):d().then(function(b){a.showMediaImageDialog({image:{width:2E3,
quality:70,src:b||""}},c(e),!0)})}return{init:function(){function d(b){var c=a.Core.getPages(),d;for(d in c)if(c.hasOwnProperty(d)&&c[d].settings.meta_image){var m=c[d].settings.meta_image,e=g.splitPath(m),n=e.ext;b.push({srcList:[{src:m}],dest:a.IMAGES_FOLDER+"/"+e.fullname});b.push({srcList:[{src:m}],dest:a.IMAGES_FOLDER+"/"+d.replace(/.html/ig,"")+"-meta."+n})}return b}a.$pageSettings.on("click","#metaShareImage",function(c){b(c.target).is(":checked")?f(c.currentTarget):(c=c.currentTarget,delete a.Core.resultJSON[a.Core.currentPage].settings.meta_image,
b(c).closest(".form-group").find(".social-sharing-on-mobirise").css({display:"none"}).find("img").attr("src",""),b(c).closest(".form-group").find(".social-sharing-on-users").css({display:"block"}))});a.$pageSettings.on("click","img.social-sharing-on-mobirise__img",function(d){var m={image:{width:2E3,quality:70,src:b(d.currentTarget).attr("src")}};0<=m.image.src.indexOf(a.getAddonDir(a.theme.name).replace("web/",""))&&(m.image.src="../../"+m.image.src);a.showMediaImageDialog(m,c(!1,d.currentTarget),
!0)});a.on("cancelMediaImageDialog",function(b){a.$pageSettings.find(".social-sharing-on-mobirise__img").attr("src")||a.$pageSettings.find("#metaShareImage").trigger("click")});a.on("closeMediaImageDialog",function(b){a.$pageSettings.find(".social-sharing-on-mobirise__img").attr("src")||a.$pageSettings.find("#metaShareImage").trigger("click")});a.addFilter("publishHTML",function(b,c){var d=c.settings,e=void 0===d.meta_image?"":d.meta_image;d=void 0===d.socialSharingUrl?"":d.socialSharingUrl;e?(e=
g.splitPath(e).ext,c='<meta name="twitter:card" content="summary_large_image"/>\n  <meta name="twitter:image:src" content="'+a.IMAGES_FOLDER+"/"+c.settings.currentPageName.replace(/\.html/ig,"")+"-meta."+e+'">\n  <meta property="og:image" content="'+a.IMAGES_FOLDER+"/"+c.settings.currentPageName.replace(/\.html/ig,"")+"-meta."+e+'">\n  <meta name="twitter:title" content="'+c.settings.title+'">\n  ',b=b.replace('<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1"',
c+'<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1"')):d&&(b=b.replace('<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1"','<meta name="twitter:card" content="summary_large_image"/>\n  <meta name="twitter:image:src" content="'+d+'">\n  <meta property="og:image" content="'+d+'">\n  <meta name="twitter:title" content="'+c.settings.title+'">\n  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1"'));
return b});a.addFilter("publishFiles",function(a){return d(a)});a.addFilter("exportProjectFiles",function(a){return d(a)})}}}();a.regExtension({name:"pages",global:{$navbarPageName:b(".app-page-name"),$pagesList:b("#app-pages-list"),$pagesListToggle:b(".pages-block"),currentPageSettings:void 0,$pageSettings:b("#app-page-settings"),pageSettingsInputs:"[data-page-settings]",showPagesList:function(){this.$body.hasClass("app-pages-list-open")&&this.$body.hasClass("app-page-settings-open")||(this.fire("showSideBarsSection",
this.$pagesList),this.fire("showPagesList"),this.$body.removeClass("app-projects-list-open").addClass("app-sidebar-open app-pages-list-open"),this.fire("showedPagesList"))},hidePagesList:function(){if(this.$body.hasClass("app-pages-list-open")||this.$body.hasClass("app-page-settings-open"))this.fire("hidePagesList"),this.$body.removeClass("app-pages-list-open app-page-settings-open"),this.fire("hiddenPagesList")},addPage:function(c,n,d,f,g){if(!d){var m=!0,p=this.Core.addPage(c);d=p.name;f=f||p.title;
g&&(a.Core.resultJSON[d].components=g)}if(!d)return!1;f=a.escapeHtml(f);this.fire("addPage",d);p=b(["<li"+(n?' class="main-page"':"")+">",'<a href="javascript:void(0)" class="clearfix">','<span data-tooltipster="bottom"'+(n?"":' title="'+e("Drag Page")+'"')+">"+f+"</span>",'<div class="btn-group">','<button class="btn btn-primary app-page-clone" data-tooltipster="bottom" title="'+e("Clone Page")+'">','<i class="mbr-icon-copy"></i></button>','<button class="btn btn-info app-page-settings" data-tooltipster="bottom" title="'+
e("Page Settings")+'">','<i class="mbr-icon-cog"></i></button>',n?"":'<button class="btn btn-material-red app-page-remove" data-tooltipster="bottom" title="'+e("Remove Page")+'"><i class="mbr-icon-trash"></i></button>','<button class="btn btn-info app-page-ok" data-tooltipster="bottom" title="'+e("OK")+'">','<i class="mbr-icon-check"></i></button></div></a></li>'].join(""));p.find(">a").attr({"data-page":d,"data-title":f});p=this.applyFilter("addPage",p,d);var h=this.$pagesList.find(".list .sortable-container");
m?(c?(m=this.$pagesList.find('.list li > a[data-page="'+c+'"]').parent(),m.hasClass("main-page")?h.prepend(p):m.after(p)):h.prepend(p),l(h)):p.hasClass("main-page")?h.before(p):h.append(p);this.fire("addedPage",d,arguments);return p},switchPage:function(c){var e=b(c).attr("data-page");b(c).attr("data-title");this.fire("switchPage",e);b(c).closest(".list").find("li").children("a").removeClass("active");b(c).addClass("active");this.$body.hasClass("app-page-settings-open")&&b(c).find(".app-page-settings").click();
this.Core.switchPage(e).then(function(){a.fire("switchedPage",e)})},removePage:function(a){var c=b(a).find("> a").attr("data-page");this.fire("removePage",c);if(this.Core.removePage(c)){b(a).find("[data-toggle=tooltip]").tooltip("destroy");if(b(a).find("> a").hasClass("active")){var d=b(a).prev();!d.length&&b(a).is(":first-child")&&(d=this.$pagesList.find(".main-page"));d.children("a").click()}b(a).remove();this.fire("removedPage",c)}},showPageSettings:function(a){this.currentPageSettings=a.attr("data-page");
this.fire("showPageSettings");var c=this.applyFilter("showPageSettings",b.extend(!0,{fileName:this.currentPageSettings},this.Core.getPages()[this.currentPageSettings].settings));this.$pageSettings.find(this.pageSettingsInputs).each(function(){var a=b(this).attr("data-page-settings");b(this).val(c[a]||"")});this.pageNameFullEdit=this.applyFilter("pageNameFullEdit",!1);if(!this.pageNameFullEdit){a=this.$pageSettings.find('[data-page-settings="fileName"]');var d=c.fileName.substr(0,c.fileName.lastIndexOf(".")),
e=c.fileName.substr(c.fileName.lastIndexOf(".")+1);a.parent(".file-name-wrap").length?(a.next().html("."+e),a.val(d)):a.wrap('<div class="file-name-wrap"></div>').after("<span>."+e+"</span>").val(d)}a=this.$pageSettings.find("img.social-sharing-on-mobirise__img");a.length&&b(a).css({height:a[0].width/1.91});this.$body.removeClass("app-projects-list-open").addClass("app-sidebar-open app-page-settings-open");this.fire("showedPageSettings")},changePageSettings:function(a,e,d){this.fire("changePageSettings",
this.currentPageSettings);e=e.toString().trim();this.pageNameFullEdit||"fileName"!==a||(e+=this.$pageSettings.find('[data-page-settings="fileName"]').next().html());var c=this.Core.changePageSettings(this.currentPageSettings,a,e);c?(this.$pagesList.find('[data-page="'+this.currentPageSettings.replace('"','\\"')+'"]').attr("data-page",c),this.currentPageSettings=c):"title"===a&&(a=e,e=this.$pagesList.find('[data-page="'+this.currentPageSettings.replace('"','\\"')+'"]'),e.attr("data-title",a),d&&b(d.target).closest(".list").length?
this.$pageSettings.find('[data-page-settings="title"]').val(a):e.find("span:eq(0)").html(a));this.fire("changedPageSettings",this.currentPageSettings)},sortPagesByOrder:function(a){var b=[];for(c in a)a.hasOwnProperty(c)&&b.push({key:c,value:a[c]});b.sort(function(a,b){return a.value.settings.order-b.value.settings.order});a={};var c=b.length;for(var e=0;e<c;e++)a[b[e].key]=b[e].value;return a},getResultPage:function(c){c=b.extend(!0,{},c);var e=c.components;delete c.components;c=a.Core.cleanJSONPlease(b.extend(!0,
{},c));c.components=e;for(var d=0;d<e.length;d++)a.Core.isSecondaryComponent(c.components[d])&&(c.components[d]=a.Core.transformSecondaryComponentForProject(c.components[d])),c.components[d]=a.Core.cleanJSONPlease(c.components[d]),delete c.components[d]._anchor,delete c.components[d]._cid;return c},getResultJSON:function(){return a.Core.resultJSON},getPagesList:function(b){return a.Core.getPagesList(b)},getCurrentPageName:function(){return a.Core.currentPage}},events:{load:function(){function c(a,
b){d.$pagesList.find(".list .sortable-container").sortable("disable");var c=a.find("span:eq(0)");l=c.html();a.children("a").addClass("editing");c.attr("contenteditable","");b&&"dblclick"===b.type?c.tooltipster("content",e("Edit Title")):c.attr("title",e("Edit Title"));a=document.createRange();b=window.getSelection();a.selectNodeContents(c[0]);b.removeAllRanges();b.addRange(a)}function f(a,c){var m=c.closest("[data-page]");m.removeClass("editing");c.removeAttr("contenteditable");m.closest("li").hasClass("main-page")?
c.tooltipster("content",null):b(a.relatedTarget).hasClass("app-page-new")||b(a.relatedTarget).attr("data-page")?setTimeout(function(){c.tooltipster("content",e("Drag Page"))},300):c.tooltipster("content",e("Drag Page"));d.$pagesList.find(".list .sortable-container").sortable("enable")}var d=this;a.$pagesList.prepend('\n                    <div class="col-xs-12 search-page-wrap">\n                        <input class="search-page-input form-control" type="text" placeholder="'+e("Search")+'" value="">\n                    </div>\n                ');
var g=null;a.$pagesList.find(".search-page-input").on("input",function(c){clearTimeout(g);g=setTimeout(function(){var d=c.target.value.toLowerCase();a.$pagesList.find(".main-page, .sortable-container li").each(function(a,c){a=b(c);a.find("[data-title]").attr("data-title").toLowerCase().includes(d)?a.removeClass("hidden"):a.addClass("hidden")})},100)});d.$pagesListToggle.on("click",function(a){a.preventDefault();a.stopPropagation();d.showPagesList()});d.$pagesList.on("click",function(a){a.stopPropagation()});
d.$pagesList.on("click",".app-layer-close",function(a){d.hidePagesList()});d.on("clickBody",function(){d.hidePagesList()});d.on("sidebarClosed",function(){d.hidePagesList()});d.$pagesList.on("paste","li > .editing > span:first-child",function(a){a.preventDefault();a=((a.originalEvent||a).clipboardData||window.clipboardData).getData("text/plain");b(this).html(a)});var l;d.$pagesList.on("click",".app-page-new",function(b){a.applyFilter("getPagePreset",Promise.resolve()).then(function(a){a=d.addPage(void 0,
void 0,void 0,void 0,a);c(a);a.children("a").click()}).catch(function(){})});d.$pagesList.find(".list").on("click",".app-page-clone",function(){var a=b(this).parents("[data-page]:eq(0)").attr("data-page");a&&(a=d.addPage(a),c(a),a.children("a").click())});d.$pagesList.find(".list").on("click","li > a:not(.active, .app-page-new)",function(a){a.preventDefault();d.switchPage(this)});d.$pagesList.find(".list").on("click",".app-page-remove",function(a){a.preventDefault();a.stopPropagation();var c=b(this).parent().parent().parent()[0];
a=b(this).parents("[data-page]:eq(0)").attr("data-page")||"";d.confirmDlg(e("Remove page $page name$?").replace("$page name$"," <strong>"+a+"</strong>"),function(a){a&&d.removePage(c)})});d.$pagesList.find(".list").on("dblclick","li > a:not(.editing, .app-page-new) > span:first-child",function(a){var d=b(this).closest("li");c(d,a)});d.$pagesList.find(".list").on("blur keydown",".editing [contenteditable]",function(a){var c=b(this);if("focusout"===a.type){var e=c.closest("[data-page]").attr("data-page")||
"",g=c.html();d.currentPageSettings=e;d.changePageSettings("title",g,a);f(a,c)}else 13===a.which?b(this).trigger("blur"):27===a.which&&(c.html(l),f(a,c))});d.$pagesList.find(".list").on("click",".app-page-settings",function(a){a.preventDefault();a.stopPropagation();a=b(this).parent().parent();d.showPageSettings(a)});d.$pageSettings.on("click",function(a){a.stopPropagation()});d.$pageSettings.on("click",".app-layer-close",function(a){d.$body.removeClass("app-page-settings-open")});d.on("clickBody",
function(){d.$body.removeClass("app-page-settings-open")});d.$pageSettings.on("blur keyup paste",d.pageSettingsInputs,function(){d.changePageSettings(b(this).attr("data-page-settings"),b(this).val());a.$pageSettings.find(".chrome-preview-title").text(a.Core.getPages()[a.currentPageSettings].settings.title||"");a.$pageSettings.find(".chrome-preview-description").text(a.Core.getPages()[a.currentPageSettings].settings.meta_descr||"")});a.$pageSettings.on("click",".app-page-settings-chrome-preview-btn",
function(){b(this).addClass("active").siblings().removeClass("active");a.$pageSettings.find(".page-settings-chrome-preview").removeClass("chrome-preview-desktop chrome-preview-mobile").addClass(b(this).hasClass("chrome-preview-desktop-btn")?"chrome-preview-desktop":"chrome-preview-mobile");a.$pageSettings.find(".page-settings-chrome-preview").hasClass("chrome-preview-mobile")?(a.isAMP()?a.$pageSettings.find(".chrome-preview-amp-icon").show():a.$pageSettings.find(".chrome-preview-amp-icon").hide(),
a.$pageSettings.find(".chrome-preview-link").insertBefore(a.$pageSettings.find(".chrome-preview-title"))):(a.$pageSettings.find(".chrome-preview-link").insertAfter(a.$pageSettings.find(".chrome-preview-title")),a.$pageSettings.find(".chrome-preview-amp-icon").hide());k()});h.init();a.$body.find(".navbar-project-info .app-page-name").on("click",function(b){b.preventDefault();b.stopPropagation();a.$pageSettings.find(".page-setting-title-wrap").removeClass("selected");a.openSidebar();setTimeout(function(){a.$pageSettings.find(".app-layer-cont").scrollTop(0);
a.$pagesList.find(".list li > a.active .app-page-settings").click();a.$pageSettings.find(".page-setting-title-wrap").addClass("selected")},300)});a.$body.find(".navbar-project-info .app-page-url").on("click",function(b){b.preventDefault();b.stopPropagation();a.$pageSettings.find(".page-setting-url-wrap").removeClass("selected");a.openSidebar();setTimeout(function(){a.$pageSettings.find(".app-layer-cont").scrollTop(0);a.$pagesList.find(".list li > a.active .app-page-settings").click();a.$pageSettings.find(".page-setting-url-wrap").addClass("selected")},
300)})},loadedProject:function(){var a,b=this.$pagesList.find(".list");b.html('<li><a href="javascript:void(0)" class="app-page-new"><span><i class="mbr-icon-plus"></i> '+e("Create New Page")+'</span></a></li><div class="sortable-container"></div>');var d=this.Core.getPages();for(g in d)if(d[g].settings.main){d[g].settings.order=0;break}d=this.sortPagesByOrder(d);for(var f in d){var g=d[f].settings.main;var h=this.addPage(null,g,f,d[f].settings.title);g&&h.children("a").click()}var k=b.find(".sortable-container");
k.sortable({axis:"y",containment:"parent",tolerance:"pointer",start:function(b,c){a=c.item.index()},stop:function(b,c){c.item.css("left","");c.item.index()!==a&&l(k)}})},showSideBarsSection:function(){this.hidePagesList()},showedPageSettings:function(){var b=a.projectSettings.favicon||a.findMenuLogo()||("secondary"===a.theme.type?"app/builder/images/logo5.png":"app/builder/images/logo.png");0===b.indexOf("../../")&&(b=b.replace("../../",""));k();a.Core.getPages()[a.currentPageSettings].settings.main?
a.$pageSettings.find(".page-settings-url-info").show():a.$pageSettings.find(".page-settings-url-info").hide();a.$pageSettings.find(".chrome-preview-favicon").attr("src",b);a.$pageSettings.find(".chrome-preview-title").text(a.Core.getPages()[a.currentPageSettings].settings.title||"");a.$pageSettings.find(".chrome-preview-description").text(a.Core.getPages()[a.currentPageSettings].settings.meta_descr||"");q&&(a.$pageSettings.find(".chrome-preview-mobile-btn").click(),q=!1)},changedPageSettings:function(){k();
a.$pageSettings.find(".chrome-preview-title").text(a.Core.getPages()[a.currentPageSettings].settings.title||"");f()},switchedPage:function(b){b=a.Core.getPages()[b].settings.meta_image||"";var c=a.$pageSettings.find(".social-sharing-on-mobirise"),d=a.$pageSettings.find("#metaShareImage");c.hide();b?(c.find("img").attr("src",b),c.show(),d.is(":checked")||d.trigger("click")):d.is(":checked")&&d.trigger("click");f()}}})},["jQuery","mbrApp","TR()","Bridge"]);
