defineM("app-migrate",function(g,b){b.regExtension({name:"migrate",global:{setArray:function(a,b){console.warn("mbrApp.setArray is depricated use Bridge.setSettingsArray instead");Bridge.setSettingsArray(a,b)},getArray:function(a,b){console.warn("mbrApp.getArray is depricated use Bridge.getSettingsArray instead");Bridge.getSettingsArray(a,b)},dirList:function(a,b,d){Bridge.dirList(a,b,d)},transformImage:function(a,b,d){Bridge.transformImage(a,b,d)},getComponent:function(a){return b.Core.getComponent(a)},
getCoreTemplate:function(){return b.Core.$template},removeComponent:function(a,c,d){return b.Core.removeComponent(a,c,d)},getUniqCompName:function(){return b.Core.getUniqCompName()},getCoreUniqNum:function(){return b.Core.uniqNum()},registeredFonts:[{name:"Open Sans",url:"https://fonts.googleapis.com/css?family=Open+Sans:400,300,700",css:"'Open Sans', sans-serif"},{name:"Roboto",url:"https://fonts.googleapis.com/css?family=Roboto:400,300,700",css:"'Roboto', sans-serif"},{name:"Lato",url:"https://fonts.googleapis.com/css?family=Lato:400,300,700",
css:"'Lato', sans-serif"},{name:"Oswald",url:"https://fonts.googleapis.com/css?family=Oswald:400,300,700",css:"'Oswald', sans-serif"},{name:"Roboto Condensed",url:"https://fonts.googleapis.com/css?family=Roboto+Condensed:400,300,700",css:"'Roboto Condensed', sans-serif"},{name:"Slabo 27px",url:"https://fonts.googleapis.com/css?family=Slabo+27px",css:"'Slabo 27px', serif"},{name:"Lora",url:"https://fonts.googleapis.com/css?family=Lora:400,700",css:"'Lora', serif"},{name:"Source Sans Pro",url:"https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300,700",
css:"'Source Sans Pro', sans-serif"},{name:"PT Sans",url:"https://fonts.googleapis.com/css?family=PT+Sans:400,700",css:"'PT Sans', sans-serif"},{name:"Open Sans Condensed",url:"https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700",css:"'Open Sans Condensed', sans-serif"},{name:"Raleway",url:"https://fonts.googleapis.com/css?family=Raleway:400,300,700",css:"'Raleway', sans-serif"},{name:"Droid Sans",url:"https://fonts.googleapis.com/css?family=Droid+Sans:400,700",css:"'Droid Sans', sans-serif"},
{name:"Montserrat",url:"https://fonts.googleapis.com/css?family=Montserrat:400,700",css:"'Montserrat', sans-serif"},{name:"Ubuntu",url:"https://fonts.googleapis.com/css?family=Ubuntu:400,300,700",css:"'Ubuntu', sans-serif"},{name:"Droid Serif",url:"https://fonts.googleapis.com/css?family=Droid+Serif:400,700",css:"'Droid Serif', serif"},{name:"Roboto Slab",url:"https://fonts.googleapis.com/css?family=Roboto+Slab:400,300,700",css:"'Roboto Slab', serif"},{name:"Merriweather",url:"https://fonts.googleapis.com/css?family=Merriweather:400,300,700",
css:"'Merriweather', serif"},{name:"PT Sans Narrow",url:"https://fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700",css:"'PT Sans Narrow', sans-serif"},{name:"Arimo",url:"https://fonts.googleapis.com/css?family=Arimo:400,700",css:"'Arimo', sans-serif"},{name:"Noto Sans",url:"https://fonts.googleapis.com/css?family=Noto+Sans:400,700",css:"'Noto Sans', sans-serif"},{name:"Bitter",url:"https://fonts.googleapis.com/css?family=Bitter:400,700",css:"'Bitter', serif"},{name:"Titillium Web",url:"https://fonts.googleapis.com/css?family=Titillium+Web:400,300,700",
css:"'Titillium Web', sans-serif"},{name:"Indie Flower",url:"https://fonts.googleapis.com/css?family=Indie+Flower",css:"'Indie Flower', cursive"},{name:"PT Serif",url:"https://fonts.googleapis.com/css?family=PT+Serif:400,400i,700,700i",css:"'PT Serif', serif"},{name:"Yanone Kaffeesatz",url:"https://fonts.googleapis.com/css?family=Yanone+Kaffeesatz:400,300,700",css:"'Yanone Kaffeesatz', sans-serif"},{name:"Oxygen",url:"https://fonts.googleapis.com/css?family=Oxygen:400,300,700",css:"'Oxygen', sans-serif"}]},
events:{load:function(){b.addFilter("loadingProject",function(a,b){a.settings&&0<Bridge.versionCmp("3.9.2",a.settings.versionPublish||a.settings.versionFirst||Bridge.version)&&(console.log("fix 3.8.xxx project"),a=JSON.parse(JSON.stringify(a,function(a,e){"string"==typeof e&&0==e.indexOf("assets/images/")&&(e=b+"/"+e);return e})));a.settings&&(a.settings["canonical-url"]=a.settings["canonical-url"]||a.settings["\u0441anonical-url"]);return a});b.addFilter("loadProjectCore",function(a,c,d){return a.then(function(){var a=
g.Deferred();b.projectSettings.siteFonts?a.resolve():Bridge.loadLocalFile(b.projectPath+"/fonts/fonts.json",function(d){var c;try{d&&(c=JSON.parse(d))}catch(h){}c&&(b.projectSettings.siteFonts=c);a.resolve()});return a})});b.addFilter("getThemeFonts",function(a){if("secondary"!==b.theme.type)for(var c=b.registeredFonts,d=0;d<c.length;d++){for(var e=0,f=0;f<a.length;f++)if(a[f].name===c[d].name){e++;break}e||a.push(c[d])}return a});b.Core.on("savedMediaIconFontDialog",function(a,c,d){b.fire("savedMediaIconFontDialog",
a,c,d)});b.Core.on("updateGlobalComponents",function(a,c){b.fire("updateGlobalComponents",a,c)});b.Core.addFilter("getComponentsAnchorList",function(a){return b.applyFilter("getComponentsAnchorList",a)});b.addFilter("registerPlugin",function(a){function c(a){return b.theme.name===a}if("secondary"===b.theme.type||"Bootstrap"!==a.name||!"default unicore sleek colorm spacem directm clarus purity mobirise3".split(" ").some(c))return a;g(a.files).each(function(b,e){/bootstrap.min.js/.test(e)&&(a.files[b]=
["default","unicore","sleek"].some(c)?"web/assets/bootstrap3-migrate/bootstrap.min.js":"web/assets/bootstrap4-migrate/bootstrap.min.js",a.root="")});return a})},loaded:function(){b.addFilter("additionalSiteSettings",function(a){return b.applyFilter("additionalPageSettings",a)})},themeLoaded:function(){"secondary"!==b.theme.type&&b.addCoreResource("web/assets/fonts/fonts.css");this.fire("loadThemeOnStart")}}})},["jQuery","mbrApp"]);
