var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(c,d,k){c instanceof String&&(c=String(c));for(var l=c.length,f=0;f<l;f++){var a=c[f];if(d.call(k,a,f,c))return{i:f,v:a}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(c,d,k){c!=Array.prototype&&c!=Object.prototype&&(c[d]=k.value)};$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global&&null!=global?global:c};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(c,d,k,l){if(d){k=$jscomp.global;c=c.split(".");for(l=0;l<c.length-1;l++){var f=c[l];f in k||(k[f]={});k=k[f]}c=c[c.length-1];l=k[c];d=d(l);d!=l&&null!=d&&$jscomp.defineProperty(k,c,{configurable:!0,writable:!0,value:d})}};$jscomp.polyfill("Array.prototype.find",function(c){return c?c:function(c,k){return $jscomp.findInternal(this,c,k).v}},"es6","es3");$jscomp.arrayIteratorImpl=function(c){var d=0;return function(){return d<c.length?{done:!1,value:c[d++]}:{done:!0}}};
$jscomp.arrayIterator=function(c){return{next:$jscomp.arrayIteratorImpl(c)}};$jscomp.makeIterator=function(c){var d="undefined"!=typeof Symbol&&Symbol.iterator&&c[Symbol.iterator];return d?d.call(c):$jscomp.arrayIterator(c)};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(c){function d(){this.batch_=null}function k(a){return a instanceof f?a:new f(function(b,h){b(a)})}if(c&&!$jscomp.FORCE_POLYFILL_PROMISE)return c;d.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})}this.batch_.push(a)};var l=$jscomp.global.setTimeout;d.prototype.asyncExecuteFunction=function(a){l(a,0)};d.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var e=0;e<a.length;++e){var h=a[e];a[e]=null;try{h()}catch(m){this.asyncThrow_(m)}}}this.batch_=null};d.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var f=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(h){b.reject(h)}};f.prototype.createResolveAndReject_=function(){function a(a){return function(b){h||(h=!0,a.call(e,b))}}var e=this,h=!1;
return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};f.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof f)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};f.prototype.resolveToNonPromiseObj_=function(a){var b=void 0;try{b=a.then}catch(h){this.reject_(h);return}"function"==typeof b?
this.settleSameAsThenable_(b,a):this.fulfill_(a)};f.prototype.reject_=function(a){this.settle_(2,a)};f.prototype.fulfill_=function(a){this.settle_(1,a)};f.prototype.settle_=function(a,e){if(0!=this.state_)throw Error("Cannot settle("+a+", "+e+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=e;this.executeOnSettledCallbacks_()};f.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var b=0;b<this.onSettledCallbacks_.length;++b)a.asyncExecute(this.onSettledCallbacks_[b]);
this.onSettledCallbacks_=null}};var a=new d;f.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};f.prototype.settleSameAsThenable_=function(a,e){var b=this.createResolveAndReject_();try{a.call(e,b.resolve,b.reject)}catch(m){b.reject(m)}};f.prototype.then=function(a,e){function b(a,b){return"function"==typeof a?function(b){try{c(a(b))}catch(p){g(p)}}:b}var c,g,d=new f(function(a,b){c=a;g=b});this.callWhenSettled_(b(a,c),b(e,g));return d};
f.prototype.catch=function(a){return this.then(void 0,a)};f.prototype.callWhenSettled_=function(b,e){function c(){switch(d.state_){case 1:b(d.result_);break;case 2:e(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?a.asyncExecute(c):this.onSettledCallbacks_.push(c)};f.resolve=k;f.reject=function(a){return new f(function(b,c){c(a)})};f.race=function(a){return new f(function(b,c){for(var e=$jscomp.makeIterator(a),h=e.next();!h.done;h=e.next())k(h.value).callWhenSettled_(b,
c)})};f.all=function(a){var b=$jscomp.makeIterator(a),c=b.next();return c.done?k([]):new f(function(a,e){function h(b){return function(c){g[b]=c;d--;0==d&&a(g)}}var g=[],d=0;do g.push(void 0),d++,k(c.value).callWhenSettled_(h(g.length-1),e),c=b.next();while(!c.done)})};return f},"es6","es3");
defineM("app-common",function(c,d,k,l,f){d.regExtension({name:"common",global:{redirectLinks:function(a,b){var e=this;c("a[href^=http]",a).each(function(){c(this).data("link",c(this).attr("href"))}).attr("href","javascript:void(0)").click(function(a){a.stopPropagation();d.openUrl(c(this).data("link"))});c("iframe",a).each(function(){e.redirectLinks(this.contentWindow.document.documentElement,b)})},openUrl:function(a){a=d.applyFilter("openUrl",a);(a=l.substUrl(a))&&l.openUrl(a)},criticalError:function(a,
b){var c="<i>"+k("This is a critical error, some functions of the program may not work correctly, please send information to the developers.")+"</i>",h=this;if(b){if(0<=h._criticalErrorShown.indexOf(b)||0<=h._criticalErrorShowed.indexOf(a))return;h._criticalErrorShown.push(b);h._criticalErrorShowed.push(a)}bootbox.dialog({title:k("Critical error"),message:(a||"")+"<br/>"+c,buttons:{cancel:{label:k("Cancel"),className:"btn-default",callback:function(){}},success:{label:k("Send Error Report"),className:"btn-primary",
callback:function(){}}}}).on("hidden.bs.modal",function(){h._criticalErrorShowed.slice(h._criticalErrorShowed.indexOf(a),1)})},_criticalErrorShown:[],_criticalErrorShowed:[],showDialog:function(a){var b=!1;this.$body.find(".bootbox.modal").length&&this.$body.find(".bootbox.modal").each(function(e,h){c(h).find(".modal-title").length&&c(h).find(".modal-title").html()===a.title?b=!0:c(h).find(".modal-body").length&&c(h).find(".modal-body").html()===a.body&&(b=!0)});if(!b){var e=this;a=a||{};var h={};
a.cancel&&(h.cancel={label:a.cancelLabel||k("Cancel"),className:"btn-default",callback:function(){a.cancel.call(g,g)}});a.success&&(h.success={label:a.successLabel||k("Ok"),className:"btn-primary",callback:function(){a.success.call(g,g)}});if(a.buttons)for(var m in a.buttons)(function(a){h[m]={label:a.label||"",className:(a.className||"")+" "+(/btn-primary|btn-default/.test(a.className)?"":a.default?"btn-primary":"btn-default"),callback:function(){if(a.callback)return a.callback()}}})(a.buttons[m]);
var g=bootbox.dialog({size:a.size,title:a.title,className:a.className+(a.flex?" mbr-flex":""),message:a.body||"\x3c!-- Empty body --\x3e",buttons:h,onEscape:a.oncancel||function(){},show:!1});a.id&&g.attr("id",a.id);for(var f in a.buttons)g.find("[data-bb-handler="+f+"]").attr("name",f);a.create&&a.create.call(g,g);g.find("select").dropdown({absolutePos:!0,align:"right"});g.find("input.mbr-color").each(function(){var a=c(this),b=function(a,b){b=b.map(function(a){return a.toUpperCase()});if(-1==b.indexOf(a.toUpperCase()))return!0};
a.spectrum("destroy").spectrum({showButtons:!1,preferredFormat:"hex",allowEmpty:!0,showInput:!0,showPaletteOnly:!0,togglePaletteOnly:!0,togglePaletteMoreText:k("More")+" >",togglePaletteLessText:k("Less")+" <",replacerClassName:a.hasClass("pull-right")?"pull-right":"",appendTo:"#innerFontDialog",maxSelectionSize:1,palette:d.getThemeColorsSet(7),move:function(b){a.val(b&&b.toHexString());a.trigger("change")},hide:function(a){if(a){var c;(c=d.projectSettings.theme.additionalSetColors)?b(a.toHexString(),
c)&&b(a.toHexString(),d.getThemeColorsSet(7)[0])&&(7>c.length?c.push(a.toHexString()):(c.unshift(a.toHexString()),c.pop())):b(a.toHexString(),d.getThemeColorsSet(7)[0])?d.projectSettings.theme.additionalSetColors=[a.toHexString()]:d.projectSettings.theme.additionalSetColors=[]}}})});a.show&&a.show.call(g,g);g.on("shown.bs.modal",function(){e.fire("modalDialogShow",g,a)});c(g).on("hide.bs.modal",function(){g.find("select").each(function(){c(c(this).data("dropdownjs-ul")).remove()});g.find("input.mbr-color").spectrum("hide");
e.fire("modalDialogHide",g)});g.on("hidden.bs.modal",function(){d.$body.find(".modal:visible").length&&d.$body.addClass("modal-open");g.find("input.mbr-color").spectrum("destroy");a.onhide&&(a.onhide.call(g,g),console.log("Warning: Using showDialog.onhide is depracated, use showDialog.hide instead"));a.hide&&a.hide.call(g,g);e.fire("modalDialogHidden",g)});g.modal("show");return g}},showError:function(a,b){"object"!=typeof a&&(a={message:a||"Unknown error"});a.callback=a.callback||b;bootbox.alert(a)},
confirmDlg:function(a,b){"object"!==typeof a?a={body:a,cancel:function(){b(!1)},success:function(){b(!0)},oncancel:function(){b(!1)}}:(a.body=a.message,a.buttons?(a.buttons.cancel.callback=function(){a.callback(!1)},a.buttons.confirm.callback=function(){a.callback(!0)},a.buttons.confirm.default=!0):(a.cancel=function(){a.callback(!1)},a.success=function(){a.callback(!0)},a.oncancel=function(){a.callback(!1)}),a.oncancel=function(){a.callback(!1)});return d.showDialog(a)},alertDlg:function(a){return d.showDialog({body:a,
success:function(){}})},Accordion:function(a,b,e){e=c.extend({autoCollapse:!0},e);a=c(a);b=c(b);a.click(function(){var c=b.eq(a.index(this));e.autoCollapse&&b.not(c).slideUp();c.slideToggle()});e.autoCollapse?(b.hide(),c(e.start_panel||b.get(0)).show()):b.show();return{collapse:function(a){c(a||b).hide()},expand:function(a){c(a||b).show()},open:function(a){b.hide();c(a).show()},close:function(a){c(a).hide()}}},initPopoverRange:function(a){var b=this;c(a).popover({trigger:"click,focus",content:function(){return b.renderRangeSlider(a)},
html:!0,placement:"top"})},renderRangeSlider:function(a){var b=c(a),e=c('<div class="slider" style="width:150px" />').get(0),h=parseFloat(b.attr("data-min"))||0,d=parseFloat(b.attr("data-max"))||10;a=parseFloat(b.attr("data-step"))||1;noUiSlider.create(e,{start:parseFloat(b.val())||h,step:a,range:{min:h,max:d}});var g=c("<span></span>").appendTo(c(e).find(".noUi-handle")),f=0;e.noUiSlider.on("update",function(a,m){f?(a=parseFloat(a[m]),c(e).removeClass("noUi-first noUi-last"),a==h?c(e).addClass("noUi-first"):
a==d&&c(e).addClass("noUi-last"),g.html("<span>"+a+"</span>"),b.val(a).trigger("change")):f=1});return e},runIframe:function(a,b,c){c=c||{};c.base=c.base||window.location.href;var e="";e='<html><head><base href="'+(c.base+'"/>');if(c.links)for(var f=0;f<c.links.length;f++)e+='<link rel="stylesheet" href="'+c.links[f]+'"/>';e+="</head><body"+(d.appSettings&&(!0===d.appSettings.darkMode?' class="dark-mode"':""))+">";e=e+(b||"")+"</body></html>";a.style.visibility="hidden";c.noScroll&&(a.setAttribute("scrolling",
"no"),a.style.overflow="hidden");a.onload=function(){a.onload="";this.style.visibility="visible";if(c.onload)c.onload(a.contentWindow.document.documentElement)};a.contentWindow.document.open();a.contentWindow.document.write(e);a.contentWindow.document.close();return a},addAppResource:function(a,b){if(a){void 0===b&&(b=/\.js$/.test(a.split("?")[0]));if(b)return this.addAppScript(a);this.addAppStyle(a);return c.Deferred().resolve()}},addCoreResource:function(a,b){if(a){void 0===b&&(b=/\.js$/.test(a.split("?")[0]));
var e=d.Core.$body.data("files")||[];if(0<=e.indexOf(a))return c.Deferred().resolve();e.push(a);d.Core.$body.data("files",e);if(b)return this.addCoreScript(a);a=d.path2core(a);d.Core.$document.find("#insertBefore").before('<link rel="stylesheet" href="'+a+'"/>');return c.Deferred().resolve()}},addAppScript:function(a){var b=c.Deferred();this.appendScriptAsync(l.path2app(a),d.$window.get(0),function(a){return b.resolve()});return b.promise()},addAppStyle:function(a){d.$body.find("#insertBefore").before('<link rel="stylesheet" href="'+
l.path2app(a)+'">')},addCoreScript:function(a){var b=c.Deferred();this.appendScriptAsync(d.path2core(a),d.iwindow,function(a){return b.resolve()});return b.promise()},appendScriptAsync:function(a,b,c){var e=document.createElement("script");e.addEventListener("load",c);e.addEventListener("error",function(b){console.warn("Error while script loading "+a,b);c&&c()});e.src=a;(b||window).document.head.appendChild(e)},checkScriptSyntaxError:function(a,b){var c,d=document.createElement("iframe");d.style.visibility=
"hidden";window.document.body.appendChild(d);d.myerrors=function(a,b,e){a&&!a.indexOf("SyntaxError:")&&(c=Error(a),c.fileName=b,c.lineNumber=e);return!0};d.onload=function(){window.document.body.removeChild(d);b&&b(c)};d.contentWindow.document.open();try{d.contentWindow.document.write('<html><head><script> window.onerror = window.frameElement.myerrors \x3c/script><script src="'+a+'">\x3c/script></head><body></body></html>'),d.contentWindow.document.close()}catch(m){}},evalScript:function(a,b){function c(a,
b){l.loadLocalFile(a,function(c){if(c){var e={},f;for(f in d)e[f]=g[f],g[f]=d[f];try{g.eval(c)}catch(n){console.error(n.message,a,n.stack);var h=n}for(f in e)g[f]=e[f];b(h)}else console.error("Empty script",a),b(Error("Empty script",a))})}b=b||{};var d=b.globals||{},f=!!b.noCheckErrors,g=b.context||window,k=b.callback_error||function(){};if(!g.eval||!g.location)if(g=g.ownerDocument||g,g=g.defaultView||g,!g.eval||!g.location){f=Error("Wrong context of evalScript",g);console.error(f);k(f);return}/^[\w]*:/.test(a)||
(b=g.location.href,a=b.substring(0,b.lastIndexOf("/")+1)+a);f?setTimeout(function(){c(a,k)},1):this.checkScriptSyntaxError(a,function(b){b?(console.error("Script error:",b,a),k(b)):setTimeout(function(){c(a,k)},1)})},spinText:function(a){for(;/\{[^{}]*\}/.exec(a);)a=a.replace(/\{([^{}]*)\}(\s?)/g,function(a,c,d){a=c.split("|");(c=a[Math.floor(Math.random()*(a.length-0))+0])&&(c+=d);return c});return a.replace(/\s$/,"")},escapeHtml:function(a){var b={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;",
"'":"&#39;","/":"&#x2F;"};return String(a).replace(/[&<>"'\/]/g,function(a){return b[a]})},http:function(a,b){return l.http(a,b)},encrypt:function(){function a(){var a=Array.prototype.slice.call(arguments),b=a.reduce(function(a,b){if(!(b instanceof ArrayBuffer||ArrayBuffer.isView(b)))throw new TypeError("Every argument must be an ArrayBuffer of ArrayBuffer view");return a+b.byteLength},0);return a.reduceRight(function(a,c){b-=c.byteLength;a.set(ArrayBuffer.isView(c)?new Uint8Array(c.buffer,c.byteOffset,
c.length*c.BYTES_PER_ELEMENT):new Uint8Array(c),b);return a},new Uint8Array(b)).buffer}var b=window.crypto,c=b&&(b.subtle||b.webkitSubtle),d=function(a){return(new TextEncoder).encode(a)};return function(e,f){if(!c)return Promise.reject(Error("Crypto.subtle is not implemented"));if("string"!==typeof e)return Promise.reject(new TypeError('"content" must be a string'));if("string"!==typeof f)return Promise.reject(new TypeError('"password" must be a string'));var g=b.getRandomValues(new Uint8Array(16)),
h=b.getRandomValues(new Uint8Array(32));return c.importKey("raw",d(f),"PBKDF2",!1,["deriveKey"]).then(function(a){return c.deriveKey({name:"PBKDF2",salt:h,iterations:5E5,hash:"SHA-256"},a,{name:"AES-GCM",length:256},!1,["encrypt"])}).then(function(a){return c.encrypt({name:"AES-GCM",iv:g},a,d(e))}).then(function(b){var c=h.length,d=g.length,e=new DataView(new ArrayBuffer(6));e.setUint8(0,c);e.setUint8(1,d);e.setUint32(2,5E5);return a(e.buffer,h,g,b)}).then(function(a){var b="";a=new Uint8Array(a);
for(var c=a.byteLength,d=0;d<c;d++)b+=String.fromCharCode(a[d]);return window.btoa(b)})}}(),reloadTranslator:function(a){"MobiriseTranslator"===a.name&&l.reload()},resizeWindow:function(){d.$window.resize()},runFileDialog:function(a){a.path&&(a.path=l.docLocation+"/"+a.path);return $Bridge.runFileDialog2(a)},showPreloader:function(a){if(d.$body.find(".preloader").length)d.$body.find(".preloader").css({opacity:".8",transition:"0.2s"}),a&&a();else{var b=c(d.preloaderHTML);d.$body.append(b);b.css({opacity:".8",
transition:"0.2s"});b.one("transitionend",function(){a&&a()})}},hidePreloader:function(a){var b=d.$body.find(".preloader");b.one("transitionend",function(){b.remove();a&&a()});b.css("opacity",0)},openImage:function(a,b,c,d,f,g,k){l.openImage(a,b,c,d,f,g,k)},mbrServerGet:function(a){return f.get("storage/"+a)},stopIfRepeatDecorator:function(a,b){var c=null;return function(){var d=arguments,e=this;clearTimeout(c);c=setTimeout(function(){a.apply(e,d)},b)}}},events:{beforeAppLoad:function(){c(document).on("show.bs.modal",
function(a){c(a.target).find(".close").addClass("mbr-icon-times").empty()})},translateLoaded:function(){c(".preloader .logo").last().html(k("LOADING..."))}}})},["jQuery","mbrApp","TR()","Bridge","mbrServer"]);
