var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(b,c,f){b instanceof String&&(b=String(b));for(var g=b.length,k=0;k<g;k++){var e=b[k];if(c.call(f,e,k,b))return{i:k,v:e}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,c,f){b!=Array.prototype&&b!=Object.prototype&&(b[c]=f.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(b,c,f,g){if(c){f=$jscomp.global;b=b.split(".");for(g=0;g<b.length-1;g++){var k=b[g];k in f||(f[k]={});f=f[k]}b=b[b.length-1];g=f[b];c=c(g);c!=g&&null!=c&&$jscomp.defineProperty(f,b,{configurable:!0,writable:!0,value:c})}};$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(c,b){return $jscomp.findInternal(this,c,b).v}},"es6","es3");
$jscomp.polyfill("Array.from",function(b){return b?b:function(c,b,g){b=null!=b?b:function(b){return b};var f=[],e="undefined"!=typeof Symbol&&Symbol.iterator&&c[Symbol.iterator];if("function"==typeof e){c=e.call(c);for(var d=0;!(e=c.next()).done;)f.push(b.call(g,e.value,d++))}else for(e=c.length,d=0;d<e;d++)f.push(b.call(g,c[d],d));return f}},"es6","es3");
$jscomp.checkEs6ConformanceViaProxy=function(){try{var b={},c=Object.create(new $jscomp.global.Proxy(b,{get:function(f,g,k){return f==b&&"q"==g&&k==c}}));return!0===c.q}catch(f){return!1}};$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS=!1;$jscomp.ES6_CONFORMANCE=$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS&&$jscomp.checkEs6ConformanceViaProxy();$jscomp.arrayIteratorImpl=function(b){var c=0;return function(){return c<b.length?{done:!1,value:b[c++]}:{done:!0}}};$jscomp.arrayIterator=function(b){return{next:$jscomp.arrayIteratorImpl(b)}};
$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.SymbolClass=function(b,c){this.$jscomp$symbol$id_=b;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:c})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};
$jscomp.Symbol=function(){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(f||"")+"_"+c++,f)}var c=0;return b}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.iterator;b||(b=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[b]&&$jscomp.defineProperty(Array.prototype,b,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.asyncIterator;b||(b=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(b){$jscomp.initSymbolIterator();b={next:b};b[$jscomp.global.Symbol.iterator]=function(){return this};return b};
$jscomp.makeIterator=function(b){var c="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];return c?c.call(b):$jscomp.arrayIterator(b)};$jscomp.owns=function(b,c){return Object.prototype.hasOwnProperty.call(b,c)};
$jscomp.polyfill("WeakMap",function(b){function c(){if(!b||!Object.seal)return!1;try{var a=Object.seal({}),c=Object.seal({}),d=new b([[a,2],[c,3]]);if(2!=d.get(a)||3!=d.get(c))return!1;d.delete(a);d.set(c,4);return!d.has(a)&&4==d.get(c)}catch(n){return!1}}function f(){}function g(a){var h=typeof a;return"object"===h&&null!==a||"function"===h}function k(a){if(!$jscomp.owns(a,d)){var h=new f;$jscomp.defineProperty(a,d,{value:h})}}function e(a){var h=Object[a];h&&(Object[a]=function(a){if(a instanceof
f)return a;k(a);return h(a)})}if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(b&&$jscomp.ES6_CONFORMANCE)return b}else if(c())return b;var d="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var l=0,a=function(a){this.id_=(l+=Math.random()+1).toString();if(a){a=$jscomp.makeIterator(a);for(var h;!(h=a.next()).done;)h=h.value,this.set(h[0],h[1])}};a.prototype.set=function(a,b){if(!g(a))throw Error("Invalid WeakMap key");k(a);if(!$jscomp.owns(a,d))throw Error("WeakMap key fail: "+
a);a[d][this.id_]=b;return this};a.prototype.get=function(a){return g(a)&&$jscomp.owns(a,d)?a[d][this.id_]:void 0};a.prototype.has=function(a){return g(a)&&$jscomp.owns(a,d)&&$jscomp.owns(a[d],this.id_)};a.prototype.delete=function(a){return g(a)&&$jscomp.owns(a,d)&&$jscomp.owns(a[d],this.id_)?delete a[d][this.id_]:!1};return a},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(b){function c(){if($jscomp.ASSUME_NO_NATIVE_MAP||!b||"function"!=typeof b||!b.prototype.entries||"function"!=typeof Object.seal)return!1;try{var a=Object.seal({x:4}),c=new b($jscomp.makeIterator([[a,"s"]]));if("s"!=c.get(a)||1!=c.size||c.get({x:4})||c.set({x:4},"t")!=c||2!=c.size)return!1;var d=c.entries(),e=d.next();if(e.done||e.value[0]!=a||"s"!=e.value[1])return!1;e=d.next();return e.done||4!=e.value[0].x||"t"!=e.value[1]||!d.next().done?!1:!0}catch(n){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(b&&$jscomp.ES6_CONFORMANCE)return b}else if(c())return b;$jscomp.initSymbolIterator();var f=new WeakMap,g=function(a){this.data_={};this.head_=d();this.size=0;if(a){a=$jscomp.makeIterator(a);for(var c;!(c=a.next()).done;)c=c.value,this.set(c[0],c[1])}};g.prototype.set=function(a,c){a=0===a?0:a;var b=k(this,a);b.list||(b.list=this.data_[b.id]=[]);b.entry?b.entry.value=c:(b.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:a,
value:c},b.list.push(b.entry),this.head_.previous.next=b.entry,this.head_.previous=b.entry,this.size++);return this};g.prototype.delete=function(a){a=k(this,a);return a.entry&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.data_[a.id],a.entry.previous.next=a.entry.next,a.entry.next.previous=a.entry.previous,a.entry.head=null,this.size--,!0):!1};g.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=d();this.size=0};g.prototype.has=function(a){return!!k(this,a).entry};
g.prototype.get=function(a){return(a=k(this,a).entry)&&a.value};g.prototype.entries=function(){return e(this,function(a){return[a.key,a.value]})};g.prototype.keys=function(){return e(this,function(a){return a.key})};g.prototype.values=function(){return e(this,function(a){return a.value})};g.prototype.forEach=function(a,c){for(var b=this.entries(),d;!(d=b.next()).done;)d=d.value,a.call(c,d[1],d[0],this)};g.prototype[Symbol.iterator]=g.prototype.entries;var k=function(a,c){var b=c&&typeof c;"object"==
b||"function"==b?f.has(c)?b=f.get(c):(b=""+ ++l,f.set(c,b)):b="p_"+c;var d=a.data_[b];if(d&&$jscomp.owns(a.data_,b))for(a=0;a<d.length;a++){var e=d[a];if(c!==c&&e.key!==e.key||c===e.key)return{id:b,list:d,index:a,entry:e}}return{id:b,list:d,index:-1,entry:void 0}},e=function(a,c){var b=a.head_;return $jscomp.iteratorPrototype(function(){if(b){for(;b.head!=a.head_;)b=b.previous;for(;b.next!=b.head;)return b=b.next,{done:!1,value:c(b)};b=null}return{done:!0,value:void 0}})},d=function(){var a={};return a.previous=
a.next=a.head=a},l=0;return g},"es6","es3");
$jscomp.polyfill("Set",function(b){function c(){if($jscomp.ASSUME_NO_NATIVE_SET||!b||"function"!=typeof b||!b.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),f=new b($jscomp.makeIterator([c]));if(!f.has(c)||1!=f.size||f.add(c)!=f||1!=f.size||f.add({x:4})!=f||2!=f.size)return!1;var e=f.entries(),d=e.next();if(d.done||d.value[0]!=c||d.value[1]!=c)return!1;d=e.next();return d.done||d.value[0]==c||4!=d.value[0].x||d.value[1]!=d.value[0]?!1:e.next().done}catch(l){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(b&&$jscomp.ES6_CONFORMANCE)return b}else if(c())return b;$jscomp.initSymbolIterator();var f=function(b){this.map_=new Map;if(b){b=$jscomp.makeIterator(b);for(var c;!(c=b.next()).done;)this.add(c.value)}this.size=this.map_.size};f.prototype.add=function(b){b=0===b?0:b;this.map_.set(b,b);this.size=this.map_.size;return this};f.prototype.delete=function(b){b=this.map_.delete(b);this.size=this.map_.size;return b};f.prototype.clear=function(){this.map_.clear();
this.size=0};f.prototype.has=function(b){return this.map_.has(b)};f.prototype.entries=function(){return this.map_.entries()};f.prototype.values=function(){return this.map_.values()};f.prototype.keys=f.prototype.values;f.prototype[Symbol.iterator]=f.prototype.values;f.prototype.forEach=function(b,c){var e=this;this.map_.forEach(function(d){return b.call(c,d,d,e)})};return f},"es6","es3");
defineM("app-fonts",function(b,c,f){function g(e,d){this.API_KEY=e;this.settingName=d;this.gFonts={};this.$iframeLocal=this.$iframeGoogle="";this.loadQuantity=20;this._blockScroll=!1;this._lastIndex=0;this.$loader=b(c.preloaderHTML);this.fontsPath=c.projectPath+"/fonts";this.requestUrl="https://www.googleapis.com/webfonts/v1/webfonts?sort=popularity&key="+this.API_KEY;this.init=function(){function d(b,d){c.runIframe(a.$modalFonts.find("#"+b).get(0),'<ul class="gf-list">\n</ul>',{onload:d,links:["assets/bootstrap/bootstrap.min.css",
"assets/bootstrap-material/css/material.min.css","app/builder/css/app-builder-icons.css","app/interface/style.css","assets/fonts/fonts.css"]})}var a=this;a.$modalFonts=c.showDialog({title:f("Fonts"),className:"google-fonts",body:['<div>\n   <div>\n       <form class="google-fonts-form">\n           <div class="form-group clearfix">\n               <div id="media-tabs">\n                   <ul class="nav nav-tabs">','                       <li>                           <button style="margin: 0 5px 0 0" class="btn btn-primary '+
(c.isAMP()?"disabled":"")+'" id="browse-font">'+f("Browse Computer")+"</button>                       </li>",'                       <li class="active">','                           <a href="#1" data-toggle="tab">'+f("Google Fonts")+"</a>","                       </li>",'                       <li>                           <a href="#2" data-toggle="tab" id="downloaded-fonts-tab">'+f("Site Fonts")+"</a>                       </li>",'                   </ul>\n                   <div class="tab-content">\n                       <div class="tab-pane active" id="1">\n                           <iframe id="gf-iframe" frameborder="0" width="100%" height="500px" src="about:blank"></iframe>\n                       </div>\n                       <div class="tab-pane" id="2">\n                           <iframe id="lf-iframe" frameborder="0" width="100%" height="500px" src="about:blank"></iframe>\n                       </div>\n                   </div>\n                  <div class="help-wrapper">\n                       <span>Help: </span>\n                       <a id="managing-fonts" href="javascript:void(0)">Managing fonts,</a>\n                       <a id="fonts-locally" href="javascript:void(0)">Using Google fonts locally</a>\n                   </div>\n               </div>\n           </div>\n       </form>\n   </div>\n</div>'].join("\n"),
buttons:{fontsOk:{label:f("Ok"),className:"btn-primary"}},show:function(a){a.find("#managing-fonts").click(function(){c.openUrl("https://mobirise.com/help/managing-fonts-394.html")});a.find("#fonts-locally").click(function(){c.openUrl("https://mobirise.com/help/how-to-set-up-google-fonts-as-local-fonts-842.html")})},hide:function(){c.redrawStyleChanger()}});a.$modalFonts.find(".modal-content").before(a.$loader);a.$loader.css({borderRadius:"8px",opacity:.8});a.$loader.show();a.$modalFonts.find("#browse-font").on("click",
function(b){b.preventDefault();Bridge.runFileDialog(f("Select font"),Bridge.docLocation,"Fonts file (*.eot *.woff *.ttf *.woff2)",function(b){if(b){a.$loader.show();var d=Bridge.splitPath(b),e=decodeURI(d.name),l=a.fontsPath+"/"+d.name,h=l+"/font."+d.ext;c.getProjectFont(e)?(a.fillCards(a.$iframeLocal,c.projectSettings.siteFonts,function(){a.$loader.hide()},!0),c.alertDlg("'"+e+"' font is already loaded!")):Bridge.copyLocal(b,h,function(b){b?(b=["@font-face {","   font-family: '"+e+"';","   font-display: swap;",
"   src: url('"+b+"');","}\n"].join("\n"),Bridge.saveLocalFile(l+"/style.css",b,function(b){b?(c.projectSettings.siteFonts.push({css:"'"+e+"'",name:e,url:null,file:h}),a.activateFont(e)):(a.fillCards(a.$iframeLocal,c.projectSettings.siteFonts,function(){a.$loader.hide()},!0),c.alertDlg(f("Error saving style.css for $font name$").replace("$font name$","'"+e+"'")))})):(a.fillCards(a.$iframeLocal,c.projectSettings.siteFonts,function(){a.$loader.hide()},!0),c.alertDlg("Error copying file!"))})}})});d("gf-iframe",
function(){a.$iframeGoogle=a.$modalFonts.find("#gf-iframe").contents();a.$iframeGoogle.find("body").addClass("gf-body");a.$iframeGoogle.find("head").append('<link id="insertBefore">');a.$iframeGoogle.find("body").prepend(['<div class="gf-form clearfix">','   <input class="form-control gf-form__input" value="" type="text" placeholder="'+f("Search by font name")+'">',"</div>"].join("\n"));a.$iframeGoogle.find(".gf-form .gf-form__input").on("keydown",function(c){var d=b(this),e=setTimeout(function(){var b=
d.val().trim(),c=a.searchFonts(b);a.$iframeGoogle.find("#insertBefore").nextAll().remove();a.$iframeGoogle.find(".gf-list").replaceWith('<ul class="gf-list"></ul>');var l=a.$iframeGoogle.find(".gf-list");a.$loader.show();c.length?b?(a.$iframeGoogle.off(),a._lastIndex=0,a._blockScroll=!0,a.$loader.show(),a.fillCards(a.$iframeGoogle,c,function(){a.$loader.hide()}),a._blockScroll=!1,l.on("scroll",function(){!a._blockScroll&&l.height()+l.scrollTop()>l[0].scrollHeight-10&&(a._blockScroll=!0,a.$loader.show(),
a.fillCards(a.$iframeGoogle,c,function(){a.$loader.hide()}),a._blockScroll=!1)})):(a._lastIndex=0,a.fillCards(a.$iframeGoogle,a.gFonts,function(){a.$loader.hide()})):(l.append('<h2 class="gf-list__error">No fonts found!</h2>'),a.$loader.hide());clearTimeout(e)},300)});a.getGoogleFonts(function(b,d){b?(a.$loader.hide(),c.alertDlg("Connection error!")):(a.gFonts=d,a.fillCards(a.$iframeGoogle,a.gFonts,function(){a.$loader.hide();a.$iframeGoogle.find(".gf-list").on("scroll",function(){if(!a._blockScroll){var b=
a.$iframeGoogle.find(".gf-list");b.height()+b.scrollTop()>b[0].scrollHeight-10&&(a._blockScroll=!0,a.$loader.show(),a.fillCards(a.$iframeGoogle,a.gFonts,function(){a.$loader.hide()}),a._blockScroll=!1)}})}))})});d("lf-iframe",function(){a.$iframeLocal=a.$modalFonts.find("#lf-iframe").contents();a.$iframeLocal.find("body").addClass("lf-body");b("#downloaded-fonts-tab").on("click",function(){b(this).parent().hasClass("active")||(a.$loader.show(),a.fillCards(a.$iframeLocal,c.projectSettings.siteFonts,
function(){a.$loader.hide()},!0))})})}}function k(){b("#theme-settings").find(".app-layer-font .dropdownjs").each(function(){var c=b(this).data("select");c=b(c.data("dropdownjs-ul"));var d=b(this).closest("[data-setting-name]").data("setting-name");d=b('<button name="fontManager" class="btn  btn-primary" data-setting-name="'+d+'">'+f("More fonts")+"</button>");c.find('button[name="fontManager"]').length||(c.append(d),d.on("click",function(){(new g("AIzaSyAHKXsrK2fMCl5gJJBy4N8t-_959d1zDls",b(this).data("setting-name"))).init()}))})}
g.prototype.$loader=b(c.preloaderHTML);g.prototype.searchFonts=function(b){var c=[];b=new RegExp(b,"i");for(var e=0,a=this.gFonts.length;e<a;e++)0<=this.gFonts[e].family.search(b)&&c.push(this.gFonts[e]);return c};g.prototype.getGoogleFonts=function(b){Bridge.http(this.requestUrl,{success:function(c,e){if(200===e.statusCode||200===e.code||200==e.status)try{var a=JSON.parse(c).items;b(null,a)}catch(h){b(!0)}else b(!0)},error:function(){b(!0)}})};g.prototype.getFontLink=function(b){for(var c="https://fonts.googleapis.com/css?family="+
b.family.replace(/\s/g,"+"),e,a="",h=0,f=b.variants.length;h<f;h++)e=b.variants[h],e.match(/\d+italic/)?e=e.replace("italic","i"):e.match("italic")?e=e.replace("italic","400i"):e.match("regular")&&(e=e.replace("regular","400")),a=h<f-1?a+(e+","):a+e;return c+(":"+a)};g.prototype.activateFont=function(c){this.$modalFonts.trigger("hidden.bs.modal");var d='.app-layer-font[data-setting-name="'+this.settingName+'"] select';d=b("#theme-settings").find(d);d.val(c);d.trigger("change")};g.prototype.fillCards=
function(b,d,l,a){var e=this;if(a)c.initFontsForFrame(b,function(){b.find(".gf-list").replaceWith('<ul class="gf-list"></ul>');for(var a=0,c=d.length;a<c;a++)e.appendCard(b,d[a],!0);l&&l()});else if(e._lastIndex>=e.gFonts.length)l();else{a=e._lastIndex;for(var f=e._lastIndex+e.loadQuantity;a<f&&d[a];a++)b.find("head").append('<link href="'+e.getFontLink(d[a])+'" rel="stylesheet">'),e.appendCard(b,d[a]);e._lastIndex=a;setTimeout(function(){l&&l()},1E3)}};g.prototype.appendCard=function(e,d,l){function a(a){function b(a){m.downloadFonts(a,
function(b){b?c.alertDlg(f("Download font error!")):(m.$loader.show(),m.activateFont(a.family),c.fire("downloadedFont",a));m.$loader.hide()})}a.preventDefault();m.$loader.show();if(d.files)b(d);else{a=0;for(var e=m.gFonts.length;a<e;a++)if(d.name===m.gFonts[a].family){b(m.gFonts[a]);break}}}function h(d){d.preventDefault();var e=b(this);m.$loader.show();m.isFontInUse(n)?(c.alertDlg(f("This is the font used in the project!")),m.$loader.hide()):m.removeFont(n,function(d){if(d){if(l){if(p.remove(),d=
m.$iframeGoogle.find(".gf-list").find('.gf-card__title:contains("'+n+'")'),d.length)for(var h=0,g=d.length;h<g;h++){var r=b(d[h]),k=r.prev().find(".gf-controls__button"),t=k.closest(".gf-card");if(r.text().trim()===n){m.triggerFontButton(k);k.off();t.on("click",a);break}}}else m.triggerFontButton(e),e.off(),e.closest(".gf-card").on("click",a);c.fire("deletedFont",n);c.alertDlg(f("This font has been successfully removed."))}else c.alertDlg(f("Font removal error!"));m.$loader.hide()})}var g=' \n        <div class="block-info">\n            <div class="block-info__theme-name-tag ">'+
(d.url?"Google":"Local")+"</div>\n        </div>      \n        ",m=this,n=l?d.name:d.family,k=c.getProjectFont(n),p=b(['<li class="gf-list__item">\n   <div class="gf-card ',k?"gf-card_downloaded":"",'   ">\n       <div class="gf-card__controls">\n           <ul class="gf-controls">\n               <li class="gf-controls__item">\n                   <span class="gf-controls__button ',k?"gf-controls__button_del btn-material-red mbr-icon-trash":"gf-controls__button_add mbr-icon-plus",'                   "></span>\n               </li>\n           </ul>\n       </div>\n       <p class="gf-card__title">',
"           "+n,'       </p>\n       <p class="gf-card__text">',f("The quick brown fox jumps over the lazy dog."),"       </p>",l?g:"","   </div>\n</li>"].join("\n"));e.find(".gf-list").append(p);p.find(".gf-card__text").css({"font-family":n});if(k)p.find(".gf-controls__button").off().on("click",h);else p.find(".gf-card").off().on("click",a)};g.prototype.triggerFontButton=function(b){b.hasClass("gf-controls__button_add")?b.removeClass("gf-controls__button_add mbr-icon-plus").addClass("gf-controls__button_del btn-material-red mbr-icon-trash").closest(".gf-card").addClass("gf-card_downloaded"):
b.removeClass("gf-controls__button_del btn-material-red mbr-icon-trash").addClass("gf-controls__button_add mbr-icon-plus").closest(".gf-card").removeClass("gf-card_downloaded")};g.prototype.downloadFonts=function(b,d){function e(a){c.getProjectFont(a.family)||c.projectSettings.siteFonts.push({css:"'"+a.family+"', "+a.category,name:a.family,url:m.getFontLink(a)})}var a=c.projectPath+"/fonts/"+b.family,h="",g=[],m=this,k;for(k in b.files)g.push({weight:k,file:b.files[k]});g=c.applyFilter("downloadFonts",
g);c.waitAllAndDo(g,function(c,d){Bridge.download2(c.file,function(e){if(e){var f=a+"/"+c.weight+".ttf";Bridge.moveLocal(e,f,function(a){if(a){var e=c.weight.match(/([0-9]+)([a-z]+)?/);e?(a=e[2]?e[2]:"normal",e=e[1]):(a=c.weight,e=400);h+=["@font-face {","   font-family: '"+b.family+"';","   font-style: "+a+";","   font-display: swap;","   font-weight: "+e+";","   src: url('"+f+"') format('truetype');","}\n"].join("\n");d(h)}else d("")})}else d("")})},function(){h?Bridge.saveLocalFile(a+"/style.css",
h,function(a){a?(e(b),d()):d(f("Error file saving!"))}):(e(b),d())})};g.prototype.removeFont=function(b,d){Bridge.removeLocal(c.projectPath+"/fonts/"+b,function(e){if(e)for(var a in c.projectSettings.siteFonts){if(c.projectSettings.siteFonts[a].name===b){c.projectSettings.siteFonts.splice(a,1);d(!0);break}}else d(!1)})};g.prototype.isFontInUse=function(b){var d=c.getUsedFonts(),e=d.length;if(e)for(var a=0;a<e;a++)if(b===d[a].name)return!0;return!1};c.regExtension({name:"fonts",global:{getThemeFonts:function(){var c=
[];"object"===typeof this.theme.params.theme&&this.theme.params.theme.fonts&&(c=b.extend([],this.theme.params.theme.fonts));return this.applyFilter("getThemeFonts",c)||[]},getAccesibleFonts:function(){var b=[].concat(c.projectSettings.siteFonts||[]),d=b.length;c.getThemeFonts().forEach(function(c){for(var a=c.name,e=0;e<d;e++)if(a==b[e].name)return;b.push(c)});return b},getFont:function(b){for(var c=this.getAccesibleFonts(),e=0;e<c.length;e++)if(c[e].name===b)return c[e];return{}},waitAllAndDo:function(){function b(c,
e,a){if(!c.length)return a();e(c.splice(0,1)[0],function(){b(c,e,a)})}return b}(),getUsedFonts:function(){var e=b("#theme-settings").find(".app-layer-select select, .app-layer-font select"),d=[];if(e.length)for(var f=0,a=e.length;f<a;f++){var h=c.getProjectFont(e[f].value);if(h){a:{var g=e[f].value;for(var m=0,k=d.length;m<k;m++)if(g===d[m].name){g=!1;break a}g=!0}g&&d.push(h)}}return d},getProjectFont:function(b){for(var d=0,e=c.projectSettings.siteFonts.length;d<e;d++)if(b===c.projectSettings.siteFonts[d].name)return c.projectSettings.siteFonts[d];
return!1},initFontsForFrame:function(e,d){e instanceof Array||(e=[e]);var f="",a=c.projectSettings.siteFonts.map(function(a){return c.projectPath+"/fonts/"+a.name+"/style.css"});c.waitAllAndDo(c.applyFilter("initFontsForFrame",a,c.projectSettings.siteFonts),function(a,c){/^http[s]?:/.test(a)?(e.forEach(function(c){b(c).find("head").append('<link href="'+a+'" rel="stylesheet">')}),c()):Bridge.loadLocalFile(a,function(a){f+=a;c()})},function(){f&&e.forEach(function(a){b(a).find("#userFonts").length?
b(a).find("#userFonts").text(f):b(a).find("body").append("<style id='userFonts'>"+f+"</style>")});d&&d()})},checkProjectFonts:function(e){function d(){c.redrawStyleChanger();c.Core.render()}function f(c){function d(b){b<c.length?a(c[b]).then(function(a){a?d(++b):h(c[b]).then(function(){d(++b)})}):e.resolve()}var e=b.Deferred();d(0);return e.promise()}function a(a){for(var d=c.projectSettings.siteFonts,f=0,g=d.length;f<g;f++)if(d[f].name===a&&(d[f].url||d[f].file)&&d[f].css)return $Bridge.isExistsLocal(e+
"/fonts/"+a);return b.Deferred().resolve(!1)}function h(a){var c=new g("AIzaSyAHKXsrK2fMCl5gJJBy4N8t-_959d1zDls"),d=b.Deferred();c.getGoogleFonts(function(b,e){if(b)return d.resolve();b=0;for(var f=e.length;b<f;b++)if(e[b].family===a)return c.downloadFonts(e[b],function(a){d.resolve()});k(a).then(function(){d.resolve()})});return d.promise()}function k(a){var d=e+"/assets/fonts/"+encodeURI(a),f=e+"/fonts/"+encodeURI(a);return $Bridge.dirList(d,{names:["*.ttf","*.eot","*.woff","*.woff2"],recursive:!1}).then(function(e){var g=
b.Deferred();if(e.length){var h=d+"/"+e[0];var l=f+"/"+e[0];$Bridge.copyLocal(h,l).then(function(b){var d=["@font-face {","   font-family: '"+a+"';","   font-display: swap;","   src: url('"+l+"');","}\n"].join("\n");b?$Bridge.saveLocalFile(f+"/style.css",d).then(function(){c.projectSettings.siteFonts.push({css:"'"+a+"'",name:a,url:null,file:l});g.resolve()}).fail(function(){g.resolve()}):g.resolve()}).fail(function(){g.resolve()})}else g.resolve();return g.promise()})}var m,n=[];try{var q=c.projectSettings.theme.styling;
for(m in q)/display\dFont/g.test(m)&&(function(){if(n.length)for(var a=0,b=n.length;a<b;a++)if(q[m]===n[a])return!0;return!1}()||n.push(q[m]))}catch(p){}n=c.applyFilter("checkProjectFonts",n);n.length?f(n).then(d):d()}},events:{load:function(){function b(b){var a=c.getUsedFonts(),d=[];if(a.length){for(var e=0,f=a.length;e<f;e++)a[e].url||(b.push({srcList:[{src:a[e].file}],dest:"assets/fonts/"+a[e].name+"/"+Bridge.splitPath(a[e].file).fullname}),b.push({srcList:[{src:c.projectPath+"/fonts/"+a[e].name+
"/style.css"}],dest:"assets/fonts/"+a[e].name+"/style.css"}),d.push({src:c.projectPath+"/fonts/"+a[e].name+"/style.css",filter:"template"}));d.length&&b.push({srcList:d,dest:"assets/fonts/style.css"})}return b}var d=[];c.on("getPublishFonts",function(b){d=Array.from(new Set(b))});c.addFilter("publishAssets",function(b,a){var e=c.projectSettings.cookiesAlert&&"3"===c.projectSettings.cookiesAlertType;c.getUsedFonts().some(function(a){return!a.url})&&(b.css+="<link "+(e?"data-href":"href")+'="assets/fonts/style.css" rel="stylesheet">\n  ');
!c.isAMP()&&d.length&&(d.forEach(function(a){b.css+='<link rel="preload" '+(e?"data-href":"href")+'="'+a+'&display=swap" as="style" onload="this.onload=null;this.rel=\'stylesheet\'">\n  <noscript><link rel="stylesheet" '+((e?"data-href":"href")+'="'+a+'&display=swap"></noscript>\n  ')}),d=[]);return b});c.addFilter("publishFiles",function(c){return b(c)});c.addFilter("exportProjectFiles",function(c){return b(c)});c.addFilter("publishTemplating",function(b,a){var d=c.getUsedFonts();if(d.length)for(var e=
0,f=d.length;e<f;e++)if(a===c.projectPath+"/fonts/"+d[e].name+"/style.css")return["@font-face {","   font-family: '"+d[e].name+"';","   font-display: swap;","   src: url('"+d[e].name+"/"+Bridge.splitPath(d[e].file).fullname+"');","}\n"].join("\n");return b})},loadProjectCore:function(b,d){c.projectSettings.siteFonts=c.projectSettings.siteFonts||[];this.checkProjectFonts(d)},initSettingsSidebar:function(){k()},redrawStyleChanger:function(){this.initFontsForFrame([c.$template,c.$body]);k()}}})},["jQuery",
"mbrApp","TR()"]);
