var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,e){a!=Array.prototype&&a!=Object.prototype&&(a[c]=e.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,c,e,b){if(c){e=$jscomp.global;a=a.split(".");for(b=0;b<a.length-1;b++){var f=a[b];f in e||(e[f]={});e=e[f]}a=a[a.length-1];b=e[a];c=c(b);c!=b&&null!=c&&$jscomp.defineProperty(e,a,{configurable:!0,writable:!0,value:c})}};$jscomp.polyfill("Object.is",function(a){return a?a:function(c,a){return c===a?0!==c||1/c===1/a:c!==c&&a!==a}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(c,a){var b=this;b instanceof String&&(b=String(b));var f=b.length;a=a||0;for(0>a&&(a=Math.max(a+f,0));a<f;a++){var d=b[a];if(d===c||Object.is(d,c))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,c,e){if(null==a)throw new TypeError("The 'this' value for String.prototype."+e+" must not be null or undefined");if(c instanceof RegExp)throw new TypeError("First argument to String.prototype."+e+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(a,e){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,e||0)}},"es6","es3");
defineM("app-themes",function(a,c,e){c.regExtension({name:"themes",global:{DEFAULT_THEME:"startm5",DEFAULT_THEME_TITLE:"StartM5",checkM3Theme:function(a){return"default unicore sleek colorm spacem directm clarus purity mobirise3".split(" ").includes(a)},getSecondaryThemesList:function(b){var f=[];a.when(c.getAddonsEx(function(a){f.push("startm5");f.push("mobirise5");for(var b=0,c=a.length;b<c;b++)a[b].theme&&"object"==typeof a[b].theme&&"secondary"===a[b].theme.type&&f.push(a[b].name)},{type:"theme"})).then(function(){b(f)})},
calcProjectTheme:function(a){var b="default",c="Mobirise";if(!a)return{};a.settings&&a.settings.theme&&("object"===typeof a.settings.theme?(b=a.settings.theme.name||b,c=a.settings.theme.title||c):(b=a.settings.theme||b,c=a.settings.theme||c));return{name:b,title:c}},requestTheme:function(b,f){var d=a.Deferred(),h=this;if(!b)return d.reject("Wrong project"),d.promise();if(b==(h.theme&&h.theme.name))return d.resolve(!0),d.promise();(function(a,b){b=b||function(){};h.getAddonsEx(function(d){for(var f=
0;f<d.length;f++)if(d[f].name===a){c.readAddon(c.getAddonDir(a),b);return}b()},{type:"theme"})})(b,function(a){if(a)d.resolve(!1);else{var f="";(a=c.getUserInfo())&&a.email&&(f=a.email);if(a&&a.email)c.getAddonsEx(0,0,{server:!0,serverOptions:{with_archive:1},restricted:!0}).then(function(a,h,g){var k=function(a,b){var f=a.downloadURL||"";c.downloadAddon(a).done(function(a){a&&b&&b(!0)}).fail(function(d,m){c.alertDlg(d+'"'+a.title+'" ('+m+")."+(f?"":e("Try to log out and log back in"))).on("hidden.bs.modal",
function(){b&&b(!1)})})},l;a.forEach(function(a){if(a.name===b)if(l=a,a.installed){if(Number(a.installed)<Number(a.version)||a.expired&&a.expiredDate<a.modified)!a.downloadURL&&a.buyURL||a.installed>=a.version?(c.openUrl("https://mobirise.com/extensions/"+a.name+"/"),d.reject()):k(a,function(){d.resolve(!1)})}else"future"==a.status?(c.openUrl(comingSoonLink),d.resolve(!1)):!a.downloadURL||a.expired&&a.premium||a.minVersion&&!(a.version>=a.minVersion)?a.buyURL?c.confirmDlg({message:e("The project you are loading is based on the $extension$ theme, which is not available for your account").replace("$extension$",
a.name?"<strong>"+a.name+"</strong>":"")+(f?" "+f+"<br>":".<br>"),buttons:{cancel:{label:e("Cancel"),className:"btn-default"},confirm:{label:e("Download $addonName").replace("$addonName",a.name),className:"btn-primary"}},callback:function(a){a&&c.openUrl("https://mobirise.com/extensions/kit/");c.loadThemeAddon(!1,function(a){c.createProject("My Site",0,0)})}}):d.resolve(!1):k(a,function(){d.resolve(!1)})});if(!l)return d.reject("No themes available for project")}).catch(function(a){d.reject("No themes available for project")});
else return d.reject(b+" theme is not available.")}});return d.promise()},loadThemeAddon:function(b,f){var d=this;b||console.warn("Warning: Force default theme will be loaded");b=b||"startm5";var e=c.getAddonDir(b);c.readAddon(e,function(g){function h(){d.fire("themeLoaded");f(!!g)}"startm5"===b||g?(d.theme=d.Core.theme={},a.extend(d.theme,{name:b,path:Bridge.path2app(e),pathCore:c.path2core(e),pathExport:e}),d.theme.params=g||{},g?d.loadEachAddon(e,g,!1,function(a){setTimeout(h,0)}):h()):f(!1)})},
getThemeButtonColors:function(){var a={"btn-default":"#e6e6e6","btn-primary":"#286090","btn-success":"#449d44","btn-info":"#31b0d5","btn-warning":"#ec971f","btn-danger":"#c9302c"};"object"===typeof this.theme.params.theme&&this.theme.params.theme.buttonColors&&(a=this.theme.params.theme.buttonColors);return this.applyFilter("getThemeButtonColors",a)},hasButtonOutlineColors:function(){return this.theme.params.theme&&this.theme.params.theme.hasButtonOutlineColors},getThemeLinkColors:function(){var a=
{"text-muted":"#777","text-primary":"#337ab7","text-success":"#3c763d","text-info":"#31708f","text-warning":"#8a6d3b","text-danger":"#a94442"};"object"===typeof this.theme.params.theme&&this.theme.params.theme.linkColors&&(a=this.theme.params.theme.linkColors);return this.applyFilter("getThemeLinkColors",a)},getThemeColorsSet:function(a){var b="#7ac673 #1ABC9C #27aae0 #2C82C9 #9365B8 #4c6972 #FFFFFF #41A85F #00A885 #3D8EB9 #2969B0 #553982 #475577 #EFEFEF #F7DA64 #faaf40 #EB6B56 #E25041 #A38F84 #28324E #CCCCCC #FAC51C #f97352 #D14841 #B8312F #7C706B #000000 #c1c1c1".split(" ");
"object"===typeof this.theme.params.theme&&this.theme.params.theme.colorsSet&&(b=this.theme.params.theme.colorsSet);b=this.applyFilter("getThemeColorsSet",b);c.projectSettings.theme.additionalSetColors&&(b=b.concat(c.projectSettings.theme.additionalSetColors));if("number"===typeof a){for(var d=[],e=0,g=[];e<b.length;e++)g.push(b[e]),e%a===a&&(d.push(g),g=[]);d.push(g);b=d}return b}},events:{load:function(){}}})},["jQuery","mbrApp","TR()"]);
