var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(k,p,m){if(null==k)throw new TypeError("The 'this' value for String.prototype."+m+" must not be null or undefined");if(p instanceof RegExp)throw new TypeError("First argument to String.prototype."+m+" must not be a regular expression");return k+""};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(k,p,m){k!=Array.prototype&&k!=Object.prototype&&(k[p]=m.value)};$jscomp.getGlobal=function(k){return"undefined"!=typeof window&&window===k?k:"undefined"!=typeof global&&null!=global?global:k};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(k,p,m,n){if(p){m=$jscomp.global;k=k.split(".");for(n=0;n<k.length-1;n++){var r=k[n];r in m||(m[r]={});m=m[r]}k=k[k.length-1];n=m[k];p=p(n);p!=n&&null!=p&&$jscomp.defineProperty(m,k,{configurable:!0,writable:!0,value:p})}};
$jscomp.polyfill("String.prototype.startsWith",function(k){return k?k:function(k,m){var n=$jscomp.checkStringArgs(this,k,"startsWith");k+="";var p=n.length,q=k.length;m=Math.max(0,Math.min(m|0,n.length));for(var t=0;t<q&&m<p;)if(n[m++]!=k[t++])return!1;return t>=q}},"es6","es3");
(function(){function k(a,b,e){a=a||{};b=b||{};for(var c in b)if(e||void 0==a[c])a[c]=b[c];return a}function p(a){a=(a||"").split(".");for(var b=0;b<a.length;b++)a[b]=parseInt(a[b])||0;return a}function m(a){c.versionName=c.versionName||c.version;c.version=p(c.version).join(".");c.projectDataLocation=n(c.projectDataLocation)||c.dataLocation;c.publicTempLocation=n(c.publicTempLocation)||c.tempLocation;c.imgLocation=n(c.imgLocation)||c.docLocation;c.projectsLocation=n(c.projectsLocation)||c.dataLocation;
a=a||function(){};if(c.debug&4)for(var b in c)"function"==typeof c[b]&&function(a){var b=c[a];c[a]=function(){console.log("Bridge."+a,arguments);return b.apply(this,arguments)}}(b);c.getArgs(function(b){if(b){for(var e=/^--([^=]+)=?/,f=0,g=0;g<b.length;g++)e.test(b[g])?c.args[e.exec(b[g])[1]]=b[g].replace(e,""):c.args[f++]=b[g];c.initPath=c.args[1]?c.sys2url(c.args[1]):""}"tests"in c.args?c.isExistsLocal("web/../test/init-tests.js",function(b){b&&("complete"!=document.readyState||"loading"==document.readyState?
document.write('<script type="text/javascript" src="../test/init-tests.js">\x3c/script>'):(b=document.createElement("script"),b.type="text/javascript",b.src="../test/init-tests.js",document.getElementsByTagName("head")[0].appendChild(b)));a()}):a()})}function n(a){return a.replace("@DATA_LOCATION@",c.dataLocation).replace("@TEMP_LOCATION@",c.tempLocation).replace("@DOC_LOCATION@",c.docLocation)}function r(){(window.bootbox&&bootbox.alert||window.alert)("Unfortunately, this feature is not available in your browser.")}
function q(){return"undefined"!==typeof qt||navigator.userAgent.match(/Mobirise/i)||navigator.userAgent.match(/Electron/i)||/ios/.test(c.getPlatform())}var t={appName:"Mobirise",version:"0.0.0.0",dataLocation:"",projectDataLocation:"@DATA_LOCATION@/projectData",tempLocation:"",publicTempLocation:"@TEMP_LOCATION@",docLocation:"",imgLocation:"@DOC_LOCATION@",projectsLocation:"@DATA_LOCATION@/projects",isPro:!0,isDev:!1,debug:0,getArgs:function(a){a&&a(window.location.href.split(/&|\?/))},templating:function(a){return a},
afterTemplating:function(a){return this.templating(a)},openUrl:function(a){window.open(a,"_blank")},runFileDialog:function(a,b,c,d,f){q()||r();d&&d("")},runFileDialog2:function(a,b){var e=[];a&&(e.push(b&&b.caption||""),e.push(b&&b.path||""),e.push(b&&b.filter||""),e.push(a),e.push(b&&b.multi),c.runFileDialog.apply(c,e))},initProject:function(a){if(a){var b=c.dataLocation+"/projects/project-"+c.dateFormat(new Date,"yyyy-MM-dd_hhmmss");a("",{path:b})}},saveLocalFile:function(a,b,e){console.warn('call Bridge.saveLocalFile("'+
a+'", String['+b.length+"])");q()||!/^\/projects\/.+project\.mobirise$/.test(a)&&!/^\/recents.list$/.test(a)?e&&e(!1):(c.FILES=c.FILES||{},c.FILES[a]=b,e&&e(!0))},loadLocalFile:function(a,b){b=b||function(){};!q()&&(/^\/projects\/.+project\.mobirise$/.test(a)||0<=a.indexOf(c._recentsFile))?b(c.FILES&&c.FILES[a]||""):c.http(c.path2app(a),{success:function(){b()},error:function(){b("")}})},paranoicLoadLocal:function(a,b){c._paranoic_count=c._paranoic_count||{};c._paranoic_count[a]=(c._paranoic_count[a]||
0)+1;5<c._paranoic_count[a]?console.error("paranoicLoadLocal was started >5 times for",a):setTimeout(function(){c.loadLocalFile(a,function(e){e?(c._paranoic_count[a]=0,b&&b(e)):c.getInfoLocal(a,function(e){e&&e.size?setTimeout(function(){c.paranoicLoadLocal(a,b)},100):(c._paranoic_count[a]=0,b(""))})})},1)},paranoicSaveLocal:function(a,b,e){function d(){c.moveLocal(f,a,function(a){setTimeout(function(b){e(a)},1)})}e=e||function(){};var f=a+"-tmp";c.saveLocalFile(f,b,function(a,l){a?setTimeout(function(a){c.loadLocalFile(f,
function(a){b.length==a.length?d():e(!1,Error("Unable to move saved paranoic local file. data.length != saved_data.length"))})},1):e(!1,l)})},registerPreviewPath:function(){return c.publicTempLocation+"/"+c.dateFormat(new Date,"yyyyMMdd_hhmmss")},copyLocal:function(a,b,c){c&&c("")},removeLocal:function(a,b){b&&b(!1)},isExistsLocal:function(a,b){c.loadLocalFile(a,function(a){b&&b(!!a)})},dirList:function(a,b,c){b&&b([])},getInfoLocal:function(a,b){b&&b()},moveLocal:function(a,b,c){c&&c(!1)},loadLocalBase64:function(a,
b){c.loadLocalFile(a,function(a){b(btoa(a))})},saveLocalBase64:function(a,b,c){c&&c(!1)},gzipBase64:function(a,b){console.warn("call gzipBase64");b&&b("")},md5_base64:function(a,b){console.warn("call md5_base64");b&&b("")},uploadBuildIn:function(a,b,e){function d(l){switch(f){case 4:return;case 1:if(l){f=l;return}break;case 2:if(!l||3==l)return;f=l;l=0;break;case 3:if(l){f=l;return}f=2;return;case 5:if(l)return;a=""}if(0>g)c._uploadBuildIn_init(a,function(a){a?(f=2,e.onError(a)):(e.onStart(b.length),
g=0,d())});else if(g>=b.length||5==f)f=4,c._uploadBuildIn_done(a,function(b){if(b)e.onError(b);e.onClose(a)});else{var k=b[g++];e.onFile(k.dest);c._uploadBuildIn_file(k,e.onData,a,function(a){a?(f=2,e.onError(a)):(e.onUploaded(k.dest),d())})}}if(!a||!b)return"file";e=k(e,{onStart:function(a){},onFile:function(a){},onUploaded:function(a){},onError:function(a){},onClose:function(a){},onData:function(a,b){return""}});var f=1,g=-1;setTimeout(d,1);return{resume:function(){d(1)},pause:function(){d(3)},
exit:function(){d(5)}}},_uploadBuildIn_init:function(a,b){console.log("Emulate Bridge.uploadBuilding()...");console.log("Upload to url =",a);setTimeout(function(){b&&b("")},1)},_uploadBuildIn_done:function(a,b){console.log("Upload is done! url =",a);setTimeout(function(){b&&b("")},1)},_uploadBuildIn_file:function(a,b,c,d){console.log("Uploading file "+a.dest);for(c=0;c<a.srcList.length;c++){var e=a.srcList[c];if(e.filter){var g=b(e.src,e.filter);console.log("<<< "+e.src+" <<< data.length="+g.length)}else console.log("<<< "+
e.src)}setTimeout(function(){d&&d("")},100)},supportedImgExts:"jpg jpeg png webp tif gif svg ico".split(" "),getScreen:function(a,b,c,d){console.warn("call Bridge.getScreen()");a&&a()},setSettings:function(a,b,c){console.warn("call Bridge.setSettings("+a+","+b+")");c&&c(!1)},getSettings:function(a,b){var c="";"account"==a&&(c='{"email":"mobirise@gmail.com","token":"1234"}');b&&b(c)},setSettingsArray:function(a,b){function e(b){c.getSettings(a+"/"+b,function(d){d&&(c.setSettings(a+"/"+b,""),e(b+1))})}
for(var d=0;d<b.length;d++)c.setSettings(a+"/"+d,b[d]);e(b.length)},getSettingsArray:function(a,b){function e(d,f){c.getSettings(a+"/"+d,function(a){a?(f.push(a),e(d+1,f)):b(f)})}e(0,[])},encode:function(a,b){b&&b(a)},decode:function(a,b){b&&b(a)},verify:function(a,b,c){c&&c(!1)},download:function(a,b){b&&b(a)},download2:function(a,b,c){b&&b(a)},download3:function(a,b){c.download2(a,b.callback,b.headers)},osLocale:function(a){a(window.navigator.language.replace("-","_"))},args:{},isValid:function(){return!1},
versionCmp:function(a,b){a=(a||"").split(".");b=(b||"").split(".");for(var c=0;c<a.length||c<b.length;c++)if(a[c]=parseInt(a[c])||0,b[c]=parseInt(b[c])||0,a[c]!=b[c])return a[c]-b[c];return 0},base:function(){var a=window.location.href.split("?")[0];return a.substr(0,a.lastIndexOf("/")+1)}(),path2app:function(a){return/^(\w*:)?\/\//.test(a)?a:a&&a.startsWith("web/")?a.substr(4):"../"+a},url2sys:function(a){a=decodeURI(a);return a=/^file:\/\/\/\w+:/.test(a)?a.replace(/^file:\/\/\/(\w+:)/,"$1").replace(/\//g,
"\\"):a.replace(/^file:\/\//,"")},sys2url:function(a,b){if(!a)return b||"";b=b||c.base;"/"!=b[b.length-1]&&(b+="/");a=encodeURI(a.replace(/\\/g,"/"));return/^(\w*:)?\//.test(a)?"file://"+a.replace(/^\w+:\//,"/$&"):b+a},substUrl:function(a){return a.replace("%name%",c.appName).replace("%ver%",c.version).replace("%os%",c.getPlatform()).replace("%reg%",c.isPro?"pro":"free")},FileManager:function(a,b,e,d){if(!a||!b)return c.uploadBuildIn("");var f=!1,g=c._fmQueue;e=k({start:function(a){},file:function(a){},
uploaded:function(a){},error:function(a){console.log("FileManager error:"+a);w()},close:function(a){}},e,!0);var l=this._run=function(){var e={onStart:u,onFile:x,onUploaded:m,onError:n,onClose:y,onData:c.templating.bind(d||{}),onAfterTransformData:c.afterTemplating.bind(d||{})};f=c.uploadBuildIn(b,a,e);if(!f)for(var g=0;g<c._fileManagerUploaders.length&&!(f=c._fileManagerUploaders[g](b,a,e));g++);};this.pause=function(){f&&f.pause()};var w=this.resume=function(){f&&f.resume()};this.exit=function(){f&&
f.exit()};var u=function(a){c.debug&1&&console.log("FileManager:emitStart",a);setTimeout(function(){e.start(a)},1)},x=function(a){c.debug&1&&console.log("FileManager:emitFile",a);setTimeout(function(){e.file(a)},1)},m=function(a){c.debug&1&&console.log("FileManager:emitUploaded",a);setTimeout(function(){e.uploaded(a)},1)},n=function(a){c.debug&1&&console.log("FileManager:emitError",a);e.error(a)},y=function(a){c.debug&1&&console.log("FileManager:emitClose",a);f=!1;setTimeout(function(){e.close(a)},
1);setTimeout(function(){g.shift();g.length&&g[0]._run()},1)};g.push(this);1==g.length&&l()},_fmQueue:[],fileManagerAddUploader:function(a){c._fileManagerUploaders.push(a)},_fileManagerUploaders:[],parseUrl:function(a){a=/^([^:]*):(?:\/\/(?:(?:([^\/:]*)(?::([^\/]*))?@)?([^\/@:]+)(?::(\d+))?))?(\/[^?]*)?(?:\?([^?]*))?$/.exec(a)||[];return{url:a[0],scheme:a[1],user:a[2],password:a[3],domain:a[4],port:parseInt(a[5]),path:a[6],query:a[7]}},joinUrl:function(a){a=a||{};return(a.scheme||"")+":"+(a.domain?
"//"+(a.user?a.user+("password"in a?":"+a.password:"")+"@":"")+a.domain+(a.port?":"+a.port:""):"")+(a.path?("/"!=a.path[0]?"/":"")+a.path:"")+(a.query?"?"+a.query:"")},bind:function(a,b){a="on"+a.toLowerCase();this[a]||(this[a]=[]);this[a].push(b)},unbind:function(a,b){a="on"+a.toLowerCase();if(!b)return this[a]=[];b=this[a].indexOf(b);if(-1<b)return this[a].splice(b,1)},emit:function(a,b){a="on"+a.toLowerCase();if(this[a])for(var c=0;c<this[a].length;c++)try{this[a][c](b)}catch(d){}},initPath:"",
OnReady:[],setOnReady:function(a){c.OnReady?c.OnReady.push(a):a()},emitOnReady:function(){for(;c.OnReady&&c.OnReady.length;)try{c.OnReady.shift()()}catch(a){console.error(a)}c.OnReady=0},regQuitTask:function(a){v.push(a)},getPlatform:function(){return navigator.userAgent.match(/Mobirise-webview/i)?"android":!/iphone|ipod|ipad/.test(navigator.userAgent.toLowerCase())||navigator.standalone||/safari/.test(navigator.userAgent.toLowerCase())?navigator.platform.match(/Mac/i)?"mac":navigator.platform.match(/Linux/i)?
"linux":"win":"ios"},isMobile:/android|webos|iphone|ipad|ipod|blackberry|iemobile|opera mini|mobirise-webview/i.test(navigator.userAgent.toLowerCase()),_recentsFile:"recents.list",_lastTopRecent:0,getRecentsList:function(a){c.paranoicLoadLocal(c.dataLocation+"/"+c._recentsFile,function(b){var e=[];try{e=JSON.parse(b)}catch(d){}b=e||[];c._lastTopRecent=b[0];a(b)})},addRecent:function(a,b){if(a&&a.path){var e=c._lastTopRecent;if(e&&a&&e.path==a.path&&e.mbrsite===a.mbrsite){var d=!0,f;for(f in a)if(a[f]!=
e[f]){d=!1;break}if(d){b(!0);return}}c._lastTopRecent=a;c.getRecentsList(function(e){e=e||[];for(var d=0;d<e.length;d++)if(e[d].path==a.path){d=e.splice(d,1)[0]||{};a.name=a.name||d.name;a.screenshot=a.screenshot||d.screenshot;break}e.unshift(a);c.paranoicSaveLocal(c.dataLocation+"/"+c._recentsFile,JSON.stringify(e),function(a){a||console.error("Error: unable to update recent list");b(a)})})}else b&&b(!1)},moveRecent:function(a,b,e){c.getRecentsList(function(d){for(var f=0;f<d.length;f++)if(d[f].path==
a){d.splice(b,0,d.splice(f,1)[0]);c.saveLocalFile(c.dataLocation+"/"+c._recentsFile,JSON.stringify(d),e);return}e&&e(!1)})},rmRecent:function(a,b){a&&c.getRecentsList(function(e){for(var d=[],f=0;f<e.length;f++)e[f].path!=a&&d.push(e[f]);c._lastTopRecent=d[0];q()?c.paranoicSaveLocal(c.dataLocation+"/"+c._recentsFile,JSON.stringify(d),b):(r(),b(!1))})},getRecentSettings:function(a,b){if(!b)return!1;a||b(!1);c._lastTopRecent&&c._lastTopRecent.path==a?b(c._lastTopRecent):c.getRecentsList(function(e){c._lastTopRecent=
e&&e[0]||c._lastTopRecent;for(var d=0;d<e.length;d++)if(e[d].path==a)return b(e[d]);b(!1)})},changeRecentSettings:function(a,b,e){if(a&&b){var d=c._lastTopRecent;if(d&&d.path==a){var f=!0,g;for(g in b)if(b[g]!=d[g]){f=!1;break}if(f){e(!0);return}}c.getRecentsList(function(d){var f=!1;d=d||[];for(var g=0;g<d.length;g++)if(d[g].path==a)for(var k in b)d[g][k]=b[k],f=!0;f||d.unshift(b);c._lastTopRecent=d[0];c.paranoicSaveLocal(c.dataLocation+"/"+c._recentsFile,JSON.stringify(d),e)})}},saveAllRecents:function(a,
b){a&&a.length?(c._lastTopRecent=a[0],c.paranoicSaveLocal(c.dataLocation+"/"+c._recentsFile,JSON.stringify(a),b)):(console.warn("Recent for save is empty and was skiped!"),b(!1))},http:function(a,b){var c=performance.now();b=k(b||{},{method:"GET",headers:{},data:null,timeout:5E3,success:function(a){},error:function(a){}});try{var d=new XMLHttpRequest}catch(g){try{d=new ActiveXObject("Microsoft.XMLHTTP")}catch(l){console.log(l.message),b.error(l.message)}}if(d){d.onreadystatechange=function(){if(4==
d.readyState){b.timeout&&clearTimeout(f);var a=performance.now()-c;200!=d.status&&d.status&&201!=d.status&&204!=d.status?b.error(d.status,d):b.success(d.responseText,d,a)}};try{d.open(b.method,a,!0);for(h in b.headers)d.setRequestHeader(h,b.headers[h]);d.send(b.data);if(b.timeout)var f=setTimeout(function(){d.abort();b.error("something went wrong",d)},b.timeout)}catch(g){console.log(g.message),b.error(g.message)}}return d},dateFormat:function(a,b){var c={"M+":a.getMonth()+1,"d+":a.getDate(),"h+":a.getHours(),
"m+":a.getMinutes(),"s+":a.getSeconds(),"q+":Math.floor((a.getMonth()+3)/3),S:a.getMilliseconds()};/(y+)/.test(b)&&(b=b.replace(RegExp.$1,(a.getFullYear()+"").substr(4-RegExp.$1.length)));for(var d in c)(new RegExp("("+d+")")).test(b)&&(b=b.replace(RegExp.$1,1==RegExp.$1.length?c[d]:("00"+c[d]).substr((""+c[d]).length)));return b},waitForEach:function(){function a(b,c,d,f){b.length?(f=b.splice(0,1)[0],c.call(this,f,function(e,f){if(f)return d([],Error("Image transformation error"));a(b,c,function(a,
b){a.splice(0,0,e);d(a,b)})})):d([])}return a}(),splitPath:function(a){a=a.split("/");var b={},c=b.fullname=a.splice(a.length-1,1)[0];b.noExt=0>c.indexOf(".");b.noExt?(b.ext="",b.name=c):(b.ext=c.substr(c.lastIndexOf(".")+1),b.name=c.substr(0,c.lastIndexOf(".")));b.dir=a.join("/");return b},openImage:function(a,b,e,d,f,g,l,m){function u(a,b){if(b)return m&&m(b),[];l&&Array.isArray(a)&&l.stageUp;f&&f(g?a||[]:a?a[0]:"")}function n(a,b,e,d){c.isExistsLocal(a,function(f){if(f){f=c.splitPath(a);var g=
f.name;d&&(g=g.substr(0,g.lastIndexOf(b+d)));d=(d||0)+1;g=g+b+d;n(f.dir+"/"+g+(f.noExt?"":"."+f.ext),b,e,d)}else e(a)})}function w(a){l&&1<=a.length&&(l.allLength=a.length);"/"!=b.substr(-1)&&(b+="/");c.waitForEach(a,function(e,f){var g=b+c.cleanURI(e.split("/").pop());n(g,"_",function(b){c[d?"moveLocal":"copyLocal"](e,b,function(c){c||console.error("Error image re-save file "+e+" to "+b);l&&1<=a.length&&l.stageUp;f(b)})})},u)}if(c.transformImage){var p={width:-1,height:-1,keepAspectRatio:!0,shrinkLarge:!1,
stretchSmall:!1,quality:100,format:"",multi:!1};c.getSettings("lastImageDialogDir",function(f){var n="Images (*."+c.supportedImgExts.join(" *.")+")";c.runFileDialog(a,e||f||c.imgLocation,n,function(a){a&&a.length&&(1!=a.length||a[0])?(a=Array.isArray(a)?a:[a],g&&$.each(a,function(b,c){a[b]=c.replace(/\\/g,"/")}),c.setSettings("lastImageDialogDir",c.splitPath(a[0]).dir),d?(d=k(p,d,!0),l&&Array.isArray(a)&&(l.allLength=a.length),c.waitForEach(a,function(a,b){var e=k({},d,!0);e.format=e.format||(/jpg|jpeg/i.test(c.splitPath(a).ext)?
"jpg":"png");"png"==e.format&&(e.quality=1);/(gif|svg|ico|tif|webp)$/i.test(a)?b(a):c.transformImage(a,e,b)},b?w:u,m)):(b||(b=c.tempLocation+"/open"+c.dateFormat(new Date,"yyyyMMdd_hhmmss")),w(a))):u()},g)})}else r(),u()},saveFileUnique:function(a,b,e){e=e||function(){};var d=function(d){function f(a,e,f){d[e]=a;c.saveLocalFile(b+"/hashes.json",JSON.stringify(d),function(c){c||console.error("unable to save "+b+"/hashes.json");f(b+"/"+a)})}function k(a){var b=/(?:[-_](\d+))?(?:(?:-\d+x\d+)*-(\d+x\d+))?(?:[-_](\d+))?\.([^\.]+)$/.exec(a);
return{name:a,base:b?a.replace(b[0],""):a,index:b?parseInt(b[1]):0,size:b?b[2]:"",ext:b?b[4]:""}}d=d||{};c.md5_base64(a,function(g){if(g)if(d[g]){var m=b+"/"+d[g];c.isExistsLocal(b+"/"+d[g],function(b){b?e(m):c.copyLocal(a,m,function(a){a||console.error("unable to save "+a);e(a)})})}else{var l=a.split("/").pop().toLowerCase();0==a.indexOf(b+"/")?f(l,g,e):(l=k(l),c.dirList(b,function(d){d=d.join("\n").toLowerCase().split("\n");var k=l.index||0;do{var m=l.base+(k?"-"+k:"")+(l.size?"-"+l.size:"")+"."+
l.ext;k++}while(0<=d.indexOf(m));c.copyLocal(a,b+"/"+m,function(a){a?f(a.split("/").pop(),g,e):(console.error("unable to save "+b+m),e(""))})},{names:[l.base+"*."+l.ext],filter:1,recursive:!1}))}else console.error("unable access to file "+a),e("")})};c.getLocalJSON(b+"/hashes.json",d,d)},moveFileClean:function(a,b,e){var d=c.cleanURI(a.split("/").pop()),f=b+"/"+d;c.copyLocal(a,f,function(){e(f)})},cleanURI:function(a){a=decodeURI(a).replace(/(^\-+|[^a-zA-Z0-9\/_.| -]+|\-+$)/g,"").toLowerCase().replace(/[\/_| -]+/g,
"-");return encodeURI(a)},moveFile:function(a,b,c){return this.moveFileClean(a,b,c)},getLocalJSON:function(a,b,e){c.loadLocalFile(a,function(c){if(c)try{var d=JSON.parse(c)}catch(g){console.error(Error(g.message+(g.line?" at line "+g.line:"")+" in file "+a,a));e&&e(null);return}b?b(d):console.warn("No callback_data function passed for the getLocalJSON:",a)})}},c=window.Bridge=k(window.Bridge||{},t);t=0;var v=[];c.bind("close",function(){function a(a){0<=a&&(v[a]=0);for(a=0;a<v.length;a++)if(v[a])return;
c.quit()}v.forEach(function(b,c){if(b){try{b(function(){d&&clearTimeout(d);a(c)})}catch(f){console.error(f),a(c)}var d=setTimeout(function(){a(c)},1E3)}});a(-1)});q()||(c.isDev=!0,c.isValid=function(){return!0});var z=setInterval(function(){c.isValid()&&(clearInterval(z),m(function(){c.emitOnReady()}))},100)})();
