var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.owns=function(d,f){return Object.prototype.hasOwnProperty.call(d,f)};$jscomp.assign="function"==typeof Object.assign?Object.assign:function(d,f){for(var g=1;g<arguments.length;g++){var b=arguments[g];if(b)for(var h in b)$jscomp.owns(b,h)&&(d[h]=b[h])}return d};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(d,f,g){d!=Array.prototype&&d!=Object.prototype&&(d[f]=g.value)};$jscomp.getGlobal=function(d){return"undefined"!=typeof window&&window===d?d:"undefined"!=typeof global&&null!=global?global:d};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(d,f,g,b){if(f){g=$jscomp.global;d=d.split(".");for(b=0;b<d.length-1;b++){var h=d[b];h in g||(g[h]={});g=g[h]}d=d[d.length-1];b=g[d];f=f(b);f!=b&&null!=f&&$jscomp.defineProperty(g,d,{configurable:!0,writable:!0,value:f})}};$jscomp.polyfill("Object.assign",function(d){return d||$jscomp.assign},"es6","es3");
window.mbrServer=function(){var d,f={email:"",token:""},g=function(a,e){var c=$.Deferred();if("function"==typeof this.then){var k=this;this.always(function(){var b="resolved"==this.state();if("any"==k.condition||"done"==k.condition&&b||"fail"==k.condition&&!b)a(c),e||c.resolve()})}else a(c),e||c.resolve();return c},b=function(a,e,c){return g.call(this,function(k){if("get"==a.toLowerCase()&&c){var b=jQuery.param(c);b&&(e+=(0>e.indexOf("?")?"?":"&")+b);c=null}Bridge.http("https://my.mobirise.com/api/"+
e,{method:a,headers:{"X-App":Bridge.appName+"/"+Bridge.version,Cookie:"token="+f.token},data:c?JSON.stringify(c):"",success:function(a){try{a=JSON.parse(a)}catch(l){k.reject("Incorrect server response.",20,a);console.error(l,a);return}a.error?k.reject(a.response||"",a.error):(k.resolve(a.response||{}),jQuery.each(a.events||[],function(a,c){h.trigger(a,c)}))},error:function(a){k.reject(a,1)}})},!0)};var h={listen:function(a,e){return arguments.length?g.call(this,function(){"on"==a.toLowerCase()?d=
setInterval(function(){b.call({},"get","events")},1E3*(e||5)):d&&(clearInterval(d),d=null)}):d?"on":"off"},post:function(a,e){return b.call(this,"post",a,e)},get:function(a){return b.call(this,"get",a)},put:function(a,e){return b.call(this,"put",a,e)},delete:function(a){return b.call(this,"delete",a)},download:function(a,e){return g.call(this,function(c){Bridge.download3(a,{callback:function(a){a?c.resolve(a):c.reject("Could not download the file.",21)},headers:{"X-App":Bridge.appName+"/"+Bridge.version,
Cookie:"token="+f.token},progress:e})},!0)},signup:function(a){return b.call(this,"post","signup",{email:a}).done(function(e){f.email=a;f.token=""})},signin:function(a,e){return b.call(this,"post","signin",{email:a,password:e}).done(function(c){f.email=a;f.token=c.token})},signinWith:function(){function a(e,c){setTimeout(function(){b.call({},"get",e).done(function(b){b.pending?a(e,c):(f.email=b&&b.profile&&b.profile.email,f.token=b&&b.token,c.resolve(b))}).fail(c.reject)},2E3)}return function(e){return g.call(this,
function(c){b.call({},"post","signin",{service:e}).done(function(b){Bridge.openUrl(b.OAuthURL);a("oauth2/states/"+b.state.id,c)}).fail(c.reject)},!0)}}(),getServiceToken:function(){function a(e,c){setTimeout(function(){b.call({},"get",e).done(function(b){b.pending?a(e,c):c.resolve(b)}).fail(c.reject)},2E3)}return function(e,c){return g.call(this,function(d){b.call({},"post","oauth2/states",{service:e||"instagram",response_type:"SERVICE_ACCESS_TOKEN"}).done(function(b){c&&c.additionalScope&&(b.OAuthURL=
b.OAuthURL.replace(/&scope=[^&]+/,"$&,"+c.additionalScope.join(",")));Bridge.openUrl(b.OAuthURL);a("oauth2/states/"+b.state.id,d)}).fail(d.reject)},!0)}}(),signout:function(){return b.call(this,"post","signout").done(function(){f.email="";f.token=""})},lostpassword:function(a){return b.call(this,"post","lostpassword",{email:a})},profile:function(a,e){if(arguments.length){var c={};"object"==typeof a?c=a:c[a]=e;return g.call(this,function(){jQuery.extend(f,c)})}return b.call(this,"get","profile")},
url:function(a){return b.call(this,"post","auth",{target:a||""}).then(function(a){return a.authURL})},jwt:function(){var a={},e=function(b){return!(a[b]&&a[b].value)||Date.now()>=a[b].expiryTime};return function(c){c=void 0===c?{}:c;var d=void 0===c.target?"https://mobirisesite.com":c.target;return c.refreshToken||e(d)?b.call(this,"post","auth",{target:d}).then(function(b){a[d]={expiryTime:Date.now()+1E3*(b.expires_in-30)};return a[d].value=b.access_token}):jQuery.when(a[d].value)}}(),sendMessage:function(a,
e){return b.call(this,"post","users/"+a+"/messages",{text:e})},activate:function(a){return b.call(this,"post","activate",{coupon:a})},addons:function(a,e){return b.call(this,"get","addons",a||e?Object.assign({},a||{},e||{}):!1)},licenses:function(a,e){return b.call(this,"get","my/purchases?ver=2")}};jQuery.each(["on","one","trigger","off"],function(a,b){var c=jQuery(window);h[b]=function(){var a=arguments;a.length?a[0]+=".mbrServer":(a[0]=".mbrServer",a.length=1);return g.call(this,function(){c[b].apply(c,
a)})}});return h}();
