var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(d,k,l){d instanceof String&&(d=String(d));for(var m=d.length,n=0;n<m;n++){var h=d[n];if(k.call(l,h,n,d))return{i:n,v:h}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(d,k,l){d!=Array.prototype&&d!=Object.prototype&&(d[k]=l.value)};$jscomp.getGlobal=function(d){return"undefined"!=typeof window&&window===d?d:"undefined"!=typeof global&&null!=global?global:d};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(d,k,l,m){if(k){l=$jscomp.global;d=d.split(".");for(m=0;m<d.length-1;m++){var n=d[m];n in l||(l[n]={});l=l[n]}d=d[d.length-1];m=l[d];k=k(m);k!=m&&null!=k&&$jscomp.defineProperty(l,d,{configurable:!0,writable:!0,value:k})}};$jscomp.polyfill("Array.prototype.find",function(d){return d?d:function(d,l){return $jscomp.findInternal(this,d,l).v}},"es6","es3");
defineM("clarus",function(d,k){function l(a,b,c){var f=this;b.find(".images > ul > li:eq("+c.find(".carousel-inner > .active").index()+")").click();b.find(".image-tabs li:not(.add-item)").each(function(a){(a=f._params.slides[a])&&a.playVideo&&(a=B(a.videoUrl))&&d(this).css("background-image","url("+C(a)+")")})}function m(a,b,c){var f=d("#edit-component-params").find(".image-tabs li.active");if(-1<f.index()){var e=this._params.slides[f.index()];e.playVideo?(e=B(e.videoUrl))&&f.css("background-image",
"url("+C(e)+")"):0===e.image.indexOf("file:")?f.css("background-image",'url("'+e.image+'")'):(e=e.image,e=/file:/g.test(e)?e:Bridge.path2app("web/app/builder/"+e),f.css("background-image",'url("'+e+'")'))}if(void 0===b)a.find(".mbr-slider > .boxed-slider").css({"padding-top":40*this._params.paddingTop+"px","padding-bottom":40*this._params.paddingBottom+"px"});else switch(b){case "paddingTop":a.find(".mbr-slider > .boxed-slider").css("padding-top",40*c+"px");break;case "paddingBottom":a.find(".mbr-slider > .boxed-slider").css("padding-bottom",
40*c+"px");break;case "fullScreen":c?a.find(".mbr-slider div:eq(0)").removeAttr("style"):a.find(".mbr-slider > .boxed-slider").css({"padding-top":40*this._params.paddingTop+"px","padding-bottom":40*this._params.paddingBottom+"px"})}}function n(a){this._plugins=function(a,c,d){return d.split(",").filter(function(b){return 0>a.indexOf(b)}).concat(c?a:[]).join(",")}(["YTPlayer","SliderVideo"],!!a.find('[data-bg-video-slide^="http"]').length,this._plugins);a.find(".mbr-slider > .boxed-slider").css({"padding-top":40*
this._params.paddingTop+"px","padding-bottom":40*this._params.paddingBottom+"px"});a.find("[data-interval]").attr("data-interval",this._params.autoplay?1E3*this._params.timeout:"false");[".carousel-indicators > li",".carousel-inner > div"].forEach(function(b){a.find(b).removeClass("active").eq(0).addClass("active")})}function h(a,b){for(var c in b)parseInt(c)+1>a&&d(b[c]).css("display","none"),parseInt(c)+1<=a&&d(b[c]).css("display","block")}function u(a,b){for(var c in b)parseInt(c)%3+1>a&&d(b[c]).css("display",
"none"),parseInt(c)%3+1<=a&&d(b[c]).css("display","block")}function q(a,b,c){"undefined"===typeof b?a.find(".mbr-section").css({"padding-top":50*this._params.paddingTop+"px","padding-bottom":50*this._params.paddingBottom+"px"}):("paddingTop"==b||"paddingBottom"==b)&&a.find(".mbr-section").css("paddingTop"==b?"padding-top":"padding-bottom","paddingTop"==b?50*c:50*c+"px")}function r(a,b,c){"undefined"===typeof b?a.find("#contact-info").css({"padding-top":50*this._params.paddingTop+"px","padding-bottom":50*
this._params.paddingBottom+"px"}):("paddingTop"==b||"paddingBottom"==b)&&a.find("#contact-info").css("paddingTop"==b?"padding-top":"padding-bottom","paddingTop"==b?50*c:50*c+"px")}function v(a,b,c){if(void 0===b||"collapsed"==b)a=a.context.defaultView,a.$(a).trigger("resize");if(void 0===b||0<=["bgColor","fontSize","fontName","fontColor","fontHoverColor"].indexOf(b))p(this._styles,".navbar-toggler","color",this._params.fontColor),p(this._styles,".close-icon::before, .close-icon::after","background-color",
this._params.fontColor),p(this._styles,".link, .dropdown-item","color",this._params.fontColor),this._params.fontName.url&&p(this._styles,".link, .dropdown-item","googleLink",this._params.fontName.url),this._params.fontName.css&&p(this._styles,".link, .dropdown-item","font-family",this._params.fontName.css),p(this._styles,".link","font-size",this._params.fontSize+"rem"),p(this._styles,".dropdown-item, .nav-dropdown-sm .link","font-size",(1.083*this._params.fontSize).toFixed(3)+"rem"),p(this._styles,
".link:hover, .dropdown-item:hover, .link:focus, .dropdown-item:focus","color",this._params.fontHoverColor),p(this._styles,'.link[aria-expanded="true"], .dropdown-menu',"background",x(this._params.bgColor,"10%")),p(this._styles,".nav-dropdown-sm .link:focus, .nav-dropdown-sm .link:hover, .nav-dropdown-sm .dropdown-item:focus, .nav-dropdown-sm .dropdown-item:hover","background",x(this._params.bgColor,"3%")+"!important"),p(this._styles,'.navbar, .nav-dropdown-sm, .nav-dropdown-sm .link[aria-expanded="true"], .nav-dropdown-sm .dropdown-menu',
"background",this._params.bgColor),p(this._styles,".bg-color.transparent .link",{color:this._params.fontColor,transition:"none"}),p(this._styles,".bg-color.transparent.opened .link","transition","color .2s ease-in-out"),p(this._styles,".bg-color.transparent.opened .link:hover, .bg-color.transparent.opened .link:focus","color",this._params.fontHoverColor),p(this._styles,'.link[aria-expanded="true"], .dropdown-item[aria-expanded="true"]',"color",this._params.fontHoverColor+"!important"),k.Core.renderComponentsStyles()}
function w(a,b){this._params.hideButtons?(a.find(".hide-buttons").removeClass("hide-buttons"),a.find("a[data-button]").parent().remove()):a.find("a[data-button]").removeAttr("data-button");this._params.logo&&a.find(".navbar-brand .navbar-logo a").addClass("navbar-logo").unwrap();this._params.showBrand&&a.find(".navbar-caption").unwrap()}function y(a,b,c){switch(b){case void 0:a.find(".mbr-section").css({"padding-top":1.5*this._params.paddingTop+"rem","padding-bottom":1.5*this._params.paddingBottom+
"rem"});a.find(".mbr-section .mbr-gallery-item").css("padding",this._params.spacing+"rem");break;case "paddingTop":a.find(".mbr-section").css("padding-top",1.5*c+"rem");break;case "spacing":a.find(".mbr-section .mbr-gallery-item").css("padding",c+"rem");break;case "paddingBottom":a.find(".mbr-section").css("padding-bottom",1.5*c+"rem")}}function z(a,b,c){a=d(a.target).parents(".mbr-gallery-item:eq(0)");a.length&&b.find(".images > ul > li:eq("+a.index()+")").click()}function A(a){a.find(".mbr-gallery-item>div").attr("data-toggle",
"modal");a.find(".mbr-section").css({"padding-top":1.5*this._params.paddingTop+"rem","padding-bottom":1.5*this._params.paddingBottom+"rem"});a.find(".mbr-gallery-item").css({padding:this._params.spacing+"rem"})}var t=document.querySelector("head"),D=document.createElement("script");D.src="app/includes/migrate/padding-components.js";t.appendChild(D);t=k.theme.name;"use strict";if("clarus"===t){var B=function(a){return"false"==a?!1:(a=/(?:\?v=|\/embed\/|\.be\/)([-a-z0-9_]+)/i.exec(a)||/^([-a-z0-9_]+)$/i.exec(a))?
a[1]:!1},C=function(a,b){return"http://img.youtube.com/vi/"+a+"/"+(b||"")+"default.jpg"};d(document).on("sortstop",function(a){a=d(a.target).closest("#edit-component-params").attr("data-component-id");k.Core.$body.find('.app-component[data-app-component-id="'+a+'"] .mbr-slider').trigger("change.cards")});var x=function(a){return a};k.iwindow.less&&function(a){x=function(b,c){return a.functions.functionRegistry._data.darken(new a.tree.Color(b.substr(1)),{value:parseInt(c)}).toCSS()}}(k.iwindow.less);
var p=function(a,b,c,d){a[b]||(a[b]={});if("object"==typeof c)for(var e in c)a[b][e]=c[e];else a[b][c]=d};t=["OVERVIEW","FEATURES","HELP","DOWNLOAD","Tutorials"];k.Core.addFilter("cleanHTMLplease",function(a){a.find(".navbar-dropdown .nav").attr("id","exCollapsingNavbar");return a});var E={accordion1:{_onParamsChange:function(a,b,c){q.call(this,a,b,c);if("undefined"===typeof b||"columns"==b){"2"==this._params.columns&&a.find(".mbr-cards-col").each(function(){d(this).attr("class","mbr-cards-col col-xs-12 col-sm-6")});
"1"==this._params.columns&&a.find(".mbr-cards-col").each(function(){d(this).attr("class","mbr-cards-col col-xs-12")});c=parseInt(this._params.columns);var f=a.find(".mbr-cards-col");h(c,f)}if("undefined"===typeof b||"tabsLeft"==b||"tabsRight"==b){b=parseInt(this._params.tabsLeft);c=parseInt(this._params.tabsRight);f=a.find("#accordionLeft").children();a=a.find("#accordionRight").children();for(var e in f)parseInt(e)+1>b&&d(f[e]).css("display","none"),parseInt(e)+1<=b&&d(f[e]).css("display","block");
for(e in a)parseInt(e)+1>c&&d(a[e]).css("display","none"),parseInt(e)+1<=c&&d(a[e]).css("display","block")}},_publishFilter:function(a,b){a.find(".mbr-section").css({"padding-top":50*this._params.paddingTop+"px","padding-bottom":50*this._params.paddingBottom+"px"});"2"==this._params.columns&&a.find(".mbr-cards-col").each(function(){d(this).attr("class","mbr-cards-col col-xs-12 col-sm-6")});"1"==this._params.columns&&a.find(".mbr-cards-col").each(function(){d(this).attr("class","mbr-cards-col col-xs-12")});
b=parseInt(this._params.columns);var c=a.find(".mbr-cards-col");h(b,c);b=parseInt(this._params.tabsLeft);c=parseInt(this._params.tabsRight);var f=a.find("#accordionLeft").children();a=a.find("#accordionRight").children();for(var e in f)parseInt(e)+1>b&&d(f[e]).css("display","none"),parseInt(e)+1<=b&&d(f[e]).css("display","block");for(e in a)parseInt(e)+1>c&&d(a[e]).css("display","none"),parseInt(e)+1<=c&&d(a[e]).css("display","block")}},accordion2:{_onParamsChange:function(a,b,c){q.call(this,a,b,
c);if("undefined"===typeof b||"columns"==b){"3"==this._params.columns&&a.find(".mbr-cards-col").each(function(){d(this).attr("class","mbr-cards-col col-xs-12 col-lg-4")});"2"==this._params.columns&&a.find(".mbr-cards-col").each(function(){d(this).attr("class","mbr-cards-col col-xs-12 col-sm-6")});"1"==this._params.columns&&a.find(".mbr-cards-col").each(function(){d(this).attr("class","mbr-cards-col col-xs-12")});c=parseInt(this._params.columns);var f=a.find(".mbr-cards-col");h(c,f)}if("undefined"===
typeof b||"tabsLeft"==b||"tabsRight"==b){b=parseInt(this._params.tabsLeft);c=parseInt(this._params.tabsCenter);f=parseInt(this._params.tabsRight);var e=a.find("#accordionLeft").children(),k=a.find("#accordionCenter").children();a=a.find("#accordionRight").children();for(var g in e)parseInt(g)+1>b&&d(e[g]).css("display","none"),parseInt(g)+1<=b&&d(e[g]).css("display","block");for(g in k)parseInt(g)+1>c&&d(k[g]).css("display","none"),parseInt(g)+1<=c&&d(k[g]).css("display","block");for(g in a)parseInt(g)+
1>f&&d(a[g]).css("display","none"),parseInt(g)+1<=f&&d(a[g]).css("display","block")}},_publishFilter:function(a,b){a.find(".mbr-section").css({"padding-top":50*this._params.paddingTop+"px","padding-bottom":50*this._params.paddingBottom+"px"});"3"==this._params.columns&&a.find(".mbr-cards-col").each(function(){d(this).attr("class","mbr-cards-col col-xs-12 col-lg-4")});"2"==this._params.columns&&a.find(".mbr-cards-col").each(function(){d(this).attr("class","mbr-cards-col col-xs-12 col-sm-6")});"1"==
this._params.columns&&a.find(".mbr-cards-col").each(function(){d(this).attr("class","mbr-cards-col col-xs-12")});b=parseInt(this._params.columns);var c=a.find(".mbr-cards-col");h(b,c);b=parseInt(this._params.tabsLeft);c=parseInt(this._params.tabsCenter);var f=parseInt(this._params.tabsRight),e=a.find("#accordionLeft").children(),k=a.find("#accordionCenter").children();a=a.find("#accordionRight").children();for(var g in e)parseInt(g)+1>b&&d(e[g]).css("display","none"),parseInt(g)+1<=b&&d(e[g]).css("display",
"block");for(g in k)parseInt(g)+1>c&&d(k[g]).css("display","none"),parseInt(g)+1<=c&&d(k[g]).css("display","block");for(g in a)parseInt(g)+1>f&&d(a[g]).css("display","none"),parseInt(g)+1<=f&&d(a[g]).css("display","block")}},content1:{_onParamsChange:function(a,b,c){r.call(this,a,b,c);if("undefined"===typeof b||"columns"==b)b=parseInt(this._params.columns),a=a.find(".mbr-cards-col"),h(b,a)},_publishFilter:function(a,b){a.find("#contact-info").css({"padding-top":50*this._params.paddingTop+"px","padding-bottom":50*
this._params.paddingBottom+"px"});b=parseInt(this._params.columns);a=a.find(".mbr-cards-col");h(b,a)}},content2:{_onParamsChange:function(a,b,c){r.call(this,a,b,c);if("undefined"===typeof b||"columns"==b)b=parseInt(this._params.columns),a=a.find(".mbr-cards-col"),h(b,a)},_publishFilter:function(a,b){a.find("#contact-info").css({"padding-top":50*this._params.paddingTop+"px","padding-bottom":50*this._params.paddingBottom+"px"});b=parseInt(this._params.columns);a=a.find(".mbr-cards-col");h(b,a)}},content3:{_onParamsChange:function(a,
b,c){r.call(this,a,b,c);if("undefined"===typeof b||"columns"==b)"2"==this._params.columns&&a.find(".mbr-cards-col").each(function(){d(this).attr("class","mbr-cards-col col-xs-12 col-sm-6")}),"3"==this._params.columns&&a.find(".mbr-cards-col").each(function(){d(this).attr("class","mbr-cards-col col-lg-4 col-md-4 col-sm-12 col-xs-12")}),b=parseInt(this._params.columns),a=a.find(".mbr-cards-col"),u(b,a)},_publishFilter:function(a,b){a.find("#contact-info").css({"padding-top":50*this._params.paddingTop+
"px","padding-bottom":50*this._params.paddingBottom+"px"});"2"==this._params.columns&&a.find(".mbr-cards-col").each(function(){d(this).attr("class","mbr-cards-col col-xs-12 col-sm-6")});"3"==this._params.columns&&a.find(".mbr-cards-col").each(function(){d(this).attr("class","mbr-cards-col col-lg-4 col-md-4 col-sm-12 col-xs-12")});b=parseInt(this._params.columns);a=a.find(".mbr-cards-col");u(b,a)}},content4:{_onParamsChange:function(a,b,c){r.call(this,a,b,c);if("undefined"===typeof b||"columns"==b)"2"==
this._params.columns&&a.find(".mbr-cards-col").each(function(){d(this).attr("class","mbr-cards-col col-xs-12 col-sm-6")}),"3"==this._params.columns&&a.find(".mbr-cards-col").each(function(){d(this).attr("class","mbr-cards-col col-lg-4 col-md-4 col-sm-12 col-xs-12")}),b=parseInt(this._params.columns),a=a.find(".mbr-cards-col"),u(b,a)},_publishFilter:function(a,b){a.find("#contact-info").css({"padding-top":50*this._params.paddingTop+"px","padding-bottom":50*this._params.paddingBottom+"px"});"2"==this._params.columns&&
a.find(".mbr-cards-col").each(function(){d(this).attr("class","mbr-cards-col col-xs-12 col-sm-6")});"3"==this._params.columns&&a.find(".mbr-cards-col").each(function(){d(this).attr("class","mbr-cards-col col-lg-4 col-md-4 col-sm-12 col-xs-12")});b=parseInt(this._params.columns);a=a.find(".mbr-cards-col");u(b,a)}},content5:{_onParamsChange:function(a,b,c){r.call(this,a,b,c);if("undefined"===typeof b||"columns"==b){c=parseInt(this._params.columns);var f=a.find(".mbr-cards-col"),e;for(e in f)parseInt(e)%
4+1>c&&d(f[e]).css("display","none"),parseInt(e)%4+1<=c&&d(f[e]).css("display","block")}if("undefined"===typeof b||"showHover"==b)0==this._params.showHover?a.find(".item-layer").each(function(){d(this).css("display","none")}):a.find(".item-layer").each(function(){d(this).css("display","block")})},_publishFilter:function(a,b){a.find("#contact-info").css({"padding-top":50*this._params.paddingTop+"px","padding-bottom":50*this._params.paddingBottom+"px"});b=parseInt(this._params.columns);a=a.find(".mbr-cards-col");
for(var c in a)parseInt(c)%4+1>b&&d(a[c]).css("display","none"),parseInt(c)%4+1<=b&&d(a[c]).css("display","block")}},content6:{_onParamsChange:function(a,b,c){q.call(this,a,b,c);if("undefined"===typeof b||"columns"==b)b=parseInt(this._params.columns),a=a.find(".mbr-cards-col"),h(b,a)},_publishFilter:function(a,b){a.find(".mbr-section").css({"padding-top":50*this._params.paddingTop+"px","padding-bottom":50*this._params.paddingBottom+"px"});b=parseInt(this._params.columns);a=a.find(".mbr-cards-col");
h(b,a)}},content7:{_onParamsChange:function(a,b,c){q.call(this,a,b,c);if("undefined"===typeof b||"columns"==b)b=parseInt(this._params.columns),a=a.find(".mbr-cards-col"),h(b,a)},_publishFilter:function(a,b){a.find(".mbr-section").css({"padding-top":50*this._params.paddingTop+"px","padding-bottom":50*this._params.paddingBottom+"px"});b=parseInt(this._params.columns);a=a.find(".mbr-cards-col");h(b,a)}},content8:{_onParamsChange:function(a,b,c){q.call(this,a,b,c);if("undefined"===typeof b||"columns"==
b)b=parseInt(this._params.columns),a=a.find(".mbr-cards-col"),h(b,a)},_publishFilter:function(a,b){a.find(".mbr-section").css({"padding-top":50*this._params.paddingTop+"px","padding-bottom":50*this._params.paddingBottom+"px"});b=parseInt(this._params.columns);a=a.find(".mbr-cards-col");h(b,a)}},content9:{_onParamsChange:function(a,b,c){q.call(this,a,b,c);if("undefined"===typeof b||"columns"==b){"2"==this._params.columns&&a.find(".mbr-cards-col").each(function(){d(this).attr("class","mbr-cards-col col-xs-12 col-sm-6")});
"3"==this._params.columns&&a.find(".mbr-cards-col").each(function(){d(this).attr("class","mbr-cards-col col-lg-4 col-md-4 col-sm-12 col-xs-12")});c=parseInt(this._params.columns);var f=a.find(".mbr-cards-col");h(c,f)}if("undefined"===typeof b||"showHover"==b)0==this._params.showHover?a.find(".item-layer").each(function(){d(this).css("display","none")}):a.find(".item-layer").each(function(){d(this).css("display","block")})},_publishFilter:function(a,b){a.find(".mbr-section").css({"padding-top":50*
this._params.paddingTop+"px","padding-bottom":50*this._params.paddingBottom+"px"});"2"==this._params.columns&&a.find(".mbr-cards-col").each(function(){d(this).attr("class","mbr-cards-col col-xs-12 col-sm-6")});"3"==this._params.columns&&a.find(".mbr-cards-col").each(function(){d(this).attr("class","mbr-cards-col col-lg-4 col-md-4 col-sm-12 col-xs-12")});b=parseInt(this._params.columns);a=a.find(".mbr-cards-col");h(b,a)}},content10:{_onParamsChange:function(a,b,c){q.call(this,a,b,c);if("undefined"===
typeof b||"columns"==b)b=parseInt(this._params.columns),a=a.find(".mbr-cards-col"),h(b,a)},_publishFilter:function(a,b){a.find(".mbr-section").css({"padding-top":50*this._params.paddingTop+"px","padding-bottom":50*this._params.paddingBottom+"px"});b=parseInt(this._params.columns);a=a.find(".mbr-cards-col");h(b,a)}},content11:{_onParamsChange:function(a,b,c){q.call(this,a,b,c);if("undefined"===typeof b||"columns"==b)b=parseInt(this._params.columns),a=a.find(".mbr-cards-col"),h(b,a)},_publishFilter:function(a,
b){a.find(".mbr-section").css({"padding-top":50*this._params.paddingTop+"px","padding-bottom":50*this._params.paddingBottom+"px"});b=parseInt(this._params.columns);a=a.find(".mbr-cards-col");h(b,a)}},content12:{_onParamsChange:function(a,b,c){q.call(this,a,b,c);if("undefined"===typeof b||"columns"==b)b=parseInt(this._params.columns),a=a.find(".mbr-cards-col"),h(b,a)},_publishFilter:function(a,b){a.find(".mbr-section").css({"padding-top":50*this._params.paddingTop+"px","padding-bottom":50*this._params.paddingBottom+
"px"});b=parseInt(this._params.columns);a=a.find(".mbr-cards-col");h(b,a)}},content13:{_onParamsChange:function(a,b,c){q.call(this,a,b,c);if("undefined"===typeof b||"columns"==b){"2"==this._params.columns&&a.find(".mbr-cards-col").each(function(){d(this).attr("class","mbr-cards-col col-xs-12 col-sm-6")});"3"==this._params.columns&&a.find(".mbr-cards-col").each(function(){d(this).attr("class","mbr-cards-col col-lg-4 col-md-4 col-sm-12 col-xs-12")});"4"==this._params.columns&&a.find(".mbr-cards-col").each(function(){d(this).attr("class",
"mbr-cards-col col-xs-12 col-sm-6 col-md-3")});c=parseInt(this._params.columns);var f=a.find(".mbr-cards-col");h(c,f)}if("undefined"===typeof b||"showHover"==b)0==this._params.showHover?a.find(".item-layer").each(function(){d(this).css("display","none")}):a.find(".item-layer").each(function(){d(this).css("display","block")})},_publishFilter:function(a,b){a.find(".mbr-section").css({"padding-top":50*this._params.paddingTop+"px","padding-bottom":50*this._params.paddingBottom+"px"});"2"==this._params.columns&&
a.find(".mbr-cards-col").each(function(){d(this).attr("class","mbr-cards-col col-xs-12 col-sm-6")});"3"==this._params.columns&&a.find(".mbr-cards-col").each(function(){d(this).attr("class","mbr-cards-col col-lg-4 col-md-4 col-sm-12 col-xs-12")});"4"==this._params.columns&&a.find(".mbr-cards-col").each(function(){d(this).attr("class","mbr-cards-col col-xs-12 col-sm-6 col-md-3")});b=parseInt(this._params.columns);a=a.find(".mbr-cards-col");h(b,a)}},content14:{_onParamsChange:function(a,b,c){r.call(this,
a,b,c);if("undefined"===typeof b||"columns"==b)b=parseInt(this._params.columns),a=a.find(".mbr-cards-col"),h(b,a)},_publishFilter:function(a,b){a.find("#contact-info").css({"padding-top":50*this._params.paddingTop+"px","padding-bottom":50*this._params.paddingBottom+"px"});b=parseInt(this._params.columns);a=a.find(".mbr-cards-col");h(b,a)}},gallery1:{_onParamsChange:function(a,b,c){y.call(this,a,b,c)},_onParamsShow:function(a,b,c){z.call(this,a,b,c)},_publishFilter:function(a){A.call(this,a)}},gallery2:{_onParamsChange:function(a,
b,c){y.call(this,a,b,c)},_onParamsShow:function(a,b,c){z.call(this,a,b,c)},_publishFilter:function(a){A.call(this,a)}},gallery3:{_onParamsChange:function(a,b,c){y.call(this,a,b,c)},_onParamsShow:function(a,b,c){z.call(this,a,b,c)},_publishFilter:function(a){A.call(this,a)}},header1:{_onParamsShow:function(a,b,c){l.call(this,a,b,c)},_onParamsChange:function(a,b,c){m.call(this,a,b,c)},_publishFilter:function(a){n.call(this,a)}},header2:{_onParamsShow:function(a,b,c){l.call(this,a,b,c)},_onParamsChange:function(a,
b,c){m.call(this,a,b,c)},_publishFilter:function(a){n.call(this,a)}},header3:{_onParamsShow:function(a,b,c){l.call(this,a,b,c)},_onParamsChange:function(a,b,c){m.call(this,a,b,c)},_publishFilter:function(a){n.call(this,a)}},header5:{_onParamsChange:function(a,b,c){r.call(this,a,b,c);if("undefined"===typeof b||"columns"==b)b=parseInt(this._params.columns),a=a.find(".mbr-cards-col"),h(b,a)},_publishFilter:function(a,b){a.find("#contact-info").css({"padding-top":50*this._params.paddingTop+"px","padding-bottom":50*
this._params.paddingBottom+"px"});b=parseInt(this._params.columns);a=a.find(".mbr-cards-col");h(b,a)}},menu1:{_onParamsChange:function(a,b,c){v.call(this,a,b,c)},_publishFilter:function(a,b){w.call(this,a,b)},items:k.arrayToDropdownMenu(t)},menu2:{_onParamsChange:function(a,b,c){v.call(this,a,b,c)},_publishFilter:function(a,b){w.call(this,a,b)},items:k.arrayToDropdownMenu(t)},menu3:{_onParamsChange:function(a,b,c){v.call(this,a,b,c)},_publishFilter:function(a,b){w.call(this,a,b)},items:k.arrayToDropdownMenu(t)},
menu4:{_onParamsChange:function(a,b,c){v.call(this,a,b,c)},_publishFilter:function(a,b){w.call(this,a,b)},items:k.arrayToDropdownMenu(t)},"pricing-table1":{_onParamsChange:function(a,b,c){r.call(this,a,b,c);if("undefined"===typeof b||"columns"==b)"2"==this._params.columns&&a.find(".mbr-cards-col").each(function(){d(this).attr("class","mbr-cards-col col-xs-12 col-sm-6")}),"3"==this._params.columns&&a.find(".mbr-cards-col").each(function(){d(this).attr("class","mbr-cards-col col-lg-4 col-xs-12")}),
b=parseInt(this._params.columns),a=a.find(".mbr-cards-col"),u(b,a)},_publishFilter:function(a,b){a.find("#contact-info").css({"padding-top":50*this._params.paddingTop+"px","padding-bottom":50*this._params.paddingBottom+"px"});"2"==this._params.columns&&a.find(".mbr-cards-col").each(function(){d(this).attr("class","mbr-cards-col col-xs-12 col-sm-6")});"3"==this._params.columns&&a.find(".mbr-cards-col").each(function(){d(this).attr("class","mbr-cards-col col-lg-4 col-xs-12")});b=parseInt(this._params.columns);
a=a.find(".mbr-cards-col");u(b,a)}},slider1:{_onParamsShow:function(a,b,c){l.call(this,a,b,c)},_onParamsChange:function(a,b,c){m.call(this,a,b,c)},_publishFilter:function(a){n.call(this,a)}},slider2:{_onParamsShow:function(a,b,c){l.call(this,a,b,c)},_onParamsChange:function(a,b,c){m.call(this,a,b,c)},_publishFilter:function(a){n.call(this,a)}},slider3:{_onParamsShow:function(a,b,c){l.call(this,a,b,c)},_onParamsChange:function(a,b,c){m.call(this,a,b,c)},_publishFilter:function(a){n.call(this,a)}},
slider4:{_onParamsShow:function(a,b,c){l.call(this,a,b,c)},_onParamsChange:function(a,b,c){m.call(this,a,b,c)},_publishFilter:function(a){n.call(this,a)}},slider5:{_onMediaClick:function(a,b){a.stopPropagation();a.preventDefault();var c=d(a.target).closest(".carousel-item"),f=c.index(),e=b["this"],h=d.extend(!0,{},e.media);k.Core.showMediaImageDialog(h,function(g){e.media=g;k.Core.updateGlobalComponents(b._id);0<d(a.target).parents(".clonedCol").length?(g=d(a.target).parents(".clonedCol").attr("data-cloned-index"),
d(a.target).attr("src",d(a.target).parents(".carousel-inner").find(".carousel-item").eq(g).find("img").attr("src"))):c.closest(".carousel-inner").find("[data-cloned-index ="+f+"]").find("img").attr("src",g.image.src)})},_onParamsShow:function(a,b,c){b.find(".images > ul > li:eq("+c.find(".carousel-inner > .active").index()+")").click();var f="";b.find(".image-tabs li:not(.add-item)").each(function(a){f=c.find(".carousel-item").eq(a).find("img").attr("src");d(this).css("background-image","url("+f+
")")})},_onParamsChange:function(a,b,c){if(void 0===b)a.find(".mbr-slider").css({"padding-top":40*this._params.paddingTop+"px","padding-bottom":40*this._params.paddingBottom+"px"}),[".carousel-indicators > li",".carousel-inner > div"].forEach(function(b){a.find(b).removeClass("active").eq(0).addClass("active")});else switch(b){case "paddingTop":a.find(".mbr-slider").css("padding-top",40*c+"px");break;case "paddingBottom":a.find(".mbr-slider").css("padding-bottom",40*c+"px");break;case "fullScreen":c&&
a.find(".mbr-slider div:eq(0)").removeAttr("style")}},_publishFilter:function(a){a.find(".mbr-slider").css({"padding-top":40*this._params.paddingTop+"px","padding-bottom":40*this._params.paddingBottom+"px"});a.find("[data-interval]").attr("data-interval",this._params.autoplay?1E3*this._params.timeout:"false");[".carousel-indicators > li",".carousel-inner > div"].forEach(function(b){a.find(b).removeClass("active").eq(0).addClass("active")})}},slider6:{_onParamsShow:function(a,b,c){l.call(this,a,b,
c)},_onParamsChange:function(a,b,c){m.call(this,a,b,c)},_publishFilter:function(a){n.call(this,a)}},social1:{_onParamsChange:function(a,b,c){"undefined"===typeof b&&a.find(".mbr-section").css({"padding-top":30*this._params.paddingTop+"px","padding-bottom":30*this._params.paddingBottom+"px"});"paddingTop"!=b&&"paddingBottom"!=b||a.find(".mbr-section").css("paddingTop"==b?"padding-top":"padding-bottom",30*c+"px")},_publishFilter:function(a){a.find(".social-likes__counter").remove();a.find(".mbr-added").removeClass("mbr-added");
a.find(".mbr-section").css({"padding-top":30*this._params.paddingTop+"px","padding-bottom":30*this._params.paddingBottom+"px"})}}};k.addFilter("loadingComponents",function(a){for(var b in a){var c=a[b],f;for(f in E)b===f&&d.extend(!0,c,E[f]);return a}})}},["jQuery","mbrApp"]);
