var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(c,d,e){c instanceof String&&(c=String(c));for(var f=c.length,g=0;g<f;g++){var h=c[g];if(d.call(e,h,g,c))return{i:g,v:h}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(c,d,e){c!=Array.prototype&&c!=Object.prototype&&(c[d]=e.value)};$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global&&null!=global?global:c};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(c,d,e,f){if(d){e=$jscomp.global;c=c.split(".");for(f=0;f<c.length-1;f++){var g=c[f];g in e||(e[g]={});e=e[g]}c=c[c.length-1];f=e[c];d=d(f);d!=f&&null!=d&&$jscomp.defineProperty(e,c,{configurable:!0,writable:!0,value:d})}};$jscomp.polyfill("Array.prototype.find",function(c){return c?c:function(c,e){return $jscomp.findInternal(this,c,e).v}},"es6","es3");
defineM("purity",function(c,d){function e(c,d,a){"undefined"===typeof d&&c.find(".mbr-section").css({"padding-top":1.5*this._params.paddingTop+"rem","padding-bottom":1.5*this._params.paddingBottom+"rem"});"paddingTop"!==d&&"paddingBottom"!==d||c.find(".mbr-section").css("paddingTop"===d?"padding-top":"padding-bottom",1.5*a+"rem")}function f(c){c.find(".mbr-section").css({"padding-top":1.5*this._params.paddingTop+"rem","padding-bottom":1.5*this._params.paddingBottom+"rem"})}var g=document.querySelector("head"),
h=document.createElement("script");h.src="app/includes/migrate/padding-components.js";g.appendChild(h);g=d.theme.name;"use strict";"purity"===g&&function(){var g=function(a){return a};d.iwindow.less&&function(a){g=function(b,c){return a.functions.functionRegistry._data.darken(new a.tree.Color(b.substr(1)),{value:parseInt(c)}).toCSS()}}(d.iwindow.less);d.Core.addFilter("cleanHTMLplease",function(a){a.find(".navbar-dropdown .nav").attr("id","exCollapsingNavbar");return a});var h={contacts3:{_onLoadFromProject:function(a,
b){void 0===this.form&&(this.form=c.extend({},a.form),this.form.action=b.formoidUserID,void 0!==b.alertSuccess&&(this.form.alerts.success=b.alertSuccess),this.form.fields.name.visible=b.showName,this.form.fields.email.visible=b.showEmail,this.form.fields.phone.visible=b.showPhone)}},"dropdown-menu":{items:d.arrayToDropdownMenu(["Overview",{text:"Features",children:["Mobile friendly","Based on Bootstrap",{text:"Trendy blocks",children:"Image/content slider;Contact forms;Image gallery;Mobile menu;Google maps;Social buttons;Google fonts;Video background".split(";")},
"Host anywhere"]},{text:"Help",children:[{text:"Forum",href:"http://forums.mobirise.com/"},"Tutorials","Contact us"]},{text:"Download",btn:"btn-black btn-black-outline"}]),_onParamsChange:function(a,b,c){if(void 0===b||0<=["bgColor","fontSize","fontName","fontColor"].indexOf(b))this._styles=this._styles||{},this._styles[".nav .link, .dropdown-item"]=this._styles[".nav .link, .dropdown-item"]||{},this._styles[".navbar, .dropdown-menu"]=this._styles[".navbar, .dropdown-menu"]||{},this._styles['.dropdown-menu .dropdown-toggle[aria-expanded="true"], .dropdown-menu a:hover, .dropdown-menu a:focus']=
this._styles['.dropdown-menu .dropdown-toggle[aria-expanded="true"], .dropdown-menu a:hover, .dropdown-menu a:focus']||{},this._styles[".navbar-toggler"]=this._styles[".navbar-toggler"]||{},this._styles[".navbar, .dropdown-menu"].background=this._params.bgColor,this._styles['.dropdown-menu .dropdown-toggle[aria-expanded="true"], .dropdown-menu a:hover, .dropdown-menu a:focus'].background=g(this._params.bgColor,"4%"),this._styles[".nav .link, .dropdown-item"]["font-size"]=this._params.fontSize+"em",
this._params.fontName.url&&(this._styles[".nav .link, .dropdown-item"].googleLink=this._params.fontName.url),this._params.fontName.css&&(this._styles[".nav .link, .dropdown-item"]["font-family"]=this._params.fontName.css),this._styles[".nav .link, .dropdown-item"].color=this._params.fontColor,this._styles[".navbar-toggler"].color=this._params.fontColor,d.Core.renderComponentsStyles()},_publishFilter:function(a,b){this._params.hideButtons?(a.find(".hide-buttons").removeClass("hide-buttons"),a.find("a[data-button]").parent().remove()):
a.find("a[data-button]").removeAttr("data-button");this._params.logo&&a.find(".navbar-brand .navbar-logo a").each(function(){c(this).addClass("navbar-logo").unwrap()});this._params.showBrand&&a.find(".navbar-brand > span:not(.navbar-logo) a").each(function(){c(this).unwrap()})}},"dropdown-menu-2btn":{items:d.arrayToDropdownMenu([{text:"Features",children:["Mobile friendly","Based on Bootstrap",{text:"Trendy blocks",children:"Image/content slider;Contact forms;Image gallery;Mobile menu;Google maps;Social buttons;Google fonts;Video background".split(";")},
"Host anywhere"]},"Help",{text:"For Windows",btn:"btn-black btn-black-outline"},{text:"For Mac",btn:"btn-danger"}])},form1:{_onLoadFromProject:function(a,b){void 0===this.form&&(this.form=c.extend({},a.form),this.form.action=b.formoidUserID,void 0!==b.alertSuccess&&(this.form.alerts.success=b.alertSuccess),this.form.fields.name.visible=b.showName,this.form.fields.email.visible=b.showEmail,this.form.fields.phone.visible=b.showPhone)}},form2:{_onLoadFromProject:function(a,b){void 0===this.form&&(this.form=
c.extend({},a.form),this.form.action=b.formoidUserID,void 0!==b.alertSuccess&&(this.form.alerts.success=b.alertSuccess))}},gallery1:{_onParamsChange:function(a,b,c){e.call(this,a,b,c)},_onParamsShow:function(a,b,d){a=c(a.target).parents(".mbr-gallery-item:eq(0)");a.length&&b.find(".images > ul > li:eq("+a.index()+")").click()},_publishFilter:function(a){a.find(".mbr-gallery-item a").attr("data-toggle","modal");f.call(this,a)}},header1:{_publishFilter:function(a,b){var c,d;for(d in b.components){var e=
b.components[d];if(c&&!e._alwaysTop&&!e._positionAbsolute){a.find(".mbr-arrow").attr("href","#"+e._anchor);return}e._id==this._id&&(c=!0)}a.find(".mbr-arrow").attr("href","#next")},next:function(a){var b=function(a){try{var b=a.target;do if(0<=b.className.indexOf("mbr-arrow")){a.preventDefault();a.stopPropagation();var e=c(b).parents(".app-component").next();e.length&&d.$template.stop().animate({scrollTop:e.offset().top},800,"easeInOutCubic");break}while(b=b.parentNode)}catch(k){}};d.arrowSupport||
(d.arrowSupport=!0,d.$template.click(b),b(a))}},menu:{_onParamsChange:function(a,b,c){if(void 0===b||"hamburgerColor"==b)a={color:this._params.hamburgerColor},this._styles||(this._styles={}),this._styles[".navbar-toggler"]=a,d.Core.renderComponentsStyles()}},"msg-box4":{_onParamsChange:function(a,b,c){e.call(this,a,b,c);"imageSize"!=b&&"undefined"!=typeof b||a.find(".image-size").css("width",this._params.imageSize+"%")},_publishFilter:function(a,b){f.call(this,a);a.find(".image-size").css("width",
this._params.imageSize+"%")}},"msg-box5":{_onParamsChange:function(a,b,c){e.call(this,a,b,c);"imageSize"!=b&&"undefined"!=typeof b||a.find(".image-size").css("width",this._params.imageSize+"%")},_publishFilter:function(a,b){f.call(this,a);a.find(".image-size").css("width",this._params.imageSize+"%")}},slider:{_onParamsShow:function(a,b,c){a=c.find(".carousel-inner > .active").index();b.find(".images > ul > li:eq("+a+")").click()},_onParamsChange:function(a,b,c){"undefined"===typeof b&&a.find(".mbr-slider > .boxed-slider").css({"padding-top":31*
this._params.paddingTop+"px","padding-bottom":31*this._params.paddingBottom+"px"});"paddingTop"==b&&a.find(".mbr-slider > .boxed-slider").css("padding-top",31*c+"px");"paddingBottom"==b&&a.find(".mbr-slider > .boxed-slider").css("padding-bottom",31*c+"px");"fullScreen"==b&&(1==c?a.find(".mbr-slider").find("div:eq(0)").removeAttr("style"):a.find(".mbr-slider > .boxed-slider").css({"padding-top":31*this._params.paddingTop+"px","padding-bottom":31*this._params.paddingBottom+"px"}))},_publishFilter:function(a){a.find(".mbr-slider > .boxed-slider").css({"padding-top":31*
this._params.paddingTop+"px","padding-bottom":31*this._params.paddingBottom+"px"});a.find("[data-interval]").attr("data-interval",this._params.autoplay?5E3:"false");a.find(".carousel-indicators .active, .carousel-inner .active").removeClass("active");a.find(".carousel-indicators > li:eq(0)").addClass("active");a.find(".carousel-inner > div:eq(0)").addClass("active")}},"social-buttons1":{_onParamsChange:function(a,b,c){e.call(this,a,b,c)},_publishFilter:function(a){a.find(".social-likes__counter").remove();
a.find(".mbr-added").removeClass("mbr-added");f.call(this,a)}},testimonials1:{_onParamsChange:function(a,b,d){"undefined"!==typeof this.testimonial&&c.extend(this.items,this.testimonial);for(var g=[],f=0,h=0;h<this._params.count;h++)f>=this.items.length&&(f=0),g.push(this.items[f]),f++;this.testimonial=g;e.call(this,a,b,d)},_publishFilter:function(a,b){f.call(this,a)}}};d.addFilter("loadingComponents",function(a){for(var b in a){var d=a[b],e;for(e in h)b===e&&c.extend(d,h[e]);return a}})}()},["jQuery",
"mbrApp"]);
