var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(b,h,f){b instanceof String&&(b=String(b));for(var l=b.length,n=0;n<l;n++){var t=b[n];if(h.call(f,t,n,b))return{i:n,v:t}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,h,f){b!=Array.prototype&&b!=Object.prototype&&(b[h]=f.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(b,h,f,l){if(h){f=$jscomp.global;b=b.split(".");for(l=0;l<b.length-1;l++){var n=b[l];n in f||(f[n]={});f=f[n]}b=b[b.length-1];l=f[b];h=h(l);h!=l&&null!=h&&$jscomp.defineProperty(f,b,{configurable:!0,writable:!0,value:h})}};$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(b,f){return $jscomp.findInternal(this,b,f).v}},"es6","es3");
defineM("spacem",function(b,h){function f(d,e){for(var g in e)parseInt(g)+1>d&&b(e[g]).css("display","none"),parseInt(g)+1<=d&&b(e[g]).css("display","block")}function l(d,e,b){"undefined"===typeof e?d.find("#contact-info").css({"padding-top":50*this._params.paddingTop+"px","padding-bottom":50*this._params.paddingBottom+"px"}):("paddingTop"==e||"paddingBottom"==e)&&d.find("#contact-info").css("paddingTop"==e?"padding-top":"padding-bottom","paddingTop"==e?50*b:50*b+"px")}function n(d,b,g){"undefined"===
typeof b?d.find(".mbr-section").css({"padding-top":50*this._params.paddingTop+"px","padding-bottom":50*this._params.paddingBottom+"px"}):("paddingTop"==b||"paddingBottom"==b)&&d.find(".mbr-section").css("paddingTop"==b?"padding-top":"padding-bottom","paddingTop"==b?50*g:50*g+"px");if("undefined"===typeof b||"columns"==b)b=parseInt(this._params.columns),d=d.find(".mbr-cards-col"),f(b,d)}function t(d){d.find(".mbr-section").css({"padding-top":50*this._params.paddingTop+"px","padding-bottom":50*this._params.paddingBottom+
"px"});var b=parseInt(this._params.columns);d=d.find(".mbr-cards-col");f(b,d)}function y(d,e,g){l(d,e,g);if("undefined"===typeof e||"columns"==e){g=parseInt(this._params.columns);var f=d.find(".mbr-cards-col"),m;for(m in f)parseInt(m)%4+1>g&&b(f[m]).css("display","none"),parseInt(m)%4+1<=g&&b(f[m]).css("display","block")}if("undefined"===typeof e||"showHover"==e)0==this._params.showHover?d.find(".item-layer").each(function(){b(this).css("display","none")}):d.find(".item-layer").each(function(){b(this).css("display",
"block")})}function A(d){d.find("#contact-info").css({"padding-top":50*this._params.paddingTop+"px","padding-bottom":50*this._params.paddingBottom+"px"});var e=parseInt(this._params.columns);d=d.find(".mbr-cards-col");for(var g in d)parseInt(g)%4+1>e&&b(d[g]).css("display","none"),parseInt(g)%4+1<=e&&b(d[g]).css("display","block")}function u(d,b,g){l(d,b,g);if("undefined"===typeof b||"columns"==b)b=parseInt(this._params.columns),d=d.find(".mbr-cards-col"),f(b,d)}function v(b){b.find("#contact-info").css({"padding-top":50*
this._params.paddingTop+"px","padding-bottom":50*this._params.paddingBottom+"px"});var d=parseInt(this._params.columns);b=b.find(".mbr-cards-col");f(d,b)}function B(b){this._params.hideButtons?(b.find(".hide-buttons").removeClass("hide-buttons"),b.find("a[data-button]").parent().remove()):b.find("a[data-button]").removeAttr("data-button");this._params.logo&&b.find(".navbar-brand .navbar-logo a").addClass("navbar-logo").unwrap();this._params.showBrand&&b.find(".navbar-caption").unwrap()}function C(b,
e){if(void 0===e||"collapsed"==e)b=b.context.defaultView,b.$(b).trigger("resize");if(void 0===e||0<=["bgColor","fontSize","fontName","fontColor","fontHoverColor"].indexOf(e))set(this._styles,".navbar-toggler","color",this._params.fontColor),set(this._styles,".close-icon::before, .close-icon::after","background-color",this._params.fontColor),set(this._styles,".link, .dropdown-item","color",this._params.fontColor),this._params.fontName.url&&set(this._styles,".link, .dropdown-item","googleLink",this._params.fontName.url),
this._params.fontName.css&&set(this._styles,".link, .dropdown-item","font-family",this._params.fontName.css),set(this._styles,".link","font-size",this._params.fontSize+"rem"),set(this._styles,".dropdown-item, .nav-dropdown-sm .link","font-size",(1.083*this._params.fontSize).toFixed(3)+"rem"),set(this._styles,".link:hover, .dropdown-item:hover, .link:focus, .dropdown-item:focus","color",this._params.fontHoverColor),set(this._styles,'.link[aria-expanded="true"], .dropdown-menu',"background",darkenColor(this._params.bgColor,
"10%")),set(this._styles,".nav-dropdown-sm .link:focus, .nav-dropdown-sm .link:hover, .nav-dropdown-sm .dropdown-item:focus, .nav-dropdown-sm .dropdown-item:hover","background",darkenColor(this._params.bgColor,"3%")+"!important"),set(this._styles,'.navbar, .nav-dropdown-sm, .nav-dropdown-sm .link[aria-expanded="true"], .nav-dropdown-sm .dropdown-menu',"background",this._params.bgColor),set(this._styles,".bg-color.transparent .link",{color:this._params.fontColor,transition:"none"}),set(this._styles,
".navbar-toggler i, .navbar-toggler em, .navbar-toggler i:before, .navbar-toggler em:before, .navbar-toggler i:after, .navbar-toggler em:after","background",this._params.fontColor),set(this._styles,'.navbar-toggler[aria-expanded="true"] i, .navbar-toggler[aria-expanded="true"] em',"background","transparent"),set(this._styles,".bg-color.transparent.opened .link","transition","color .2s ease-in-out"),set(this._styles,".bg-color.transparent.opened .link:hover, .bg-color.transparent.opened .link:focus",
"color",this._params.fontHoverColor),set(this._styles,'.link[aria-expanded="true"], .dropdown-item[aria-expanded="true"]',"color",this._params.fontHoverColor+"!important"),h.Core.renderComponentsStyles()}function D(d,e,g){"undefined"===typeof e?d.find(".mbr-section").css({"padding-top":50*this._params.paddingTop+"px","padding-bottom":50*this._params.paddingBottom+"px"}):("paddingTop"==e||"paddingBottom"==e)&&d.find(".mbr-section").css("paddingTop"==e?"padding-top":"padding-bottom","paddingTop"==e?
50*g:50*g+"px");if("undefined"===typeof e||"columns"==e){"3"==this._params.columns&&d.find(".mbr-cards-col").each(function(){b(this).attr("class","mbr-cards-col col-xs-12 col-lg-4")});"2"==this._params.columns&&d.find(".mbr-cards-col").each(function(){b(this).attr("class","mbr-cards-col col-xs-12 col-sm-6")});"1"==this._params.columns&&d.find(".mbr-cards-col").each(function(){b(this).attr("class","mbr-cards-col col-xs-12")});g=parseInt(this._params.columns);var h=d.find(".mbr-cards-col");f(g,h)}if("undefined"===
typeof e||"tabsLeft"==e||"tabsRight"==e){e=parseInt(this._params.tabsLeft);g=parseInt(this._params.tabsCenter);h=parseInt(this._params.tabsRight);var m=d.find("#accordionLeft").children(),l=d.find("#accordionCenter").children();d=d.find("#accordionRight").children();for(var k in m)parseInt(k)+1>e&&b(m[k]).css("display","none"),parseInt(k)+1<=e&&b(m[k]).css("display","block");for(k in l)parseInt(k)+1>g&&b(l[k]).css("display","none"),parseInt(k)+1<=g&&b(l[k]).css("display","block");for(k in d)parseInt(k)+
1>h&&b(d[k]).css("display","none"),parseInt(k)+1<=h&&b(d[k]).css("display","block")}}function F(d){d.find(".mbr-section").css({"padding-top":50*this._params.paddingTop+"px","padding-bottom":50*this._params.paddingBottom+"px"});"3"==this._params.columns&&d.find(".mbr-cards-col").each(function(){b(this).attr("class","mbr-cards-col col-xs-12 col-lg-4")});"2"==this._params.columns&&d.find(".mbr-cards-col").each(function(){b(this).attr("class","mbr-cards-col col-xs-12 col-sm-6")});"1"==this._params.columns&&
d.find(".mbr-cards-col").each(function(){b(this).attr("class","mbr-cards-col col-xs-12")});var e=parseInt(this._params.columns),g=d.find(".mbr-cards-col");f(e,g);e=parseInt(this._params.tabsLeft);g=parseInt(this._params.tabsCenter);var h=parseInt(this._params.tabsRight),m=d.find("#accordionLeft").children(),l=d.find("#accordionCenter").children();d=d.find("#accordionRight").children();for(var k in m)parseInt(k)+1>e&&b(m[k]).css("display","none"),parseInt(k)+1<=e&&b(m[k]).css("display","block");for(k in l)parseInt(k)+
1>g&&b(l[k]).css("display","none"),parseInt(k)+1<=g&&b(l[k]).css("display","block");for(k in d)parseInt(k)+1>h&&b(d[k]).css("display","none"),parseInt(k)+1<=h&&b(d[k]).css("display","block")}function p(d,e,g){var f=this;e.find(".images > ul > li:eq("+g.find(".carousel-inner > .active").index()+")").click();e.find(".image-tabs li:not(.add-item)").each(function(d){(d=f._params.slides[d])&&d.playVideo&&(d=getVideoId(d.videoUrl))&&b(this).css("background-image","url("+getPreviewUrl(d)+")")})}function q(d,
e,g){var f=b("#edit-component-params").find(".image-tabs li.active");if(-1<f.index()){var h=this._params.slides[f.index()];h.playVideo?(h=getVideoId(h.videoUrl))&&f.css("background-image","url("+getPreviewUrl(h)+")"):0===h.image.indexOf("file:")?f.css("background-image",'url("'+h.image+'")'):(h=core2app(h.image),f.css("background-image",'url("'+h+'")'))}if(void 0===e)d.find(".mbr-slider > .boxed-slider").css({"padding-top":40*this._params.paddingTop+"px","padding-bottom":40*this._params.paddingBottom+
"px"});else switch(e){case "paddingTop":d.find(".mbr-slider > .boxed-slider").css("padding-top",40*g+"px");break;case "paddingBottom":d.find(".mbr-slider > .boxed-slider").css("padding-bottom",40*g+"px");break;case "fullScreen":g?d.find(".mbr-slider div:eq(0)").removeAttr("style"):d.find(".mbr-slider > .boxed-slider").css({"padding-top":40*this._params.paddingTop+"px","padding-bottom":40*this._params.paddingBottom+"px"})}}function r(b){this._plugins=function(b,d,f){return f.split(",").filter(function(d){return 0>
b.indexOf(d)}).concat(d?b:[]).join(",")}(["YTPlayer","SliderVideo"],!!b.find('[data-bg-video-slide^="http"]').length,this._plugins);b.find(".mbr-slider > .boxed-slider").css({"padding-top":40*this._params.paddingTop+"px","padding-bottom":40*this._params.paddingBottom+"px"});b.find("[data-interval]").attr("data-interval",this._params.autoplay?1E3*this._params.timeout:"false");[".carousel-indicators > li",".carousel-inner > div"].forEach(function(d){b.find(d).removeClass("active").eq(0).addClass("active")})}
var G=document.querySelector("head"),w=document.createElement("script");w.src="app/includes/migrate/padding-components.js";G.appendChild(w);var x=h.theme.name;"use strict";"spacem"===x&&function(){function d(a){return"false"==a?!1:(a=/(?:\?v=|\/embed\/|\.be\/)([-a-z0-9_]+)/i.exec(a)||/^([-a-z0-9_]+)$/i.exec(a))?a[1]:!1}function e(a,c){return"http://img.youtube.com/vi/"+a+"/"+(c||"")+"default.jpg"}b(document).on("sortstop",function(a){a=b(a.target).closest("#edit-component-params").attr("data-component-id");
h.Core.$body.find('.app-component[data-app-component-id="'+a+'"] .mbr-gallery').trigger("change.cards")});b(document).on("sortstop",function(a){a=b(a.target).closest("#edit-component-params").attr("data-component-id");h.Core.$body.find('.app-component[data-app-component-id="'+a+'"] .mbr-slider').trigger("change.cards")});var g=["OVERVIEW","FEATURES","HELP","DOWNLOAD","Tutorials"];h.Core.addFilter("cleanHTMLplease",function(a){a.find(".navbar-dropdown .nav").attr("id","exCollapsingNavbar");return a});
var z=["firstType","secondType","thirdType","fourthType"],m=function(a,c){for(var b=[],d=0,e=0;e<z.length;e++)b[e]="hidden"!=c._params[z[e]],b[e]&&(d+=1);a.find(".mbr-plan").parent().each(function(a){b[a]&&(a="col-xs-12 ",1==d?a+="col-md-6 col-md-offset-3 col-sm-12 col-xl-6 col-xl-offset-3":2==d?a+="col-md-6 col-xl-6":3==d?a+="col-md-6 col-xl-4":4==d&&(a+=" col-md-6 col-xl-3"),this.className=a)})};var E="spacem"===x?h.arrayToDropdownMenu(g):void 0;E={_onParamsChange:function(a,c,b){C.call(this,a,
c)},_publishFilter:function(a,c){B.call(this,a)},items:E};var k="spacem"===x?h.arrayToDropdownMenu(g):void 0;k={_onParamsChange:function(a,c,b){C.call(this,a,c)},_publishFilter:function(a,c){B.call(this,a)},items:k};g="spacem"===x?h.arrayToDropdownMenu(g):void 0;var w={accordion1:{_onParamsChange:function(a,c,b){D.call(this,a,c,b)},_publishFilter:function(a,c){F.call(this,a)}},accordion2:{_onParamsChange:function(a,c,b){D.call(this,a,c,b)},_publishFilter:function(a,c){F.call(this,a)}},accordion3:{_onParamsChange:function(a,
c,b){D.call(this,a,c,b)},_publishFilter:function(a,c){F.call(this,a)}},content1:{_onParamsChange:function(a,c,b){l.call(this,a,c,b);if("undefined"===typeof c||"columns"==c)c=parseInt(this._params.columns)/2,a=a.find(".mbr-cards-row"),f(c,a)},_publishFilter:function(a,c){a.find("#contact-info").css({"padding-top":50*this._params.paddingTop+"px","padding-bottom":50*this._params.paddingBottom+"px"});c=parseInt(this._params.columns)/2;a=a.find(".mbr-cards-row");f(c,a)}},content2:{_onParamsChange:function(a,
c,b){l.call(this,a,c,b);if("undefined"===typeof c||"columns"==c)c=parseInt(this._params.columns)/3,a=a.find(".mbr-cards-row"),f(c,a)},_publishFilter:function(a,c){a.find("#contact-info").css({"padding-top":50*this._params.paddingTop+"px","padding-bottom":50*this._params.paddingBottom+"px"});c=parseInt(this._params.columns)/3;a=a.find(".mbr-cards-row");f(c,a)}},content3:{_onParamsChange:function(a,c,b){u.call(this,a,c,b)},_publishFilter:function(a,c){v.call(this,a)}},content4:{_onParamsChange:function(a,
c,b){y.call(this,a,c,b)},_publishFilter:function(a,c){A.call(this,a)}},content6:{_onParamsChange:function(a,c,b){n.call(this,a,c,b)},_publishFilter:function(a,c){t.call(this,a)}},content7:{_onParamsChange:function(a,c,b){n.call(this,a,c,b)},_publishFilter:function(a,c){t.call(this,a)}},content10:{_onParamsChange:function(a,c,b){n.call(this,a,c,b)},_publishFilter:function(a,c){t.call(this,a)}},content11:{_onParamsChange:function(a,c,b){n.call(this,a,c,b)},_publishFilter:function(a,c){t.call(this,a)}},
gallery1:{_onParamsChange:function(a,c,b){switch(c){case void 0:a.find(".mbr-section").css({"padding-top":1.5*this._params.paddingTop+"rem","padding-bottom":1.5*this._params.paddingBottom+"rem"});break;case "paddingTop":a.find(".mbr-section").css("padding-top",1.5*b+"rem");break;case "paddingBottom":a.find(".mbr-section").css("padding-bottom",1.5*b+"rem")}},_onParamsShow:function(a,c,d){a=b(a.target).parents(".mbr-gallery-item:eq(0)");a.length&&c.find(".images > ul > li:eq("+a.index()+")").click()},
_publishFilter:function(a){a.find(".mbr-gallery-item>div").attr("data-toggle","modal");a.find(".mbr-section").css({"padding-top":1.5*this._params.paddingTop+"rem","padding-bottom":1.5*this._params.paddingBottom+"rem"})}},gallery2:{_onParamsChange:function(a,c,b){switch(c){case void 0:a.find(".mbr-section").css({"padding-top":1.5*this._params.paddingTop+"rem","padding-bottom":1.5*this._params.paddingBottom+"rem"});break;case "paddingTop":a.find(".mbr-section").css("padding-top",1.5*b+"rem");break;
case "paddingBottom":a.find(".mbr-section").css("padding-bottom",1.5*b+"rem")}},_onParamsShow:function(a,c,d){a=b(a.target).parents(".mbr-gallery-item:eq(0)");a.length&&c.find(".images > ul > li:eq("+a.index()+")").click()},_publishFilter:function(a){a.find(".mbr-gallery-item>div").attr("data-toggle","modal");a.find(".mbr-section").css({"padding-top":1.5*this._params.paddingTop+"rem","padding-bottom":1.5*this._params.paddingBottom+"rem"})}},header1:{_onParamsChange:function(a,c,b){u.call(this,a,c,
b)},_publishFilter:function(a,c){v.call(this,a)}},header3:{_onParamsChange:function(a,c,b){l.call(this,a,c,b);"imageSize"!=c&&"undefined"!=typeof c||a.find(".image-size").css("width",this._params.imageSize+"%");if("undefined"===typeof c||"columns"==c)c=parseInt(this._params.columns),a=a.find(".mbr-cards-col"),f(c,a)},_publishFilter:function(a,c){a.find("#contact-info").css({"padding-top":50*this._params.paddingTop+"px","padding-bottom":50*this._params.paddingBottom+"px"});a.find(".image-size").css("width",
this._params.imageSize+"%");c=parseInt(this._params.columns);a=a.find(".mbr-cards-col");f(c,a)}},menu1:E,menu2:k,menu4:{_onParamsChange:function(a,c,b){C.call(this,a,c)},_publishFilter:function(a,c){B.call(this,a)},items:g},news1:{_onParamsChange:function(a,c,b){y.call(this,a,c,b)},_publishFilter:function(a,c){A.call(this,a)}},news2:{_onParamsChange:function(a,c,b){y.call(this,a,c,b)},_publishFilter:function(a,c){A.call(this,a)}},"pricing-table1":{_onParamsChange:function(a,c,d){"undefined"===typeof c&&
a.find("section.mbr-section").css({"padding-top":40*this._params.paddingTop+"px","padding-bottom":40*this._params.paddingBottom+"px"});"paddingTop"!=c&&"paddingBottom"!=c||a.find("section.mbr-section").css("paddingTop"==c?"padding-top":"padding-bottom",40*d+"px");"undefined"!=typeof c&&-1==b.inArray(c,z)||m(a,this)},_publishFilter:function(a,c){a.find("section.mbr-section").css({"padding-top":40*this._params.paddingTop+"px","padding-bottom":40*this._params.paddingBottom+"px"});m(a,this)}},process1:{_onParamsChange:function(a,
c,b){u.call(this,a,c,b)},_publishFilter:function(a,c){v.call(this,a)}},progressbar1:{_onParamsChange:function(a,c,b){"undefined"===typeof c?(a.find("#contact-info").css({"padding-top":50*this._params.paddingTop+"px","padding-bottom":50*this._params.paddingBottom+"px"}),"0"===this._params.progress1&&a.find(".progress1 .progress").attr("value",0),"0"===this._params.progress2&&a.find(".progress2 .progress").attr("value",0),"0"===this._params.progress3&&a.find(".progress3 .progress").attr("value",0),
"0"===this._params.progress4&&a.find(".progress4 .progress").attr("value",0)):"paddingTop"!=c&&"paddingBottom"!=c||a.find("#contact-info").css("paddingTop"==c?"padding-top":"padding-bottom","paddingTop"==c?50*b:50*b+"px");"imageSize"!=c&&"undefined"!=typeof c||a.find(".image-size").css("width",this._params.imageSize+"%");if("undefined"===typeof c||"columns"==c)c=parseInt(this._params.columns),b=a.find(".mbr-cards-col"),f(c,b);a.find(".progress1 .progressbar-number").css({right:100-this._params.progress1+
"%"});a.find(".progress2 .progressbar-number").css({right:100-this._params.progress2+"%"});a.find(".progress3 .progressbar-number").css({right:100-this._params.progress3+"%"});a.find(".progress4 .progressbar-number").css({right:100-this._params.progress4+"%"})},_publishFilter:function(a,c){a.find("#contact-info").css({"padding-top":50*this._params.paddingTop+"px","padding-bottom":50*this._params.paddingBottom+"px"});c=parseInt(this._params.columns);var b=a.find(".mbr-cards-col");f(c,b);"0"===this._params.progress1&&
a.find(".progress1 .progress").attr("value",0);"0"===this._params.progress2&&a.find(".progress2 .progress").attr("value",0);"0"===this._params.progress3&&a.find(".progress3 .progress").attr("value",0);"0"===this._params.progress4&&a.find(".progress4 .progress").attr("value",0);a.find(".progress1 .progressbar-number").css({right:100-this._params.progress1+"%"});a.find(".progress2 .progressbar-number").css({right:100-this._params.progress2+"%"});a.find(".progress3 .progressbar-number").css({right:100-
this._params.progress3+"%"});a.find(".progress4 .progressbar-number").css({right:100-this._params.progress4+"%"});a.find(".image-size").css("width",this._params.imageSize+"%")}},progressbar2:{_onParamsChange:function(a,c,b){"undefined"===typeof c?(a.find("#contact-info").css({"padding-top":50*this._params.paddingTop+"px","padding-bottom":50*this._params.paddingBottom+"px"}),"0"===this._params.progress1&&a.find(".progress1 .progress").attr("value",0),"0"===this._params.progress2&&a.find(".progress2 .progress").attr("value",
0),"0"===this._params.progress3&&a.find(".progress3 .progress").attr("value",0),"0"===this._params.progress4&&a.find(".progress4 .progress").attr("value",0)):"paddingTop"!=c&&"paddingBottom"!=c||a.find("#contact-info").css("paddingTop"==c?"padding-top":"padding-bottom","paddingTop"==c?50*b:50*b+"px");if("undefined"===typeof c||"columns"==c)c=parseInt(this._params.columns),b=a.find(".mbr-cards-col"),f(c,b);a.find(".progress1 .progressbar-number").css({right:100-this._params.progress1+"%"});a.find(".progress2 .progressbar-number").css({right:100-
this._params.progress2+"%"});a.find(".progress3 .progressbar-number").css({right:100-this._params.progress3+"%"});a.find(".progress4 .progressbar-number").css({right:100-this._params.progress4+"%"})},_publishFilter:function(a,c){a.find("#contact-info").css({"padding-top":50*this._params.paddingTop+"px","padding-bottom":50*this._params.paddingBottom+"px"});c=parseInt(this._params.columns);var b=a.find(".mbr-cards-col");f(c,b);"0"===this._params.progress1&&a.find(".progress1 .progress").attr("value",
0);"0"===this._params.progress2&&a.find(".progress2 .progress").attr("value",0);"0"===this._params.progress3&&a.find(".progress3 .progress").attr("value",0);"0"===this._params.progress4&&a.find(".progress4 .progress").attr("value",0);a.find(".progress1 .progressbar-number").css({right:100-this._params.progress1+"%"});a.find(".progress2 .progressbar-number").css({right:100-this._params.progress2+"%"});a.find(".progress3 .progressbar-number").css({right:100-this._params.progress3+"%"});a.find(".progress4 .progressbar-number").css({right:100-
this._params.progress4+"%"})}},slider1:{_onParamsShow:function(a,c,b){p.call(this,a,c,b)},_onParamsChange:function(a,c,b){q.call(this,a,c,b)},_publishFilter:function(a){r.call(this,a)}},slider2:{_onParamsShow:function(a,c,b){p.call(this,a,c,b)},_onParamsChange:function(a,c,b){q.call(this,a,c,b)},_publishFilter:function(a){r.call(this,a)}},slider3:{_onParamsShow:function(a,c,b){p.call(this,a,c,b)},_onParamsChange:function(a,b,d){q.call(this,a,b,d)},_publishFilter:function(a){r.call(this,a)}},slider4:{_onParamsShow:function(a,
b,d){p.call(this,a,b,d)},_onParamsChange:function(a,b,d){q.call(this,a,b,d)},_publishFilter:function(a){r.call(this,a)}},slider5:{_onParamsShow:function(a,c,f){var g=this;c.find(".images > ul > li:eq("+f.find(".carousel-inner > .active").index()+")").click();c.find(".image-tabs li:not(.add-item)").each(function(a){(a=g._params.slides[a])&&a.playVideo&&(a=d(a.videoUrl))&&b(this).css("background-image","url("+e(a)+")")})},_onParamsChange:function(a,c,f){var g=b("#edit-component-params").find(".image-tabs li.active");
if(-1<g.index()){var h=this._params.slides[g.index()];h.playVideo?(h=d(h.videoUrl))&&g.css("background-image","url("+e(h)+")"):0===h.image.indexOf("file:")?g.css("background-image",'url("'+h.image+'")'):(h=h.image,h=/file:/g.test(h)?h:Bridge.path2app("web/app/builder/"+h),g.css("background-image",'url("'+h+'")'))}"imageSize"!=c&&"undefined"!=typeof c||a.find(".image-size").css("width",this._params.imageSize+"%");if(void 0===c)a.find(".mbr-slider > .boxed-slider").css({"padding-top":40*this._params.paddingTop+
"px","padding-bottom":40*this._params.paddingBottom+"px"});else switch(c){case "paddingTop":a.find(".mbr-slider > .boxed-slider").css("padding-top",40*f+"px");break;case "paddingBottom":a.find(".mbr-slider > .boxed-slider").css("padding-bottom",40*f+"px");break;case "fullScreen":f?a.find(".mbr-slider div:eq(0)").removeAttr("style"):a.find(".mbr-slider > .boxed-slider").css({"padding-top":40*this._params.paddingTop+"px","padding-bottom":40*this._params.paddingBottom+"px"})}},_publishFilter:function(a){this._plugins=
function(a,b,d){return d.split(",").filter(function(b){return 0>a.indexOf(b)}).concat(b?a:[]).join(",")}(["YTPlayer","SliderVideo"],!!a.find('[data-bg-video-slide^="http"]').length,this._plugins);a.find(".mbr-slider > .boxed-slider").css({"padding-top":40*this._params.paddingTop+"px","padding-bottom":40*this._params.paddingBottom+"px"});a.find("[data-interval]").attr("data-interval",this._params.autoplay?1E3*this._params.timeout:"false");[".carousel-indicators > li",".carousel-inner > div"].forEach(function(b){a.find(b).removeClass("active").eq(0).addClass("active")});
a.find(".image-size").css("width",this._params.imageSize+"%")}},slider6:{_onMediaClick:function(a,c){a.stopPropagation();a.preventDefault();var d=b(a.target).closest(".carousel-item"),e=d.index(),g=c["this"],f=b.extend(!0,{},g.media);h.Core.showMediaImageDialog(f,function(f){g.media=f;h.Core.updateGlobalComponents(c._id);0<b(a.target).parents(".clonedCol").length?(f=b(a.target).parents(".clonedCol").attr("data-cloned-index"),b(a.target).attr("src",b(a.target).parents(".carousel-inner").find(".carousel-item").eq(f).find("img").attr("src"))):
d.closest(".carousel-inner").find("[data-cloned-index ="+e+"]").find("img").attr("src",f.image.src)})},_onParamsShow:function(a,c,d){c.find(".images > ul > li:eq("+d.find(".carousel-inner > .active").index()+")").click();var e="";c.find(".image-tabs li:not(.add-item)").each(function(a){e=d.find(".carousel-item").eq(a).find("img").attr("src");b(this).css("background-image","url("+e+")")})},_onParamsChange:function(a,b,d){if(void 0===b)a.find(".mbr-slider").css({"padding-top":40*this._params.paddingTop+
"px","padding-bottom":40*this._params.paddingBottom+"px"}),[".carousel-indicators > li",".carousel-inner > div"].forEach(function(b){a.find(b).removeClass("active").eq(0).addClass("active")});else switch(b){case "paddingTop":a.find(".mbr-slider").css("padding-top",40*d+"px");break;case "paddingBottom":a.find(".mbr-slider").css("padding-bottom",40*d+"px");break;case "fullScreen":d&&a.find(".mbr-slider div:eq(0)").removeAttr("style")}},_publishFilter:function(a){a.find(".mbr-slider").css({"padding-top":40*
this._params.paddingTop+"px","padding-bottom":40*this._params.paddingBottom+"px"});a.find("[data-interval]").attr("data-interval",this._params.autoplay?1E3*this._params.timeout:"false");[".carousel-indicators > li",".carousel-inner > div"].forEach(function(b){a.find(b).removeClass("active").eq(0).addClass("active")})}},slider7:{_onParamsShow:function(a,b,d){p.call(this,a,b,d)},_onParamsChange:function(a,b,d){q.call(this,a,b,d)},_publishFilter:function(a){r.call(this,a)}},slider8:{_onParamsShow:function(a,
b,d){p.call(this,a,b,d)},_onParamsChange:function(a,b,d){q.call(this,a,b,d)},_publishFilter:function(a){r.call(this,a)}},testimonials1:{_onParamsShow:function(a,b,d){p.call(this,a,b,d)},_onParamsChange:function(a,b,d){q.call(this,a,b,d)},_publishFilter:function(a){r.call(this,a)}},testimonials2:{_onParamsShow:function(a,b,d){p.call(this,a,b,d)},_onParamsChange:function(a,b,d){q.call(this,a,b,d)},_publishFilter:function(a){r.call(this,a)}},title3:{_onParamsChange:function(a,b,d){u.call(this,a,b,d)},
_publishFilter:function(a,b){v.call(this,a)}},title4:{_onParamsChange:function(a,b,d){u.call(this,a,b,d)},_publishFilter:function(a,b){v.call(this,a)}}};h.addFilter("loadingComponents",function(a){for(var c in a){var d=a[c],e;for(e in w)c===e&&b.extend(d,w[e]);return a}})}()},["jQuery","mbrApp"]);
