var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(c,e,f){c instanceof String&&(c=String(c));for(var h=c.length,g=0;g<h;g++){var d=c[g];if(e.call(f,d,g,c))return{i:g,v:d}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(c,e,f){c!=Array.prototype&&c!=Object.prototype&&(c[e]=f.value)};$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global&&null!=global?global:c};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(c,e,f,h){if(e){f=$jscomp.global;c=c.split(".");for(h=0;h<c.length-1;h++){var g=c[h];g in f||(f[g]={});f=f[g]}c=c[c.length-1];h=f[c];e=e(h);e!=h&&null!=e&&$jscomp.defineProperty(f,c,{configurable:!0,writable:!0,value:e})}};$jscomp.polyfill("Array.prototype.find",function(c){return c?c:function(c,f){return $jscomp.findInternal(this,c,f).v}},"es6","es3");
defineM("change-background",function(c,e){e.regExtension({name:"change-background",events:{load:function(){function f(c,k){c&&k.css({"background-size":"200% 200%",animation:"gradient-animation 5s infinite alternate","-webkit-animation":"gradient-animation 5s infinite alternate"})}function e(d,k,b){function a(a,b){if("IMG"===a.prop("tagName")){a.attr("src",b);var d=a.parents(".app-video-wrapper:eq(0)");/no-video/g.test(b)?d.length&&a.unwrap():d.length||a.wrap('<div class="app-video-wrapper">')}else d=
a.find(".mbr-background-video-preview"),d.length||(d=c('<div class="mbr-background-video-preview">').css({backgroundSize:"cover",backgroundPosition:"center"}),a.find("> *:eq(0)").before(d)),d.css("background-image",'url("'+b+'")')}function f(a){"IMG"!==a.prop("tagName")&&a.find(".mbr-background-video-preview").remove()}var e=c(d);if(b)f(e);else if((d=k.match(/(http:|https:|)\/\/(player.|www.)?(vimeo\.com|youtu(be\.com|\.be|be\.googleapis\.com))\/(shorts\/|video\/|embed\/|watch\?v=|v\/)?([A-Za-z0-9._%-]*)(&\S+)?/))&&
/youtu\.?be/g.test(d[3])){var g=c("<img>");g.on("load",function(){if(120===(this.naturalWidth||this.width)){var b=this.src.split("/").pop();switch(b){case "maxresdefault.jpg":this.src=this.src.replace(b,"sddefault.jpg");break;case "sddefault.jpg":this.src=this.src.replace(b,"hqdefault.jpg");break;default:a(e,"images/no-video.jpg"),g.remove()}}else a(e,this.src),g.remove()});g.attr("src","http://img.youtube.com/vi/"+d[6]+"/maxresdefault.jpg")}else d&&/vimeo/g.test(d[3])?c.ajax({type:"GET",url:"http://vimeo.com/api/v2/video/"+
d[6]+".json",dataType:"json",success:function(b){a(e,b[0].thumbnail_large)},error:function(){a(e,"images/no-video.jpg")}}):a(e,"images/video-placeholder.jpg")}var g=this;g.Core.addFilter("changeComponentParams",function(d,c,b,a){a=g.$template.find("[data-app-component-id="+a+"] > .app-component-content section");"bgImageRadio"===c&&!0===d?(a.find(".mbr-background-video-preview").remove(),a.css({"background-image":"url("+b.bgImage+")","background-color":"","background-size":"",animation:"","-webkit-animation":""}),
b.parallax&&a.addClass("mbr-parallax-background"),b.overlay&&(a.find(".mbr-overlay").length||a.prepend('<div class="mbr-overlay"></div>'),a.find(".mbr-overlay").css({"background-color":b.overlayColor,opacity:b.overlayOpacity}))):"bgImage"===c?a.css({"background-image":"url("+d+")"}):"bgColorRadio"===c&&!0===d?(a.removeClass("mbr-parallax-background"),a.find(".mbr-overlay").remove(),a.find(".mbr-background-video-preview").remove(),b.switchBgGradient?(a.css("background-image","linear-gradient("+b.gradientAngle+
"deg, "+b.containerColor1+", "+b.containerColor2+")"),b.gradientAnimation&&f(b.gradientAnimation,a)):a.css({"background-color":b.bgColor,"background-image":"","background-size":"",animation:"","-webkit-animation":""})):"bgColor"===c?a.css("background-color",b.bgColor):"parallax"===c?d?a.addClass("mbr-parallax-background"):a.removeClass("mbr-parallax-background"):"bgVideoRadio"===c&&!0===d?(a.css({"background-color":"","background-image":"","background-size":"",animation:"","-webkit-animation":""}).removeClass("mbr-parallax-background"),
e(a[0],b.bgVideo.url,!1),b.overlay&&(a.find(".mbr-overlay").remove(),a.prepend('<div class="mbr-overlay"></div>'),a.find(".mbr-overlay").css({"background-color":b.overlayColor,opacity:b.overlayOpacity}))):"bgVideo"===c?e(a[0],d.url,!1):"overlay"===c?(d?(a.prepend('<div class="mbr-overlay"></div>'),a.find(".mbr-overlay").css({"background-color":b.overlayColor,opacity:b.overlayOpacity})):a.find(".mbr-overlay").remove(),b.switchOverlayGradient?a.find(".mbr-overlay").css("background-image","linear-gradient("+
b.overlayAngle+"deg, "+b.overlayColor1+", "+b.overlayColor2+")"):a.find(".mbr-overlay").css("background-color",b.overlayColor)):"overlayColor"===c?a.find(".mbr-overlay").css("background-color",b.overlayColor):"switchOverlayGradient"===c?d?a.find(".mbr-overlay").css("background-image","linear-gradient("+b.overlayAngle+"deg, "+b.overlayColor1+", "+b.overlayColor2+")"):a.find(".mbr-overlay").css("background-color",b.overlayColor):"overlayColor1"===c?a.find(".mbr-overlay").css("background-image","linear-gradient("+
b.overlayAngle+"deg, "+d+", "+b.overlayColor2+")"):"overlayColor2"===c?a.find(".mbr-overlay").css("background-image","linear-gradient("+b.overlayAngle+"deg, "+b.overlayColor1+", "+d+")"):"overlayAngle"===c?a.find(".mbr-overlay").css("background-image","linear-gradient("+d+"deg, "+b.overlayColor1+", "+b.overlayColor2+")"):"overlayOpacity"===c?a.find(".mbr-overlay").css("opacity",d):"switchBgGradient"===c?d?(a.css({"background-image":"linear-gradient("+b.gradientAngle+"deg, "+b.containerColor1+", "+
b.containerColor2+")","background-color":""}),b.gradientAnimation&&f(b.gradientAnimation,a)):a.css({"background-color":b.bgColor,"background-size":"","background-image":"",animation:"","-webkit-animation":""}):"containerColor1"===c?(a.css("background-image","linear-gradient("+b.gradientAngle+"deg, "+d+", "+b.containerColor2+")"),f(b.gradientAnimation,a)):"containerColor2"===c?(a.css("background-image","linear-gradient("+b.gradientAngle+"deg, "+b.containerColor1+", "+d+")"),f(b.gradientAnimation,a)):
"gradientAngle"===c?(a.css("background-image","linear-gradient("+d+"deg, "+b.containerColor1+", "+b.containerColor2+")"),f(b.gradientAnimation,a)):"gradientAnimation"===c&&(d?f(d,a):a.css({"background-size":"",animation:"","-webkit-animation":""}));return d})}}})},["jQuery","mbrApp"]);
