var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(b,c,d){b instanceof String&&(b=String(b));for(var e=b.length,a=0;a<e;a++){var f=b[a];if(c.call(d,f,a,b))return{i:a,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,c,d){b!=Array.prototype&&b!=Object.prototype&&(b[c]=d.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(b,c,d,e){if(c){d=$jscomp.global;b=b.split(".");for(e=0;e<b.length-1;e++){var a=b[e];a in d||(d[a]={});d=d[a]}b=b[b.length-1];e=d[b];c=c(e);c!=e&&null!=c&&$jscomp.defineProperty(d,b,{configurable:!0,writable:!0,value:c})}};$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(b,d){return $jscomp.findInternal(this,b,d).v}},"es6","es3");
(function(b,c){function d(a){b("[data-app-component-id="+a+"] > .app-component-content .mbr-gallery .mbr-gallery-item > [data-slide-to], [data-app-component-id="+a+"] > .app-component-content .mbr-gallery .mbr-gallery-item > [data-bs-slide-to]").off("click").on("click",function(f){f.preventDefault();if(!f.target.hasAttribute("data-app-edit")){var d=c.getComponentParams(a),g=b(f.target).parent().index(),e=[];e[g]={};for(var l in d["default"])if("image-tabs"===d["default"][l].type){var k=l;break}if(k){var h=
{image:{width:2E3,quality:70,src:d.current[k][g].image,alt:d.current[k][g].alt,title:d.current[k][g].title}};c.APP.showMediaImageDialog(h,function(){function b(b){e[g].thumb=b;c.changeComponentParams(a,k,e)}e[g].image=h.image.src;e[g].alt=h.image.alt;e[g].title=h.image.title;/(gif|svg|ico|tif|webp)$/i.test(h.image.src)?b(h.image.src):c.Bridge.transformImage(h.image.src,{width:800,height:"-1",keepAspectRatio:!0,quality:80},function(a){c.APP.projectPath?c.Bridge.moveFileClean(a,c.APP.getProjectImagesDir(),
function(a){b(a)}):b(a)})},!1,!0)}}});b("[data-app-component-id="+a+"] .mbr-gallery-title").off("click").on("click","a",function(a){a.stopPropagation()})}function e(a,b){a=a.getElementsByTagName("img");for(var c=a.length,d=0;d<a.length;d++)a[d].complete?c--:a[d].addEventListener("load",function(){c--;0==c&&b()}),0==c&&b()}c.regExtension({name:"core-gallery",events:{loadedComponent:function(a,c,m,g){a=a._id;var f=b("[data-app-component-id="+a+"] > .app-component-content .mbr-gallery");f.length&&(c=
f.find(".row.mbr-gallery"),c.length&&e(c[0],function(){f.trigger("change.cards")}));c=b("[data-app-component-id="+a+"] > .app-component-content .row.mbr-masonry");if(c.length){var l=new Masonry(c[0],{});setTimeout(function(){l.layout()},100)}g?(m.find("[data-app-component-id="+a+"] > .app-component-content .mbr-gallery-item>div").attr("data-toggle","modal"),m.find("[data-app-component-id="+a+"] > .app-component-content .mbr-gallery-item>div").attr("data-bs-toggle","modal"),m.find("[data-app-component-id="+
a+"] > .app-component-content .gallery-image>div").attr("data-bs-toggle","modal")):d(a)},addComponentParamsTab:function(a){d(a)},changedComponentParams:function(a){d(a)},saveMediaImageDialog:function(a,b,c){setTimeout(function(){mbrAppCore.$body.find('.app-component[data-app-component-id="'+c+'"] .mbr-gallery').trigger("change.cards")},100)},summernoteFocus:function(a){b(a).parents("[data-app-component-id]:eq(0)").find(".row.mbr-masonry").length&&b(a).parents("div.item").addClass("editing")},summernoteBlur:function(a){b(a).parents("[data-app-component-id]:eq(0)").find(".row.mbr-masonry").length&&
c.spectrumPicker&&!c.spectrumPicker.hasClass("sp-active")&&(b(a).parents("div.item").removeClass("editing"),mbrAppCore.render(b(a).parents("[data-app-component-id]:eq(0)").attr("data-app-component-id")))},rivetsBlur:function(a){b(a).parents("[data-app-component-id]:eq(0)").find(".row.mbr-masonry").length&&c.spectrumPicker&&!c.spectrumPicker.hasClass("sp-active")&&(b(a).parents("div.item").removeClass("editing"),mbrAppCore.render(b(a).parents("[data-app-component-id]:eq(0)").attr("data-app-component-id")))},
savedCodeEditor:function(a){mbrAppCore.$body.find('.app-component[data-app-component-id="'+a+'"] .row.mbr-masonry').length&&mbrAppCore.render(a)}}})})(jQuery,mbrAppCore);
