var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var e=a.length,d=0;d<e;d++){var f=a[d];if(b.call(c,f,d,a))return{i:d,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,c,e){if(b){c=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var d=a[e];d in c||(c[d]={});c=c[d]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};
$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.SymbolClass=function(a,b){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};
$jscomp.Symbol=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(c||"")+"_"+b++,c)}var b=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};
$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var c=0,e={next:function(){if(c<a.length){var d=c++;return{value:b(d,a[d]),done:!1}}e.next=function(){return{done:!0,value:void 0}};return e.next()}};e[Symbol.iterator]=function(){return e};return e};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
defineM("gallery-video",function(a,b){b.regExtension({name:"gallery-video",global:{downloadVideoPreview:function(c){function e(b){var c=!1;a.ajax({type:"GET",url:"https://vimeo.com/api/v2/video/"+b+".json",dataType:"json",async:!1,success:function(a){c=a[0].thumbnail_large}});return c}function d(b){var c=!1;a.ajax({url:"https://vimeo.com/api/oembed.json?url="+b,type:"GET",async:!1,success:function(a){a.video_id&&(c=a.video_id)}});return c}function f(a,c,d){c?b.addImageFromUrlToAssets(e(a)).then(d):
k(a).done(function(a){b.addImageFromUrlToAssets(a).then(d)})}var g=!1,h="",k=function(){var b={};return function(c){var d=a.Deferred();c in b?b[c]?d.resolve(b[c]):d.reject("Preview image not found."):a("<img>").on("load",function(){if(120===(this.naturalWidth||this.width)){var a=this.src.split("/").pop();switch(a){case "maxresdefault.jpg":this.src=this.src.replace(a,"sddefault.jpg");break;case "sddefault.jpg":this.src=this.src.replace(a,"hqdefault.jpg");break;case "hqdefault.jpg":this.src=this.src.replace(a,
"default.jpg");break;default:b[c]=null,d.reject("Preview image not found.")}}else d.resolve(b[c]=this.src)}).attr("src","https://img.youtube.com/vi/"+c+"/maxresdefault.jpg");return d}}();h=function(a){return(a=/(?:\?v=|\/embed\/|\.be\/)([-a-z0-9_]+)/i.exec(a)||/^([-a-z0-9_]+)$/i.exec(a))?a[1]:!1}(c);-1!=c.indexOf("vimeo.com")&&(h=d(c),g=!0);var l=a.Deferred();h?f(h,g,function(a){l.resolve(a)}):l.resolve(!1);return l}},events:{load:function(){var a=this;a.Core.addFilter("changeComponentParams",function(c,
d,f,g){g=a.$template.find("[data-app-component-id="+g+"] > .app-component-content section [mbr-gallery]").attr("mbr-gallery")||"images";if(d===g&&(d=Object.keys(c),1==d.length&&(d=c[d[0]],"playVideo"in d||"videoUrl"in d))){var e=a.$body.find("#edit-component-params").find(".image-tabs li.active"),k=f[g][e.index()];"playVideo"in d&&(f=d.playVideo?b.core2path(k.videoPreview):b.core2path(k.image),e.css("background-image",'url("'+f+'")'));"videoUrl"in d&&a.downloadVideoPreview(d.videoUrl).then(function(a){var c=
b.$componentsParams.attr("data-component-id"),d=b.Core.getComponentParams(c)["default"],h=b.$template.find("[data-app-component-id="+c+"] > .app-component-content section [mbr-gallery]").attr("mbr-gallery")||"images";d=b.Core.replaceSystemVariables(d[h].defaultImg,b.Core.getComponent(c));a=a?a:d?d:b.Core.replaceSystemVariables("@ADDON_DIR@_images/gallery/logo.jpg",b.Core.getComponent(c));k.videoPreview=a;e.css("background-image",'url("'+b.core2path(a)+'")')})}return c})},preparedComponentParams:function(){var c=
b.$componentsParams,e=b.$componentsParams.attr("data-component-id");0==b.Core.getComponent(e)._name.indexOf("gallery")&&a('<button class="btn btn-raised btn-primary">Set</button>').on("click",function(a){a.preventDefault();a.stopPropagation()}).insertAfter(c.find('[data-name="videoUrl"]'))},showedComponentParams:function(){var a=b.$componentsParams;a.find('[data-name="videoUrl"]').on("focus",function(b){a.find(".image-tabs .images").css({"pointer-events":"none",opacity:"0.4"})}).on("blur",function(){a.find(".image-tabs .images").css({"pointer-events":"inherit",
opacity:"1"})});var e=b.$componentsParams.attr("data-component-id"),d=b.$template.find("[data-app-component-id="+e+"] > .app-component-content section [mbr-gallery]").attr("mbr-gallery"),f=b.Core.getComponent(e)._params;if(0==b.Core.getComponent(e)._name.indexOf("gallery"))a.find("input").on("input",function(a){a.stopPropagation()});e=f[d];var g=a.find(".images li");e&&0<e.length&&e.map(function(a,c){a.playVideo&&(a=b.core2path(a.videoPreview),g.eq(c).css("background-image","url("+a+")"))})}}})},
["jQuery","mbrApp"]);
