var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,f,k){a instanceof String&&(a=String(a));for(var q=a.length,v=0;v<q;v++){var y=a[v];if(f.call(k,y,v,a))return{i:v,v:y}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,f,k){a!=Array.prototype&&a!=Object.prototype&&(a[f]=k.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,f,k,q){if(f){k=$jscomp.global;a=a.split(".");for(q=0;q<a.length-1;q++){var v=a[q];v in k||(k[v]={});k=k[v]}a=a[a.length-1];q=k[a];f=f(q);f!=q&&null!=f&&$jscomp.defineProperty(k,a,{configurable:!0,writable:!0,value:f})}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,k){return $jscomp.findInternal(this,a,k).v}},"es6","es3");
defineM(function(a,f,k){function q(c,e,b){var d=f.isAMP(),g=a(f.getComponentHTML(c)),h=g.find(".item"),m=g.find(".modal .carousel-item"),n=d?g.find(".dots"):g.find(".carousel-indicators li"),u=g.find(".img-prw-wrapper"),l=g.find("amp-state").attr("id"),p=g.find("amp-carousel").attr("id"),r=e+1,t=e+1;"string"!==typeof b&&b?1<=b.length&&a(b).each(function(x){var w=h.eq(e).clone();d&&w.find("amp-img").attr("src",b[x]);w.find("img").attr("src",b[x]);w.insertAfter(h.eq(e));n.eq(e).clone().insertAfter(n.eq(e));
w.is(".gallery-image")&&(w=m.eq(e).clone(),w.find("img").attr("src",b[x]),w.insertAfter(m.eq(e)));w=u.eq(e).clone();w.find("img").attr("src",b[x]);w.insertAfter(m.eq(e));if(b.length-1===x)if(h=g.find(".item"),m=g.find(".carousel-item"),n=d?g.find(".dots"):g.find(".carousel-indicators li"),u=g.find(".img-prw-wrapper"),m.each(function(b){0==b?a(this).addClass("active"):a(this).removeClass("active")}),h.each(function(b){d||(a(this).find("img").attr("data-slide-to",b),a(this).find("img").attr("data-bs-slide-to",
b))}),n.each(function(b){d?(a(this).find("dot").attr("data-amp-bind-class",l+".slide == "+r+' ? "current" : ""'),a(this).find("dot").attr("on","tap:"+p+".goToSlide(index="+r+")"),a(this).find("dot").removeClass("current")):(0==b?a(this).addClass("active"):a(this).removeClass("active"),a(this).attr("data-slide-to",b),a(this).attr("data-bs-slide-to",b))}),d&&u.each(function(b){a(this).find("dot").attr("data-amp-bind-class",l+".slide == "+r+' ? "current" : ""');a(this).find("dot").attr("on","tap:"+p+
".goToSlide(index="+r+")");a(this).find("dot").removeClass("current")}),f.setComponentHTML(c,g[0].outerHTML),1<b.length){var t=f.$template.find("[data-app-component-id="+c+"]").find("img"),z=0;t.each(function(){a(this).one("load",function(){z++;f.progressBar("show",k("Loading Images"),"",!0);f.progressBar(z+" / "+t.length);f.progressBar({progress:100/t.length*z},"","",!0);z===t.length&&(f.progressBar("hide"),f.hidePreloader())})})}else f.hidePreloader()}):(h.each(function(c){if(e==c){var m=a(this).clone().removeClass("active");
b&&m.find("amp-img").attr("src",b);b&&m.find("img").attr("src",b);m.insertAfter(a(this));d||(m.find("img").attr("data-slide-to",++c),m.find("img").attr("data-bs-slide-to",++c))}else!d&&e<c&&(a(h.find("img")[c]).attr("data-slide-to",++c),a(h.find("img")[c]).attr("data-bs-slide-to",++c))}),n.each(function(b){e==b?(b=a(this).clone().removeClass("active"),d?(b.find(".dot").attr("data-amp-bind-class",l+".slide == "+r+' ? "current" : ""'),b.find(".dot").attr("on","tap:"+p+".goToSlide(index="+r+")"),b.find(".dot").removeClass("current")):
(b.attr("data-slide-to",r),b.attr("data-bs-slide-to",r)),b.insertAfter(a(this))):b>=e&&1<h.length&&(r++,d?(a(this).find(".dot").attr("data-amp-bind-class",l+".slide == "+r+' ? "current" : ""'),a(this).find(".dot").attr("on","tap:"+p+".goToSlide(index="+r+")")):(a(this).attr("data-slide-to",r),a(this).attr("data-bs-slide-to",r)))}),m.each(function(c){e==c&&(c=a(this).clone(),b&&c.find("img").attr("src",b),c.insertAfter(a(this)),d||0!=e||c.removeClass("active"))}),f.isAMP()&&u.each(function(d){if(e==
d){var c=a(this).clone();b&&c.find("amp-img").attr("src",b);b&&c.find("img").attr("src",b);c.find("amp-img").attr("data-amp-bind-class",l+".slide == "+t+'? "selected":""');c.find("amp-img").attr("on","tap:"+p+".goToSlide(index="+t+")");c.find("amp-img").attr("tabindex",d);c.find("amp-img").removeClass("selected");c.insertAfter(a(this))}else d>=e&&1<h.length&&(t++,a(this).find("amp-img").attr("data-amp-bind-class",l+".slide == "+t+'? "selected":""'),a(this).find("amp-img").attr("on","tap:"+p+".goToSlide(index="+
t+")"),a(this).find("amp-img").attr("tabindex",d))}),f.setComponentHTML(c,g[0].outerHTML));mbrApp.Core.render(c)}function v(c,e,b){var d=a(f.getComponentHTML(c)),g=d.find(".item"),h=d.find(".img-prw-wrapper");""===b.image.link&&d.find("a img").each(function(){a(this).attr("src")===b.image.src&&a(this).closest("a").attr("href",b.image.link)});g.each(function(c){if(e==c){a(this).find("amp-img").attr("src",b.image.src);a(this).find("img").attr("src",b.image.src);a(this).find("img").attr("alt",b.image.alt);
if(b.image.link&&!b.image.lightbox)a(this).find("amp-img a").length?(a(this).find("amp-img a").attr("href",b.image.link),a(this).find("amp-img a").attr("target",b.image.linkInNewWindow?"_target":"_self"),a(this).find("amp-img").removeAttr("lightbox"),a(this).find("amp-img img").removeAttr("lightbox")):(c=a("<a>"),c.attr("href",b.image.link),c.attr("target",b.image.linkInNewWindow),a(this).find("img").parent().append(c),c.append(a(this).find("img")));else if(a(this).find("amp-img a").length){c=a(this).find("amp-img a");
var d=c.html();c.parent().append(d);c.remove()}b.image.lightbox?(a(this).find("amp-img").attr("lightbox",b.image.lightbox),a(this).find("img").attr("lightbox",b.image.lightbox)):(a(this).find("amp-img").removeAttr("lightbox"),a(this).find("img").removeAttr("lightbox"))}});h.each(function(c){e==c&&(a(this).find("amp-img").attr("src",b.image.src),a(this).find("img.mbr-temp").attr("src",b.image.src))});f.setComponentHTML(c,d[0].outerHTML);mbrApp.Core.render(c)}function y(c,e){a(f.getComponentHTML(c)).find(".item").each(function(b){e==
b&&(b=f.isAMP()?a(this).find("amp-img"):a(this).find("img"),b={image:{active:!0,alt:b.attr("alt"),src:b.attr("src"),width:b[0].naturalWidth}},f.showMediaImageDialog(b,function(a){a.image?q(c,e,a.image.src):1<=a.length&&(a.reverse(),q(c,e,a))},!1,!1,!0,c))})}function D(c,e){var b=a(f.getComponentHTML(c)),d=b.find(".item"),g=b.find(".modal .carousel-item"),h=b.find(".img-prw-wrapper");d.each(function(b){a(this).removeClass("active");b==e?(e==d.length-1?a(this).insertBefore(d.first()):a(this).insertAfter(a(this).next()),
e==d.length-1&&g&&!f.isAMP()?(a(g[b]).insertBefore(g.first()),g.first().removeClass("active"),g.last().addClass("active")):g&&!f.isAMP()&&a(g[b]).insertAfter(a(g[b]).next()),f.isAMP()||(a(d[e]).find("img").attr("data-slide-to",e+1),a(d[e]).find("img").attr("data-bs-slide-to",e+1),e!=d.length-1&&a(d[e+1]).find("img").attr("data-slide-to",e),e!=d.length-1&&a(d[e+1]).find("img").attr("data-bs-slide-to",e))):f.isAMP()||e!=d.length-1||(a(d[b]).find("img").attr("data-slide-to",b),a(d[b]).find("img").attr("data-bs-slide-to",
b))});d=b.find(".item");a(d[0]).addClass("active");h.each(function(b){b==e&&(e==h.length-1?a(this).insertBefore(h.first()):a(this).insertAfter(a(this).next()))});h.find("amp-img").each(function(b,c){a(c).attr("on",a(c).attr("on").replace(/\(index=\d+\)/,"(index="+b+")"));a(c).attr("data-amp-bind-class",a(c).attr("data-amp-bind-class").replace(/slide == \d+\?/,"slide == "+b+"?"));a(c).attr("tabindex",b)});f.setComponentHTML(c,b[0].outerHTML);mbrApp.Core.render(c)}function E(c,e){var b=a(f.getComponentHTML(c)),
d=b.find(".item"),g=b.find(".modal .carousel-item"),h=b.find(".img-prw-wrapper");d.each(function(b){a(this).removeClass("active");b==e?(0==e?a(this).insertAfter(d.last()):a(this).insertBefore(a(this).prev()),0==e&&g&&!f.isAMP()?a(g[b]).insertAfter(g.last()):g&&!f.isAMP()&&a(g[b]).insertBefore(a(g[b]).prev()),2>e&&g&&!f.isAMP()&&(g.first().removeClass("active"),a(g[1]).addClass("active")),f.isAMP()||(0!=e&&a(d[e]).find("img").attr("data-slide-to",e-1),0!=e&&a(d[e]).find("img").attr("data-bs-slide-to",
e-1),a(d[e-1]).find("img").attr("data-slide-to",e),a(d[e-1]).find("img").attr("data-bs-slide-to",e))):f.isAMP()||0!=e||(a(d[b]).find("img").attr("data-slide-to",b),a(d[b]).find("img").attr("data-bs-slide-to",b))});d=b.find(".item");a(d[0]).addClass("active");h.each(function(b){b==e&&(0==e?a(this).insertAfter(h.last()):a(this).insertBefore(a(this).prev()))});h.find("amp-img").each(function(b,c){a(c).attr("on",a(c).attr("on").replace(/\(index=\d+\)/,"(index="+b+")"));a(c).attr("data-amp-bind-class",
a(c).attr("data-amp-bind-class").replace(/slide == \d+\?/,"slide == "+b+"?"));a(c).attr("tabindex",b)});f.setComponentHTML(c,b[0].outerHTML);mbrApp.Core.render(c)}function F(c,e){var b=a(f.getComponentHTML(c)),d=b.find(".item"),g=b.find(".modal .carousel-item"),h=b.find(".dots"),m=b.find(".img-prw-wrapper"),n=b.find("amp-state").attr("id"),u=b.find("amp-carousel").attr("id"),l=e+1,p=e+1;d.each(function(b){b==e&&1<d.length&&(a(this).remove(),f.isAMP()||(0==b&&(a(d[1]).addClass("active"),a(g[1]).addClass("active")),
a(g[b]).remove()));1>=d.length&&f.alertDlg(k("This element is the last. It cannot be removed."))});f.isAMP()?h.each(function(b){b==e&&1<d.length?(a(this).remove(),l--):b>=e&&1<d.length&&(a(this).find(".dot").attr("data-amp-bind-class",n+".slide == "+l+' ? "current" : ""'),a(this).find(".dot").attr("on","tap:"+u+".goToSlide(index="+l+")"),l++)}):1<d.length&&b.find(".carousel-indicators li").last().remove();m.each(function(b){b==e&&1<d.length?(a(this).remove(),p--):b>=e&&1<d.length&&(a(this).find("amp-img").attr("data-amp-bind-class",
n+".slide == "+p+'? "selected":""'),a(this).find("amp-img").attr("on","tap:"+u+".goToSlide(index="+p+")"),a(this).find("amp-img").attr("tabindex",p),p++)});f.setComponentHTML(c,b[0].outerHTML);mbrApp.Core.render(c)}function I(c){if(a(c.currentTarget).is(".item")){var e=a(c.currentTarget).find(".item-wrapper"),b=a('<div class="item-menu-overlay">'),d=a(c.target).parents(".app-component").attr("data-app-component-id"),g=a('<div class="btn-wrapper">'),h;a(c.currentTarget).parent().parent().find(".item").each(function(a){c.currentTarget==
this&&(h=a)});var f=a('<span class="mbr-icon-trash ctrl-btn"><span class="tooltiptext">'+k("Remove")+"</span></span>").click(function(a){a.stopPropagation();a.preventDefault();F(d,h)}),n=a('<span class="mbr-icon-plus ctrl-btn"><span class="tooltiptext">'+k("Add Copy")+"</span></span>").click(function(a){a.stopPropagation();a.preventDefault();q(d,h)}),u=a('<span class="mbr-icon-plus ctrl-btn"><span class="tooltiptext">'+k("Add Items")+"</span></span>").click(function(a){a.stopPropagation();a.preventDefault();
y(d,h)}),l=a('<span class="mbr-icon-arrow-right ctrl-btn"><span class="tooltiptext">'+k("Move Right")+"</span></span>").click(function(a){a.stopPropagation();a.preventDefault();D(d,h)}),p=a('<span class="mbr-icon-arrow-left ctrl-btn"><span class="tooltiptext">'+k("Move Left")+"</span></span>").click(function(a){a.stopPropagation();a.preventDefault();E(d,h)});if(a(c.currentTarget).is(".item.shop-image")){var r=a('<span class="mbr-icon-pencil ctrl-btn"><span class="tooltiptext">'+k("Edit")+"</span></span>").click(function(a){return A(a,
d,h)});b.append(g.append(r).append(p).append(l).append(f).append(n));b.click(function(a){return A(a,d,h)})}a(c.currentTarget).is(".item.shop-image")&&a(c.currentTarget).find(".item-menu-overlay").click(function(a){return A(a,d,h)});a(c.currentTarget).is(".item.features-image")&&b.append(g.append(p).append(l).append(f).append(u));a(c.currentTarget).is(".item.features-without-image")&&b.append(g.append(p).append(l).append(f).append(n));a(c.currentTarget).is(".item.gallery-image")&&b.append(g.append(p).append(l).append(f).append(u));
if(a(c.currentTarget).is(".item.slider-image")){var t=!1;b.mousemove(function(a){return t=!0});b.mousedown(function(a){a.preventDefault();t=!1});b.mouseup(function(a){t||0!==a.button||b.click(function(a){return J(d,h)});t=!1})}0===e.find(".item-menu-overlay").length&&e.append(b);b.fadeTo(200,1);a(c.currentTarget).one("mouseleave",function(){b.fadeTo(200,0,function(){a(b).remove()})})}}function J(c){if(c){var e=f.theme.name,b=f.getComponent(c)._sourceTheme,d=f.getAddonDir(b||e);e=a(f.getComponentHTML(c)).find("img").each(function(){0===
a(this).attr("src").search("../../")?a(this).attr("src",a(this).attr("src").replace("../../","")):0===a(this).attr("src").search("../")?a(this).attr("src",Bridge.path2app(d)+"/components"+a(this).attr("src").replace("..","")):a(this).attr("src",a(this).attr("src").replace(f.path2core(d),Bridge.path2app(d)))});var g=a('<div class="row">'),h=a('<div class="col-md-4 item"><div class="item-wrapper"><img>');e.each(function(){var b=h.clone();b.find("img").attr("src",a(this).attr("src"));b.find("img").attr("data-text",
a(this).find("span").html());b.find("img").attr("alt",a(this).attr("alt"));a(this).find("a")&&(b.find("img").attr("data-link",a(this).parent().attr("href")),b.find("img").attr("data-window","target"==a(this).find("a").attr("target")?!0:!1));a(this).attr("lightbox")&&b.find("img").attr("data-lb",a(this).attr("lightbox"));g.append(b)});e=f.showDialog({title:k("Slides"),size:"large",className:"note-air-layout item-wizard-slides",body:'<div class="gallery-wrapper">'+g[0].outerHTML,successLabel:"Ok",success:function(){}});
B(e,c);C(e,c)}}function C(c,e){if(c&&e){var b=c.is("img")?c:a(c).find("img"),d;b.on("click",function(a){for(var c=0;c<b.length;c++)a.currentTarget==b[c]&&(d=c);G(a.currentTarget,!1,e,d,!0)})}}function B(c,e){var b;(a(c).is(".item-wrapper")?a(c):a(c).find(".item-wrapper")).on("mouseenter",function(c){var d=a(c.currentTarget),h=a('<div class="item-menu-overlay">');c=a('<div class="btn-wrapper">');d.parents(".row").find(".item").each(function(c,e){0!==a(e).has(d).length&&(b=c)});var m=a('<span class="mbr-icon-trash ctrl-btn"><span class="tooltiptext">'+
k("Remove")+"</span></span>").click(function(c){var d=b;c=a(c.target).parents(".item");1>=c.parent().find(".item").length?f.alertDlg("This element is the last. It cannot be removed."):c.remove();F(e,d)}),n=a('<span class="mbr-icon-plus ctrl-btn"><span class="tooltiptext">'+k("Add Items")+"</span></span>").click(function(a){return G(a.currentTarget,!0,e,b)}),u=a('<span class="mbr-icon-arrow-right ctrl-btn"><span class="tooltiptext">'+k("Move Right")+"</span></span>").click(function(a){return K(a,e,
b)}),l=a('<span class="mbr-icon-arrow-left ctrl-btn"><span class="tooltiptext">'+k("Move Left")+"</span></span>").click(function(a){return L(a,e,b)});h.append(c.append(l).append(u).append(m).append(n));0==d.find(".item-menu-overlay").length&&d.append(h);h.fadeTo(200,1);d.one("mouseleave",function(){h.fadeTo(200,0,function(){a(h).remove()})})})}function G(c,e,b,d,g){var h=a(c).parents(".item").find("img"),m={image:{active:!0,alt:h.attr("alt"),src:Bridge.path2app(Bridge.path2app(h.attr("src"))),width:h[0].naturalWidth}};
a(c).attr("data-link")&&(m.image.link=a(c).attr("data-link"),m.image.linkInNewWindow=a(c).attr("data-window"),m.image.lightbox=!1);a(c).attr("data-lb")&&(m.image.lightbox=!0);f.showMediaImageDialog(m,function(c){if(c.image)if(e)e&&H(h[0],c.image.src,b,d);else{var g=a(h[0]).parents(".item");g.find("img").attr("src",f.core2abs(c.image.src));g.find("img").attr("alt",c.image.alt);c.image.link?(g.find("img").attr("data-link",c.image.link),g.find("img").attr("data-window",c.image.linkInNewWindow)):(g.find("img").removeAttr("data-link"),
g.find("img").removeAttr("data-window"));c.image.lightbox?g.find("img").attr("data-lb",c.image.lightbox):g.find("img").removeAttr("data-lb");v(b,d,c)}else 1<=c.length&&(c.reverse(),H(h[0],c,b,d))},!1,!1,e,b,g)}function H(c,e,b,d){var g=a(c).parents(".item");if("string"===typeof e)c=g.clone(),c.find("img").attr("src",f.core2abs(e)),B(c,b,d),C(c.find("img")),c.find(".item-menu-overlay").remove(),c.insertAfter(g);else if(1<=e.length){var h=[];a(e).each(function(a){var c=g.clone();c.find("img").attr("src",
e[a]);B(c,b,d);C(c.find("img"));c.find(".item-menu-overlay").remove();h.push(c)});h.length&&g.after(h)}q(b,d,e)}function K(c,e,b){var d=a(c.target).parents(".item"),g=a(c.target).parents().find(".item");g.each(function(a,b){d[0]==b&&(a==g.length-1?d.insertBefore(g.first()):d.insertAfter(d.next()))});D(e,b)}function L(c,e,b){var d=a(c.target).parents(".item"),g=a(c.target).parents().find(".item");g.each(function(a,b){d[0]==b&&(0==a?d.insertAfter(g.last()):d.insertBefore(d.prev()))});E(e,b)}function A(c,
e,b){var d=a(c.currentTarget).parents(".item").parent().find("amp-lightbox");d.each(function(c){c==b&&(a(this).removeAttr("hidden"),a(this).find("div.placeholder").attr("hidden",!0))});d.find(".close").click(function(c){c=a(f.getComponentHTML(e));var g=c.find("amp-lightbox"),m=c.find(".item-wrapper amp-img"),k=c.find(".item-wrapper");g.each(function(c,d){m.each(function(e){if(b==c&&c==e){e=a(d).find("amp-img img.mbr-temp")[0].naturalHeight;var g=a(d).find("amp-img img.mbr-temp")[0].naturalWidth;e&&
g||(e=9,g=16);a(this).attr("src",a(d).find("amp-img img").attr("src"));a(this).attr("alt",a(d).find("amp-img").attr("alt"));a(this).attr("height",e);a(this).attr("width",g);a(this).find("img").attr("src",a(d).find("amp-img img").attr("src"))}});k.each(function(e){b==c&&c==e&&(a(this).find(".item-title").html(a(d).find(".item-box-title").html()),a(this).find(".cur").html(a(d).find(".cur").html()),a(this).find(".item-price").html(a(d).find(".item-box-price").html()),a(this).find(".item-text").html(a(d).find(".item-box-text").html()),
a(this).find("a.btn").html(a(d).find("a.btn").html()),a(d).find("a.btn").attr("href")&&a(this).find("a.btn").attr("href",a(d).find("a.btn").attr("href")))})});d.attr("hidden",!0);d.find("div.placeholder").removeAttr("hidden");f.setComponentHTML(e,c[0].outerHTML)})}f.addCoreResource("web/app/includes/item-wizard.css");f.addAppResource("web/app/includes/item-wizard.css");f.regExtension({name:"item-wizard",events:{load:function(){f.$template.on("mouseenter",".item",function(a){I(a);a.stopPropagation();
a.preventDefault()});f.Core.on("loadedComponent",function(c,e,b,d){var g=this;if(f.isAMP()){var h=a(b).find("[data-app-component-id="+c._id+"]"),k=h.find(".dots-wrapper span");for(c=0;c<k.length;c++)a(k[c]).on("click",function(b){h.find(".i-amphtml-slide-item");var c=h.find(".amp-lightbox-carousel amp-carousel .i-amphtml-slides-container > div");c.each(function(){a(this).addClass("hidden-slide").removeClass("visible-slide")});b=k.index(b.target);a(c[b]).addClass("visible-slide").removeClass("hidden-slide");
k.each(function(b){a(this).removeClass("current")});a(this).addClass("current")});c=h.find(".amp-lightbox-carousel amp-carousel .amp-carousel-button-next");e=h.find(".amp-lightbox-carousel amp-carousel .amp-carousel-button-prev");c.click(function(b){b=h.find(".i-amphtml-slide-item");var c=b.length,d=h.find(".dot"),e=h.find(".preview-wrapper amp-img");b.each(function(b,d){a(d).is(".visible-slide, .hidden-slide")&&a(d).removeClass("visible-slide").removeClass("hidden-slide");b=a(d).attr("style").replace(/\d/,
function(a){return a=parseInt(a,10)+1});parseInt(b.match(/\d/),10)>c?b=1:1>parseInt(b.match(/\d/),10)&&(b=c);a(g).attr("style",b)});e.each(function(b,c){a(c).removeClass("selected")});d.each(function(b,c){a(c).removeClass("current")});for(l=0;l<c;l++)if(a(b[l]).find('[aria-hidden="false"]').length){var f=1;f=l+2>c?1:l+2;a(d[f-1]).addClass("current");a(e[f-1]).addClass("selected")}});e.click(function(b){b=h.find(".i-amphtml-slide-item");var c=b.length,d=h.find(".dot"),e=h.find(".preview-wrapper amp-img");
b.each(function(b,d){a(d).is(".visible-slide, .hidden-slide")&&a(d).removeClass("visible-slide").removeClass("hidden-slide");b=a(d).attr("style").replace(/\d/,function(a){return a=parseInt(a,10)-1});parseInt(b.match(/\d/),10)>c?b=1:1>parseInt(b.match(/\d/),10)&&(b=c);a(g).attr("style",b)});e.each(function(b,c){a(c).removeClass("selected")});d.each(function(b,c){a(c).removeClass("current")});for(l=0;l<b.length;l++)if(a(b[l]).find('[aria-hidden="false"]').length){var f=1;f=0>l-1?b.length:l;a(d[f-1]).addClass("current");
a(e[f-1]).addClass("selected")}});for(var n=h.find(".preview-wrapper amp-img"),q=h.find(".i-amphtml-slide-item"),l=0;l<n.length;l++)a(n[l]).on("click",function(b){q.each(function(b,c){a(c).is(".visible-slide, .hidden-slide")&&a(c).removeClass("visible-slide").removeClass("hidden-slide")});n.each(function(){a(this).removeClass("selected")});a(this).addClass("selected")})}d&&(f.isAMP()?(b.find("section .amp-shop").each(function(b){a(this).find(".item").each(function(c){var d=/:((.*?)(?:-(\d)-(\d))?)(?:$|\.)/;
a(this).attr("on").match(d);d=a(this).attr("on").match(d)[2];a(this).attr("on","tap:"+d+"-"+b+"-"+c);a(this).find("amp-lightbox").attr("id",d+"-"+b+"-"+c);a(this).find("button.close").attr("on","tap:"+d+"-"+b+"-"+c+".close")})}),b.find("section.amp-lightbox-carousel").each(function(b,c){a(c).find("amp-carousel").find(".img-prw-wrapper amp-img").each(function(b){a(this).attr("data-amp-bind-class",a(this).attr("data-amp-bind-class").replace(/== \d+ \?|==\d+\?/gm,"== "+b+" ?"));a(this).attr("tabindex",
b);a(this).attr("on",a(this).attr("on").replace(/index=\d+/gm,"index="+b))})})):(b=b.find("section .mbr-gallery").parent(),b.length&&b.each(function(b,c){f.getUID(3,{timePrefix:!0});f.getUID(3,{timePrefix:!0});var d=[];a(c).find(".row img").each(function(b,c){a(c).attr("data-slide-to",b).attr("data-bs-slide-to",b);b=0===c.src.indexOf(Bridge.base)?c.src.replace(Bridge.base,"../../"):c.src;d.push(b)});a(c).find(".carousel img").each(function(b,c){a(c).attr("src",d.shift())});a(c).find(".carousel li").each(function(b,
c){a(c).attr("data-slide-to",b).attr("data-bs-slide-to",b)})})))})}}})},["jQuery","mbrApp","TR()"]);
