var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.owns=function(a,c){return Object.prototype.hasOwnProperty.call(a,c)};$jscomp.assign="function"==typeof Object.assign?Object.assign:function(a,c){for(var b=1;b<arguments.length;b++){var d=arguments[b];if(d)for(var e in d)$jscomp.owns(d,e)&&(a[e]=d[e])}return a};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){a!=Array.prototype&&a!=Object.prototype&&(a[c]=b.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,c,b,d){if(c){b=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in b||(b[e]={});b=b[e]}a=a[a.length-1];d=b[a];c=c(d);c!=d&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})}};$jscomp.polyfill("Object.assign",function(a){return a||$jscomp.assign},"es6","es3");
var defaultOptions$$module$C_$hudson$workspace$Mobirise5_ewin_Release$Release$release$win_ia32_unpacked$resources$_app_asar$web$app$themes$startm5$plugins$as_pie_progress$sources$index={colorCircle:!1,colorSlice:"#00a1ff",end:264,fontColor:"#365b74",fontSize:"1.6rem",fontWeight:400,lineargradient:!1,number:!0,opacity:10,round:!1,size:200,stroke:10};
function toFixed$$module$C_$hudson$workspace$Mobirise5_ewin_Release$Release$release$win_ia32_unpacked$resources$_app_asar$web$app$themes$startm5$plugins$as_pie_progress$sources$index(a,c){return a.toString().match(new RegExp("^-?\\d+(?:.\\d{0,"+(c||-1)+"})?"))[0]}
function polarToCartesian$$module$C_$hudson$workspace$Mobirise5_ewin_Release$Release$release$win_ia32_unpacked$resources$_app_asar$web$app$themes$startm5$plugins$as_pie_progress$sources$index(a,c,b,d){d=(d-90)*Math.PI/180;return{x:a+b*Math.cos(d),y:c+b*Math.sin(d)}}
function describeArc$$module$C_$hudson$workspace$Mobirise5_ewin_Release$Release$release$win_ia32_unpacked$resources$_app_asar$web$app$themes$startm5$plugins$as_pie_progress$sources$index(a,c,b,d,e){var f=polarToCartesian$$module$C_$hudson$workspace$Mobirise5_ewin_Release$Release$release$win_ia32_unpacked$resources$_app_asar$web$app$themes$startm5$plugins$as_pie_progress$sources$index(a,c,b,e);a=polarToCartesian$$module$C_$hudson$workspace$Mobirise5_ewin_Release$Release$release$win_ia32_unpacked$resources$_app_asar$web$app$themes$startm5$plugins$as_pie_progress$sources$index(a,
c,b,d);d=180>=e-d?"0":"1";return["M",toFixed$$module$C_$hudson$workspace$Mobirise5_ewin_Release$Release$release$win_ia32_unpacked$resources$_app_asar$web$app$themes$startm5$plugins$as_pie_progress$sources$index(f.x,5),f.y,"A",b,b,0,d,0,a.x,a.y].join(" ")}
var CircularProgressBar$$module$C_$hudson$workspace$Mobirise5_ewin_Release$Release$release$win_ia32_unpacked$resources$_app_asar$web$app$themes$startm5$plugins$as_pie_progress$sources$index=function(a){this.pieName=a;this.svg="http://www.w3.org/2000/svg";a=document.querySelectorAll("."+a);a=[].slice.call(a);a.map(function(a,b){a.setAttribute("data-index",b+1)});this.initial(a)};
CircularProgressBar$$module$C_$hudson$workspace$Mobirise5_ewin_Release$Release$release$win_ia32_unpacked$resources$_app_asar$web$app$themes$startm5$plugins$as_pie_progress$sources$index.prototype.initial=function(a){if("IntersectionObserver"in window){var c=new IntersectionObserver(function(a,c){a.map(function(a){a.isIntersecting&&.75<a.intersectionRatio&&(this.createSvg(a.target),c.unobserve(a.target))})},{root:null,rootMargin:"0px",threshold:1});a.map(function(a){c.observe(a)})}else a.map(function(a){this.createSvg(a)})};
CircularProgressBar$$module$C_$hudson$workspace$Mobirise5_ewin_Release$Release$release$win_ia32_unpacked$resources$_app_asar$web$app$themes$startm5$plugins$as_pie_progress$sources$index.prototype.hex2rgb=function(a,c){c=void 0===c?10:c;a="string"===typeof a?parseInt(a.replace("#",""),16):a;return"rgba("+(a>>16)+", "+((a&65280)>>8)+", "+(a&255)+", "+c/100+")"};
CircularProgressBar$$module$C_$hudson$workspace$Mobirise5_ewin_Release$Release$release$win_ia32_unpacked$resources$_app_asar$web$app$themes$startm5$plugins$as_pie_progress$sources$index.prototype.progressBar=function(a,c,b){var d=b.index,e=b.stroke,f=b.round,k=b.lineargradient,h=b.colorSlice,l=b.colorCircle,g=b.opacity,m=b.size;b.number&&a.appendChild(this.percentElement(b));a=document.querySelector("."+this.pieName+"-circle-"+d);this.setAttr(a,{fill:"none",transform:"rotate(0, 50, 50)","stroke-width":e,
"stroke-linecap":f?"round":""},!1);this.animationTo(Object.assign({},b,{element:a}),!0);a.setAttribute("stroke",k?"url(#linear-"+d+")":h);b=l?"":"border-radius:50%;box-shadow:inset 0px 0px "+e+"px "+e+"px "+this.hex2rgb(h,g);c.setAttribute("style","width:"+m+"px;height:"+m+"px;position:relative;"+b)};
CircularProgressBar$$module$C_$hudson$workspace$Mobirise5_ewin_Release$Release$release$win_ia32_unpacked$resources$_app_asar$web$app$themes$startm5$plugins$as_pie_progress$sources$index.prototype.animationTo=function(a,c){function b(){f>=k.percent?g--:g++;l=requestAnimationFrame(b);e.setAttribute("stroke-dasharray",2.64*g+", 20000");e.setAttribute("d",describeArc$$module$C_$hudson$workspace$Mobirise5_ewin_Release$Release$release$win_ia32_unpacked$resources$_app_asar$web$app$themes$startm5$plugins$as_pie_progress$sources$index(50,
50,42,0,3.6*g));h&&k.number&&(h.textContent=g+"%");g===d&&(e.setAttribute("data-angel",g),cancelAnimationFrame(l))}c=void 0===c?!1:c;var d=Math.round(a.percent),e=document.querySelector("."+this.pieName+"-circle-"+a.index);if(e){var f=JSON.parse(e.getAttribute("data-angel")),k=c?a:Object.assign({},defaultOptions$$module$C_$hudson$workspace$Mobirise5_ewin_Release$Release$release$win_ia32_unpacked$resources$_app_asar$web$app$themes$startm5$plugins$as_pie_progress$sources$index,a),h=document.querySelector("."+
this.pieName+"-percent-"+a.index);0==d&&h&&k.number&&(h.textContent="0%",e.setAttribute("stroke-dasharray","0, 20000"));if(!(100<d||0>=d||f===d)){var l,g=c?0:f;requestAnimationFrame(b)}}};
CircularProgressBar$$module$C_$hudson$workspace$Mobirise5_ewin_Release$Release$release$win_ia32_unpacked$resources$_app_asar$web$app$themes$startm5$plugins$as_pie_progress$sources$index.prototype.percentElement=function(a){var c=a.index,b=a.fontSize,d=a.fontWeight;a=a.fontColor;var e=document.createElementNS(this.svg,"text");this.setAttr(e,{class:this.pieName+"-percent-"+c+" pie_progress__number",x:"50%",y:"50%","font-size":b,"font-weight":d,fill:a,"text-anchor":"middle","dominant-baseline":"central"},
!1);return e};
CircularProgressBar$$module$C_$hudson$workspace$Mobirise5_ewin_Release$Release$release$win_ia32_unpacked$resources$_app_asar$web$app$themes$startm5$plugins$as_pie_progress$sources$index.prototype.createSvg=function(a){if(!a.querySelector("svg")){var c=JSON.parse(a.getAttribute("data-pie")),b=a.getAttribute("data-index");c=Object.assign({},defaultOptions$$module$C_$hudson$workspace$Mobirise5_ewin_Release$Release$release$win_ia32_unpacked$resources$_app_asar$web$app$themes$startm5$plugins$as_pie_progress$sources$index,c,
{index:b});b=document.createElementNS(this.svg,"svg");this.setAttr(b,{width:c.size,height:c.size,viewBox:"0 0 100 100"},!1);c.colorCircle&&b.appendChild(this.circleSvg(c,"bottom"));c.lineargradient&&b.appendChild(this.gradient(c));b.appendChild(this.circleSvg(c,"top",!0));a.appendChild(b);this.progressBar(b,a,c)}};
CircularProgressBar$$module$C_$hudson$workspace$Mobirise5_ewin_Release$Release$release$win_ia32_unpacked$resources$_app_asar$web$app$themes$startm5$plugins$as_pie_progress$sources$index.prototype.gradient=function(a){var c=a.index;a=a.lineargradient;var b=document.createElementNS(this.svg,"defs"),d=document.createElementNS(this.svg,"linearGradient");d.id="linear-"+c;var e=[].slice.call(a);b.appendChild(d);var f=0;e.map(function(a){var b=document.createElementNS(this.svg,"stop");this.setAttr(b,{offset:f+
"%","stop-color":""+a},!1);d.appendChild(b);f+=100/(e.length-1)});return b};
CircularProgressBar$$module$C_$hudson$workspace$Mobirise5_ewin_Release$Release$release$win_ia32_unpacked$resources$_app_asar$web$app$themes$startm5$plugins$as_pie_progress$sources$index.prototype.circleSvg=function(a,c,b){var d=a.index,e=a.colorCircle,f=a.stroke;b=void 0===b?!1:b;a=document.createElementNS(this.svg,"top"===c?"path":"ellipse");e={fill:"none",stroke:e,"stroke-width":f};d="top"===c?{class:this.pieName+"-circle-"+d}:e;c="top"===c?{d:describeArc$$module$C_$hudson$workspace$Mobirise5_ewin_Release$Release$release$win_ia32_unpacked$resources$_app_asar$web$app$themes$startm5$plugins$as_pie_progress$sources$index(50,
50,42,0,0),"shape-rendering":"geometricPrecision","data-angle":b?0:"",style:"stroke-width: 5px !important;",typeCircle:Object.assign({},d)}:{rx:42,ry:42,cx:50,cy:50,style:"stroke-width: 5px !important;",typeCircle:Object.assign({},d)};this.setAttr(a,c,!1);return a};
CircularProgressBar$$module$C_$hudson$workspace$Mobirise5_ewin_Release$Release$release$win_ia32_unpacked$resources$_app_asar$web$app$themes$startm5$plugins$as_pie_progress$sources$index.prototype.setAttr=function(a,c,b){b=void 0===b?!1:b;for(var d in c)b?a.setAttributeNS(null,d,c[d]):a.setAttribute(d,c[d])};
var $jscompDefaultExport$$module$C_$hudson$workspace$Mobirise5_ewin_Release$Release$release$win_ia32_unpacked$resources$_app_asar$web$app$themes$startm5$plugins$as_pie_progress$sources$index=CircularProgressBar$$module$C_$hudson$workspace$Mobirise5_ewin_Release$Release$release$win_ia32_unpacked$resources$_app_asar$web$app$themes$startm5$plugins$as_pie_progress$sources$index,module$C_$hudson$workspace$Mobirise5_ewin_Release$Release$release$win_ia32_unpacked$resources$_app_asar$web$app$themes$startm5$plugins$as_pie_progress$sources$index=
{};module$C_$hudson$workspace$Mobirise5_ewin_Release$Release$release$win_ia32_unpacked$resources$_app_asar$web$app$themes$startm5$plugins$as_pie_progress$sources$index.default=$jscompDefaultExport$$module$C_$hudson$workspace$Mobirise5_ewin_Release$Release$release$win_ia32_unpacked$resources$_app_asar$web$app$themes$startm5$plugins$as_pie_progress$sources$index;
