var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,c,b){a instanceof String&&(a=String(a));for(var f=a.length,g=0;g<f;g++){var h=a[g];if(c.call(b,h,g,a))return{i:g,v:h}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){a!=Array.prototype&&a!=Object.prototype&&(a[c]=b.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,c,b,f){if(c){b=$jscomp.global;a=a.split(".");for(f=0;f<a.length-1;f++){var g=a[f];g in b||(b[g]={});b=b[g]}a=a[a.length-1];f=b[a];c=c(f);c!=f&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})}};$jscomp.polyfill("Array.prototype.findIndex",function(a){return a?a:function(a,b){return $jscomp.findInternal(this,a,b).i}},"es6","es3");
$jscomp.polyfill("Object.is",function(a){return a?a:function(a,b){return a===b?0!==a||1/a===1/b:a!==a&&b!==b}},"es6","es3");$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(a,b){var c=this;c instanceof String&&(c=String(c));var g=c.length;b=b||0;for(0>b&&(b=Math.max(b+g,0));b<g;b++){var h=c[b];if(h===a||Object.is(h,a))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,c,b){if(null==a)throw new TypeError("The 'this' value for String.prototype."+b+" must not be null or undefined");if(c instanceof RegExp)throw new TypeError("First argument to String.prototype."+b+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(a,b){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,b||0)}},"es6","es3");
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,b){return $jscomp.findInternal(this,a,b).v}},"es6","es3");
(function(a){var c=function(){this.$body=a("body");this.$window=a(window);this.$document=a(document);this.$template=a(".template > div");this.components={};this.currentPage="index.html";this.resultJSON={"index.html":{settings:{main:!0,title:"Home",meta_descr:"",header_custom:"",footer_custom:"",html_before:""},components:[]}};(this.isMobile=/android|webos|iphone|ipad|ipod|blackberry|iemobile|opera mini|mobirise-webview/i.test(navigator.userAgent.toLowerCase()))&&a("html").addClass("device")},b=0;
c.prototype.uniqNum=function(){return b++};c.prototype.resetUniqNum=function(){b=0};this.uniqCompNum=0;c.prototype.getUniqCompName=function(){return(this.uniqCompNum++).toString(36)};var f={},g={};c.prototype.on=function(d,k){if(a.isArray(d))for(var e in d)this.on(d[e],k);else g[d]?k&&k.apply(this,g[d]):(f[d]||(f[d]=[])).push(k)};c.prototype.off=function(d,a){if(!f[d])return!1;if(a)for(var e=0;e<f[d].length;e++)f[d][e]===a&&(f[d][e]=void 0);else delete f[d]};c.prototype.fire=function(d){var a=[].slice.call(arguments,
1);if("undefined"!==typeof f[d])for(var e in f[d])if(f[d][e])try{f[d][e].apply(this,a)}catch(l){console.error("Error in event handler mbrAppCore::"+d),console.log(l)}};c.prototype.fireOnce=function(d){if(!(d in g)){var a=[].slice.call(arguments,1);g[d]=a;for(var e in f[d])if(f[d][e])try{f[d][e].apply(this,a),f[d][e]=void 0}catch(l){console.error("Error in event handler mbrAppCore::"+d,l)}}};var h={};c.prototype.addFilter=function(a,b){(h[a]||(h[a]=[])).push(b)};c.prototype.applyFilter=function(a){var d=
[].slice.call(arguments,1);if(h[a])for(var e=h[a],b=0,c=e.length;b<c;b++)d[0]=e[b].apply(this,d),"undefined"==typeof d[0]&&console.warn("handle of "+a+" filter return undefined: ",e[b]);return d[0]};var m={};c.prototype.regExtension=c.prototype.registerExtension=function(a){if(!a.name||"undefined"!==typeof m[a.name])return!1;m[name]=a;if(a.global)for(var d in a.global)d in this?console.error("Error re-definition method mbrAppCore."+d+" by module "+a.name):this[d]=a.global[d];if(a.events)for(var e in a.events)this.on(e,
a.events[e]);return!0};c.prototype.getResultProject=function(){var d=a.extend(!0,{},this.resultJSON),b;for(b in d){var e=d[b],c=e.components,f=c.findIndex(function(a){return a._name.includes("menu")&&a._once&&a._global});-1!==f&&f&&c.unshift(c.splice(f,1)[0]);delete e.components;e=this.cleanJSONPlease(e);e.components=c;for(e=0;e<c.length;e++)this.isSecondaryComponent(c[e])?c[e]=this.transformSecondaryComponentForProject(c[e]):c[e]=this.cleanJSONPlease(c[e])}return{settings:{currentPage:this.currentPage,
uniqCompNum:this.uniqCompNum},pages:d}};c.prototype.getResultHTML=function(d,c){var e=this;if(!e.resultJSON[d]||!e.resultJSON[d].components)return!1;if("undefined"!==typeof c){var b=e.getComponent(c,d),f=e.prepareComponent(b);f=a("<div>").append(f);e.loadEachComponent(b,f,e.resultJSON[d],d,!0);e.isSecondaryComponent(b)&&e.getSecondaryComponent(b);return a.Deferred().resolve(f.find("[data-app-component-id="+c+"] .app-component-content"))}c=e.resultJSON[d].components;f=e.prepareAllComponents(c);var g=
a("<div>").append(f);for(b in c)e.loadEachComponent(c[b],g,e.resultJSON[d],d,!0),e.isSecondaryComponent(c[b])&&e.getSecondaryComponent(c[b]);return function(){function c(g){if(g<b.length){var k=a(b[g]).attr("data-app-component-id");k=e.getComponent(k,d);e.applyFilter("getResultComponent",a.Deferred().resolve(a(b[g]).find(".app-component-content"),k,d)).then(function(a,d,b){a=e.cleanHTMLplease(a.html());a=e.applyFilter("getResultHTMLcomponent",a,d,b);h+=a+"\n\n";c(++g)},function(a){APP.showError(a)})}else f.resolve(h)}
var b=g.find("[data-app-component-id]"),f=a.Deferred(),h="";c(0);return f.promise()}()};c.prototype.loadProject=function(a){var b=this;if(!a||!a.pages||"object"!=typeof a.pages)return console.error("Error: project has no pages"),!1;this.uniqCompNum=a.settings.uniqCompNum||0;return this.loadPage(a.settings.currentPage,a).always(function(){b.resultJSON=a&&a.pages||{};b.currentPage=a&&a.settings&&a.settings.currentPage||""}).then(function(){b.fire("projectLoaded");b.render()})};c.prototype.showDialog=
function(a){if(this.APP&&this.APP.showDialog)return this.APP.showDialog(a);console.warn("Error: mbrApp is not accessible");a.buttons={success:{label:"Ok",className:"btn-primary",callback:a.success},cancel:{label:"Cancel",className:"btn-default",callback:a.cancel}};a.message=a.body;return bootbox.dialog(a)};window.mbrAppCore=new c})(jQuery);
