var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,d,c){a instanceof String&&(a=String(a));for(var e=a.length,b=0;b<e;b++){var n=a[b];if(d.call(c,n,b,a))return{i:b,v:n}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,c){a!=Array.prototype&&a!=Object.prototype&&(a[d]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,d,c,e){if(d){c=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var b=a[e];b in c||(c[b]={});c=c[b]}a=a[a.length-1];e=c[a];d=d(e);d!=e&&null!=d&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:d})}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");$jscomp.polyfill("Object.is",function(a){return a?a:function(a,c){return a===c?0!==a||1/a===1/c:a!==a&&c!==c}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(a,c){var d=this;d instanceof String&&(d=String(d));var b=d.length;c=c||0;for(0>c&&(c=Math.max(c+b,0));c<b;c++){var n=d[c];if(n===a||Object.is(n,a))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,d,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(d instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(a,c){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,c||0)}},"es6","es3");
(function(a,d){function c(b){b=b||!1;var c=d.resultJSON[d.currentPage].components.length;d.$body.find(".placeholderPage").length&&d.$body.find(".placeholderPage").remove();b||c?b&&!c?a(document.body).append(e()):(b=a(".placeholderPage"),b.length?b.remove():""):a(document.body).append(e())}var e=function(){var b=document.createElement("div");a(b).addClass("placeholderPage");var c=d.APP.TR('Click the "plus" $icon$ to add a new block.').replace("$icon$",'<br/><button class="placeholderPage__button mbr-btn btn-red"><i class="mbr-icon-plus"></i></button>');
a(b).append(d.APP.TR("This is a new empty page.")+"<br/>"+c);a(b).find("button").on("click",function(b){setTimeout(function(){a(b.target).css({pointerEvents:"none"});d.APP.$componentsToggleBtn.trigger("click")},0)});return b};d.regExtension({name:"pages",global:{getPages:function(){return this.applyFilter("getPages",a.extend(!0,{},this.resultJSON))},checkCurrentPage:function(b){return b===this.currentPage},getUniquePageName:function(b){if(!b){b=0;for(var a in this.resultJSON)this.resultJSON.hasOwnProperty(a)&&
b++}return this.resultJSON["page"+b+".html"]?this.getUniquePageName(b+1):this.applyFilter("getUniquePageName","page"+b+".html",b)},getPageComponents:function(b){b=b||this.currentPage;return this.applyFilter("getPageComponents",this.resultJSON[b]?a.extend(!0,{},this.resultJSON[b].components):!1,b)},loadPage:function(b,c){var h=(c?c.pages:this.resultJSON)[b],n=[];c=[];if("object"!=typeof h||"object"!=typeof h.settings||"object"!=typeof h.components)return console.log("Error: error component list in page",
b),a.Deferred().reject().promise();if(h.components.length&&"_id"in h.components[0])return a.when();for(var e=function(b){return(d.isSecondaryComponent(b)?a.Deferred().resolve(b).promise():d.APP.getRealComponent(b._name)).then(function(c){a:{var f=b;c||(c={});if(c._once)if(0>n.indexOf(c._once))n.push(c._once);else{console.log("Error: dublicate _once =",c._once,"at component",f._name);h.components.splice(l,1);break a}f._id=d.uniqNum();if(!d.isSecondaryComponent(c)){c=a.extend({},f._params||{});for(var g in d.components[f._name]){if("function"===
typeof d.components[f._name][g]||/_alwaysTop|_alwaysBottom|_positionAbsolute|_noDrag|_once|_group|_global|_autoPadding|_css|_js|_plugins|_afterNavbarItem/g.test(g)&&d.components[f._name][g])f[g]=d.components[f._name][g];if("_params"===g){"undefined"===typeof f[g]&&(f[g]={});var e=d.components[f._name][g],q={},k;for(k in e)"undefined"===typeof f[g][k]?q[k]=e[k].default:a.isArray(f[g][k])?q[k]=a.extend([],!0,f[g][k]):q[k]="object"===typeof f[g][k]?a.extend({},!0,f[g][k]):f[g][k];f[g]=q}}f=d.replaceSystemVariables(f,
f);"function"==typeof f._onLoadFromProject&&f._onLoadFromProject(d.components[f._name],c)}}})},l=0;l<h.components.length;){var m=h.components[l];m?(m=this.applyFilter("loadingPageComponent",m,h),function(b,a){return"string"!==typeof b?!1:"secondary"===a.theme.type||"pro.custom-html"===b?!0:b in a.components}(m._name,this)?c.push(e(m)):console.log('Error: component with name "'+m._name+'" is not registered, will be passed'),l++):(console.log("Warning: Empty component #",l,"in page",b,". Will be removed!"),
h.components.splice(l,1))}return a.when.apply(a,c)},addPage:function(b){this.fire("addPage");var a=this.getUniquePageName(),c={settings:{},components:[]};if(d.APP&&/^(default|mobirise3|mobirise4)$/.test(d.APP.theme.name)){var e=d.APP.spinText("{Website|Website|Site|Web|Web Site|Web Page} {Builder|Builder|Creator|Maker|Generator}");c.settings.meta_descr=e+" Description"}b&&(c=d.APP.getResultPage(this.resultJSON[b]),delete c.settings.main);b=/\d+/;b="Page"+(b.test(a)?" "+a.match(b):"");c.settings.title=
b;this.resultJSON[a]=this.applyFilter("addPage",c,a);this.fire("addedPage",a);return{name:a,title:b}},removePage:function(b){return this.resultJSON[b]?(this.fire("removePage",b),delete this.resultJSON[b],this.fire("removedPage",b),!0):!1},switchPage:function(b){return this.resultJSON[b]?(this.fire("switchPage",b),this.currentPage=b,this.loadPage(b).then(function(){d.render();d.fire("switchedPage",b)})):a.Deferred().reject().promise()},changePageSettings:function(b,a,c){this.fire("changePageSettings",
b);if("fileName"!==a)this.resultJSON[b].settings[a]=this.applyFilter("changePageSettings",c,a,b),this.fire("changedPageSettings",a,b);else{if(c=c.replace(/^[\.]+|["'\\\/:;<>]/g,"")){var d=c.split("."),e=d[d.length-1],h="html shtml xml php asp aspx xhtml htm jsp js".split(" ");if(2>d.length||!h.includes(e))c+=".html"}if(""!==c&&!this.resultJSON[c])return Object.defineProperty(this.resultJSON,c,Object.getOwnPropertyDescriptor(this.resultJSON,b)),delete this.resultJSON[b],this.currentPage==b&&(this.currentPage=
this.applyFilter("changePageSettings",c,a,b)),this.fire("changedPageSettings",a,b),c}return""},getPagesList:function(b){var a="",c=1,e=d.APP.sortPagesByOrder(this.getPages()),p;for(p in e){var l="";b==p&&(l='selected="selected"',c=1);var m=d.APP.escapeHtml(e[p].settings.title?e[p].settings.title:p);a+='<option value="'+p+'" '+l+' data-text="'+m+'">'+m+"</option>"}return this.applyFilter("getPagesList",'<option value="" disabled="disabled" '+(c?'selected="selected"':"")+"></option>"+a,b)}},events:{rendered:function(a){c(a)},
projectLoaded:function(){d.APP.on("hideComponents",function(){d.$body.find(".placeholderPage__button").length&&d.$body.find(".placeholderPage__button").css({pointerEvents:""})})},removedComponent:function(a){c(a)}}})})(jQuery,mbrAppCore);
